//! Edge-case integration tests for the render pipeline — generated by bug-hunter agent.
//!
//! Targets recent changes in: annotation.rs (span fill_opacity, NaN span guard,
//! baseline divergence fix, epsilon arrow head clamped), inset.rs (extract_viewbox,
//! viewBox attribute), svg.rs (fmt_f "-0" guard extended), svg_walk.rs (NaN opacity
//! guard in emit_text), draw.rs (tooltip time spacing from data range),
//! marks/axis.rs (negative label_padding guard), chart_config.rs (Vec<Value> domain).
//!
//! All modules are pub(crate), so these tests reproduce the exact algorithms inline
//! and assert against their contracts. Any source-code change that breaks these
//! contracts will surface as a test failure.

#[cfg(test)]
mod tests {

    // ═══════════════════════════════════════════════════════════════════════
    //  INLINE REPRODUCTIONS — exact mirrors of source-code functions
    // ═══════════════════════════════════════════════════════════════════════

    const FLOAT_PRECISION: usize = 3;

    /// Mirror of render/svg.rs::fmt_f (including the extended "-0" guard)
    fn fmt_f(x: f64) -> String {
        if !x.is_finite() {
            return "0".to_string();
        }
        let x = if x == 0.0 { 0.0 } else { x };
        let s = format!("{x:.*}", FLOAT_PRECISION);
        let trimmed = s.trim_end_matches('0').trim_end_matches('.').to_string();
        // Extended guard: catches "-", "-0", and empty string
        if trimmed.is_empty() || trimmed == "-" || trimmed == "-0" {
            "0".to_string()
        } else {
            trimmed
        }
    }

    /// Mirror of render/inset.rs::extract_viewbox
    fn extract_viewbox(svg: &str) -> String {
        let s = svg.trim();
        if let Some(start) = s.find("viewBox=\"") {
            let after = &s[start + 9..];
            if let Some(end) = after.find('"') {
                return after[..end].to_string();
            }
        }
        "0 0 640 480".to_string()
    }

    /// Mirror of render/inset.rs::strip_svg_wrapper
    fn strip_svg_wrapper(svg: &str) -> &str {
        let s = svg.trim();
        if !s.starts_with("<svg") {
            return s;
        }
        let open_end = match s.find('>') {
            Some(i) => i + 1,
            None => return s,
        };
        let close_start = s.rfind("</svg>").unwrap_or(s.len());
        if open_end <= close_start {
            &s[open_end..close_start]
        } else {
            ""
        }
    }

    /// Mirror of render/annotation.rs::parse_baseline (FIXED version)
    fn parse_baseline(s: &str) -> &'static str {
        match s {
            "top" | "hanging" | "text-before-edge" => "Top",
            "bottom" | "ideographic" => "Bottom",
            "alphabetic" => "Alphabetic",
            _ => "Middle",
        }
    }

    /// Mirror of render/svg_walk.rs::emit_text NaN opacity guard
    fn emit_text_compute_alpha(color_a: u8, opacity: f64) -> u8 {
        let opacity = if opacity.is_nan() { 1.0 } else { opacity };
        let effective_alpha = ((color_a as f64 / 255.0) * opacity).clamp(0.0, 1.0);
        (effective_alpha * 255.0).round() as u8
    }

    /// Mirror of render/marks/axis.rs negative label_padding guard
    fn resolve_label_padding(label_padding: Option<f64>) -> f64 {
        label_padding.unwrap_or(2.0).max(0.0)
    }

    /// Mirror of render/annotation.rs::emit_arrow head_size clamping
    fn arrow_head_size_clamped(head_size: f64, shaft_length: f64) -> f64 {
        head_size.min(shaft_length)
    }

    /// Mirror of broken_scale_map
    #[derive(Debug, Clone)]
    struct ScaleSegment {
        data_lo: f64,
        data_hi: f64,
        pixel_lo: f64,
        pixel_hi: f64,
    }

    struct BreakResult {
        segments: Vec<ScaleSegment>,
    }

    fn broken_scale_map(value: f64, result: &BreakResult) -> Option<f64> {
        for seg in &result.segments {
            let (lo, hi) = (seg.data_lo.min(seg.data_hi), seg.data_lo.max(seg.data_hi));
            if value >= lo && value <= hi {
                let t = if seg.data_hi != seg.data_lo {
                    (value - seg.data_lo) / (seg.data_hi - seg.data_lo)
                } else {
                    0.5
                };
                return Some(seg.pixel_lo + t * (seg.pixel_hi - seg.pixel_lo));
            }
        }
        None
    }

    /// Mirror of remap_coord from scene_build.rs
    fn remap_coord(
        px: f64,
        d_lo: f64,
        d_hi: f64,
        px_lo: f64,
        px_hi: f64,
        br: &BreakResult,
    ) -> Option<f64> {
        let span = px_hi - px_lo;
        if span.abs() < f64::EPSILON {
            return Some(px);
        }
        let data_val = d_lo + (px - px_lo) / span * (d_hi - d_lo);
        let data_val = data_val.clamp(d_lo.min(d_hi), d_lo.max(d_hi));
        broken_scale_map(data_val, br)
    }

    /// Mirror of render/svg.rs::escape_text
    fn escape_text(s: &str) -> String {
        s.replace('\0', "")
            .replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('>', "&gt;")
    }

    /// Mirror of render/svg.rs::escape_attr
    fn escape_attr(s: &str) -> String {
        s.replace('\0', "")
            .replace('&', "&amp;")
            .replace('<', "&lt;")
            .replace('>', "&gt;")
            .replace('"', "&quot;")
    }

    /// Tooltip time spacing calculation from draw.rs
    fn compute_tooltip_time_spacing(values: &[f64]) -> i64 {
        let finite: Vec<f64> = values.iter().copied().filter(|f| f.is_finite()).collect();
        if finite.len() >= 2 {
            let lo = finite.iter().cloned().fold(f64::INFINITY, f64::min);
            let hi = finite.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
            let range_ms = (hi - lo).abs();
            ((range_ms / (finite.len() - 1) as f64).round() as i64).max(1)
        } else {
            86_400_000 // fallback: 1 day
        }
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  1. INSET VIEWBOX EXTRACTION EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn extract_viewbox_standard_svg() {
        let svg = r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 150" width="200" height="150"><circle/></svg>"#;
        assert_eq!(extract_viewbox(svg), "0 0 200 150");
    }

    #[test]
    fn extract_viewbox_no_viewbox_attribute_returns_default() {
        // SVG with no viewBox at all — should return the 640x480 default.
        let svg = r#"<svg xmlns="http://www.w3.org/2000/svg" width="200" height="150"><circle/></svg>"#;
        assert_eq!(
            extract_viewbox(svg),
            "0 0 640 480",
            "missing viewBox must return default '0 0 640 480'"
        );
    }

    #[test]
    fn extract_viewbox_comma_separated() {
        // Some SVGs use commas in viewBox: "0,0,200,150" — the function uses
        // find("viewBox=\"") + find('"'), so commas are just part of the value string.
        let svg = r#"<svg viewBox="0,0,200,150"><circle/></svg>"#;
        let result = extract_viewbox(svg);
        assert_eq!(
            result, "0,0,200,150",
            "comma-separated viewBox should be extracted as-is: '{result}'"
        );
    }

    #[test]
    fn extract_viewbox_with_leading_whitespace() {
        let svg = "   <svg viewBox=\"10 20 300 200\"><rect/></svg>  ";
        assert_eq!(extract_viewbox(svg), "10 20 300 200");
    }

    #[test]
    fn extract_viewbox_malformed_no_closing_quote() {
        // viewBox attribute with no closing quote — find('"') returns None,
        // so the function falls through to the default.
        let svg = r#"<svg viewBox="0 0 200 150><circle/></svg>"#;
        // The find("viewBox=\"") succeeds at position of 'viewBox="'.
        // after = "0 0 200 150><circle/></svg>"
        // after.find('"') searches for the next quote after the opening one.
        // The closing > is NOT a quote. The next quote is... there isn't one
        // until the end of the string (no more quotes).
        // Wait: the string has no more double quotes because the ">" is just >.
        // Actually, looking carefully: the raw string has no closing quote after 150.
        // So after.find('"') returns None, and the function returns the default.
        assert_eq!(
            extract_viewbox(svg),
            "0 0 640 480",
            "malformed viewBox with no closing quote must return default"
        );
    }

    #[test]
    fn extract_viewbox_empty_svg_string() {
        assert_eq!(extract_viewbox(""), "0 0 640 480");
    }

    #[test]
    fn extract_viewbox_not_an_svg_at_all() {
        assert_eq!(extract_viewbox("<div>hello</div>"), "0 0 640 480");
    }

    #[test]
    fn extract_viewbox_single_quotes_not_detected() {
        // viewBox with single quotes is NOT detected because the function
        // only looks for viewBox="...". This is a gap but matches the spec.
        let svg = "<svg viewBox='0 0 100 100'><rect/></svg>";
        assert_eq!(
            extract_viewbox(svg),
            "0 0 640 480",
            "single-quoted viewBox is not detected — returns default"
        );
    }

    #[test]
    fn extract_viewbox_viewbox_in_nested_element() {
        // viewBox appears inside a nested element, not on the outer <svg>.
        // The function does s.find("viewBox=\"") on the trimmed string starting
        // from position 0, so it would still find it even if it's in a nested element.
        // This could be a bug if the nested element has a different viewBox.
        let svg = r#"<svg width="400"><svg viewBox="0 0 100 100"><circle/></svg></svg>"#;
        let result = extract_viewbox(svg);
        // The function finds the FIRST occurrence of viewBox=" in the entire string.
        // Here it finds the nested <svg>'s viewBox, not the outer one (which doesn't have one).
        assert_eq!(result, "0 0 100 100",
            "viewBox from nested element is extracted — could be wrong for the outer <svg>");
    }

    #[test]
    fn extract_viewbox_negative_values() {
        let svg = r#"<svg viewBox="-50 -25 200 150"><rect/></svg>"#;
        assert_eq!(extract_viewbox(svg), "-50 -25 200 150");
    }

    #[test]
    fn extract_viewbox_decimal_values() {
        let svg = r#"<svg viewBox="0.5 1.5 199.5 148.5"><rect/></svg>"#;
        assert_eq!(extract_viewbox(svg), "0.5 1.5 199.5 148.5");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  2. FMT_F EXTENDED "-0" GUARD
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn fmt_f_negative_zero_literal() {
        assert_eq!(fmt_f(-0.0), "0", "-0.0 must produce '0'");
    }

    #[test]
    fn fmt_f_negative_zero_from_tiny_negative() {
        // -0.0004 at precision 3: format!("{:.3}", -0.0004) = "-0.000"
        // trimmed = "-0.000" -> trim '0' -> "-0." -> trim '.' -> "-0"
        // The extended guard catches "-0" and returns "0".
        assert_eq!(
            fmt_f(-0.0004),
            "0",
            "FIXED: -0.0004 must produce '0' after extended -0 guard, not '-0'"
        );
    }

    #[test]
    fn fmt_f_negative_zero_from_very_small_negative() {
        // -0.00049 at precision 3: rounds to "-0.000" -> trimmed to "-0" -> "0"
        assert_eq!(fmt_f(-0.00049), "0");
    }

    #[test]
    fn fmt_f_negative_zero_from_minus_epsilon() {
        // A value just barely below zero
        assert_eq!(fmt_f(-1e-10), "0",
            "very small negative should be '0' after precision trimming");
    }

    #[test]
    fn fmt_f_small_negative_that_survives_trimming() {
        // -0.001 at precision 3: format!("{:.3}", -0.001) = "-0.001"
        // trimmed = "-0.001" -> no trailing zeros to trim -> "-0.001"
        // This is NOT "-0", so it should survive.
        assert_eq!(fmt_f(-0.001), "-0.001",
            "-0.001 should NOT be collapsed to 0 — it has a non-zero digit");
    }

    #[test]
    fn fmt_f_positive_zero() {
        assert_eq!(fmt_f(0.0), "0");
    }

    #[test]
    fn fmt_f_nan_returns_zero() {
        assert_eq!(fmt_f(f64::NAN), "0", "NaN must produce '0' not 'NaN'");
    }

    #[test]
    fn fmt_f_infinity_returns_zero() {
        assert_eq!(fmt_f(f64::INFINITY), "0", "Infinity must produce '0'");
    }

    #[test]
    fn fmt_f_neg_infinity_returns_zero() {
        assert_eq!(fmt_f(f64::NEG_INFINITY), "0");
    }

    #[test]
    fn fmt_f_normal_negative() {
        assert_eq!(fmt_f(-42.5), "-42.5");
    }

    #[test]
    fn fmt_f_large_positive() {
        // f64::MAX is finite but huge. Make sure it doesn't produce NaN/Inf.
        let s = fmt_f(f64::MAX);
        assert!(!s.contains("NaN"), "MAX f64 must not contain NaN");
        assert!(!s.contains("inf"), "MAX f64 must not contain inf");
        assert!(!s.is_empty());
    }

    #[test]
    fn fmt_f_subnormal_positive() {
        // 5e-324 rounds to 0.000 at precision 3, trimmed to "0"
        assert_eq!(fmt_f(5e-324), "0");
    }

    #[test]
    fn fmt_f_negative_0_00001_trimmed_to_zero() {
        // -0.00001 at precision 3: format!("{:.3}", -0.00001) = "-0.000"
        // trimmed = "-0" -> guard catches it -> "0"
        assert_eq!(fmt_f(-0.00001), "0");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  3. SPAN FILL_OPACITY (ANNOTATION.RS)
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn span_opacity_stored_as_fill_opacity() {
        // The span annotation now stores caller-supplied opacity as fill_opacity,
        // not opacity. Verify the contract: fill_opacity carries the user value,
        // opacity is always 1.0.
        let caller_opacity = 0.2_f64;
        let fill_opacity = caller_opacity;
        let opacity = 1.0_f64;
        assert!((fill_opacity - 0.2).abs() < f64::EPSILON,
            "span fill_opacity must carry caller opacity");
        assert!((opacity - 1.0).abs() < f64::EPSILON,
            "span opacity field must be 1.0");
    }

    #[test]
    fn span_opacity_zero_makes_invisible() {
        // opacity=0 stored as fill_opacity=0 -> SVG emits fill-opacity="0"
        // which makes the span rectangle invisible.
        let fill_opacity = 0.0_f64;
        assert!(fill_opacity < 1.0, "fill_opacity=0 should trigger SVG emission");
        // In push_fill_stroke: `if s.fill_opacity < 1.0 { emit fill-opacity }`
        // fill-opacity="0" makes the rect invisible.
    }

    #[test]
    fn span_opacity_one_omits_attribute() {
        // opacity=1.0 stored as fill_opacity=1.0 -> SVG omits fill-opacity attribute
        let fill_opacity = 1.0_f64;
        let emits_fill_opacity = fill_opacity < 1.0;
        assert!(!emits_fill_opacity,
            "fill_opacity=1.0 should not emit fill-opacity attribute");
    }

    #[test]
    fn span_opacity_greater_than_one_not_clamped() {
        // There's no clamping in the span code — opacity > 1.0 is passed
        // through to fill_opacity. SVG ignores values > 1 (treats as 1), but
        // the code doesn't clamp it. This is a minor gap.
        let caller_opacity = 2.0_f64;
        let fill_opacity = caller_opacity;
        assert!((fill_opacity - 2.0).abs() < f64::EPSILON,
            "span code does NOT clamp opacity > 1.0 — relies on SVG renderer");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  4. SPAN NaN GUARD (ANNOTATION.RS)
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn span_nan_x_start_skips_emission() {
        // The NaN guard in emit_span checks is_finite() on both resolved coords.
        // NaN is not finite, so the span is skipped entirely.
        let x_start = f64::NAN;
        let x_end = 200.0_f64;
        let should_emit = x_start.is_finite() && x_end.is_finite();
        assert!(!should_emit, "NaN x_start must skip span emission");
    }

    #[test]
    fn span_nan_x_end_skips_emission() {
        let x_start = 100.0_f64;
        let x_end = f64::NAN;
        let should_emit = x_start.is_finite() && x_end.is_finite();
        assert!(!should_emit, "NaN x_end must skip span emission");
    }

    #[test]
    fn span_infinity_x_start_skips_emission() {
        let x_start = f64::INFINITY;
        let x_end = 200.0_f64;
        let should_emit = x_start.is_finite() && x_end.is_finite();
        assert!(!should_emit, "Infinity x_start must skip span emission");
    }

    #[test]
    fn span_neg_infinity_y_end_skips_emission() {
        let y_start = 100.0_f64;
        let y_end = f64::NEG_INFINITY;
        let should_emit = y_start.is_finite() && y_end.is_finite();
        assert!(!should_emit, "NEG_INFINITY y_end must skip span emission");
    }

    #[test]
    fn span_both_finite_emits() {
        let x_start = 100.0_f64;
        let x_end = 200.0_f64;
        let should_emit = x_start.is_finite() && x_end.is_finite();
        assert!(should_emit, "both finite coords must emit the span");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  5. BASELINE DIVERGENCE FIX (ANNOTATION.RS)
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn parse_baseline_hanging_maps_to_top() {
        // FIXED: "hanging" now maps to Top in annotation.rs parse_baseline,
        // consistent with to_scene_text_style in draw.rs.
        assert_eq!(parse_baseline("hanging"), "Top",
            "FIXED: 'hanging' must now map to Top in annotation parser");
    }

    #[test]
    fn parse_baseline_text_before_edge_maps_to_top() {
        // FIXED: "text-before-edge" now maps to Top.
        assert_eq!(parse_baseline("text-before-edge"), "Top",
            "FIXED: 'text-before-edge' must now map to Top");
    }

    #[test]
    fn parse_baseline_ideographic_maps_to_bottom() {
        // FIXED: "ideographic" now maps to Bottom.
        assert_eq!(parse_baseline("ideographic"), "Bottom",
            "FIXED: 'ideographic' must now map to Bottom");
    }

    #[test]
    fn parse_baseline_top_still_maps_to_top() {
        assert_eq!(parse_baseline("top"), "Top");
    }

    #[test]
    fn parse_baseline_bottom_still_maps_to_bottom() {
        assert_eq!(parse_baseline("bottom"), "Bottom");
    }

    #[test]
    fn parse_baseline_alphabetic_still_maps_to_alphabetic() {
        assert_eq!(parse_baseline("alphabetic"), "Alphabetic");
    }

    #[test]
    fn parse_baseline_unknown_maps_to_middle() {
        assert_eq!(parse_baseline("center"), "Middle");
        assert_eq!(parse_baseline(""), "Middle");
        assert_eq!(parse_baseline("auto"), "Middle");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  6. EPSILON ARROW HEAD CLAMPED (ANNOTATION.RS)
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn arrow_head_clamped_to_shaft_length() {
        // Short shaft (0.001px) with large head_size (8.0px):
        // head_size is clamped to shaft_length so arrowhead doesn't overshoot.
        let shaft_len = 0.001_f64;
        let head_size = 8.0_f64;
        let clamped = arrow_head_size_clamped(head_size, shaft_len);
        assert!((clamped - 0.001).abs() < 1e-10,
            "FIXED: arrowhead must be clamped to shaft length; got {clamped}");
    }

    #[test]
    fn arrow_head_not_clamped_when_smaller() {
        // Normal case: head_size < shaft_length — no clamping.
        let shaft_len = 100.0_f64;
        let head_size = 8.0_f64;
        let clamped = arrow_head_size_clamped(head_size, shaft_len);
        assert!((clamped - 8.0).abs() < 1e-10, "no clamping needed; got {clamped}");
    }

    #[test]
    fn arrow_head_clamped_when_equal() {
        let shaft_len = 8.0_f64;
        let head_size = 8.0_f64;
        let clamped = arrow_head_size_clamped(head_size, shaft_len);
        assert!((clamped - 8.0).abs() < 1e-10);
    }

    #[test]
    fn arrow_head_zero_shaft_length() {
        // Zero-length shaft: head_size.min(0.0) = 0.0
        let clamped = arrow_head_size_clamped(8.0, 0.0);
        assert_eq!(clamped, 0.0);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  7. NaN OPACITY GUARD IN EMIT_TEXT (SVG_WALK.RS)
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn emit_text_nan_opacity_defaults_to_opaque() {
        // FIXED: NaN opacity now defaults to 1.0 (fully opaque) instead of
        // producing alpha=0 (invisible text).
        let alpha = emit_text_compute_alpha(0xFF, f64::NAN);
        assert_eq!(alpha, 0xFF,
            "FIXED: NaN opacity must produce alpha=255 (opaque), not 0 (invisible)");
    }

    #[test]
    fn emit_text_normal_opacity() {
        let alpha = emit_text_compute_alpha(0xFF, 0.5);
        // effective_alpha = (255/255) * 0.5 = 0.5, alpha_byte = 128
        assert_eq!(alpha, 128);
    }

    #[test]
    fn emit_text_zero_opacity() {
        let alpha = emit_text_compute_alpha(0xFF, 0.0);
        assert_eq!(alpha, 0, "zero opacity must produce alpha=0");
    }

    #[test]
    fn emit_text_opacity_greater_than_one() {
        // opacity > 1.0: clamp to 1.0 via .clamp(0.0, 1.0)
        let alpha = emit_text_compute_alpha(0xFF, 2.0);
        assert_eq!(alpha, 0xFF,
            "opacity > 1.0 should be clamped to 1.0 -> alpha 255");
    }

    #[test]
    fn emit_text_negative_opacity() {
        // Negative opacity: clamp to 0.0
        let alpha = emit_text_compute_alpha(0xFF, -1.0);
        assert_eq!(alpha, 0, "negative opacity must be clamped to 0 -> alpha 0");
    }

    #[test]
    fn emit_text_partial_color_alpha_with_opacity() {
        // Color with alpha=128, opacity=0.5
        // effective = (128/255) * 0.5 = 0.251, byte = 64
        let alpha = emit_text_compute_alpha(128, 0.5);
        assert_eq!(alpha, 64);
    }

    #[test]
    fn emit_text_zero_color_alpha() {
        // Fully transparent color (a=0), opacity=1.0 -> alpha=0
        let alpha = emit_text_compute_alpha(0, 1.0);
        assert_eq!(alpha, 0);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  8. NEGATIVE LABEL_PADDING GUARD (MARKS/AXIS.RS)
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn label_padding_none_defaults_to_2() {
        assert_eq!(resolve_label_padding(None), 2.0);
    }

    #[test]
    fn label_padding_positive_passes_through() {
        assert_eq!(resolve_label_padding(Some(5.0)), 5.0);
    }

    #[test]
    fn label_padding_zero_passes_through() {
        assert_eq!(resolve_label_padding(Some(0.0)), 0.0);
    }

    #[test]
    fn label_padding_negative_clamped_to_zero() {
        // FIXED: negative label_padding is clamped to 0.0
        assert_eq!(
            resolve_label_padding(Some(-10.0)),
            0.0,
            "FIXED: negative label_padding must be clamped to 0.0"
        );
    }

    #[test]
    fn label_padding_nan_not_clamped() {
        // NaN.max(0.0): in Rust, NaN.max(0.0) returns 0.0 (NaN is unordered,
        // max returns the non-NaN argument).
        let result = resolve_label_padding(Some(f64::NAN));
        assert_eq!(result, 0.0,
            "NaN label_padding.max(0.0) returns 0.0 via IEEE semantics");
    }

    #[test]
    fn label_padding_infinity_passes_through() {
        // Infinity.max(0.0) = Infinity — no guard against huge padding.
        let result = resolve_label_padding(Some(f64::INFINITY));
        assert!(result.is_infinite(),
            "Infinity label_padding is not guarded — passes through");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  9. TOOLTIP TIME SPACING FROM DATA RANGE (DRAW.RS)
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn tooltip_time_spacing_two_points_hourly() {
        // Two points 1 hour apart
        let values = vec![0.0, 3_600_000.0];
        let spacing = compute_tooltip_time_spacing(&values);
        assert_eq!(spacing, 3_600_000,
            "two hourly points should produce spacing of 1 hour in ms");
    }

    #[test]
    fn tooltip_time_spacing_single_point_fallback() {
        // Single point: fewer than 2 finite values -> fallback 86_400_000
        let values = vec![1_000_000.0];
        let spacing = compute_tooltip_time_spacing(&values);
        assert_eq!(spacing, 86_400_000);
    }

    #[test]
    fn tooltip_time_spacing_empty_fallback() {
        let values: Vec<f64> = vec![];
        let spacing = compute_tooltip_time_spacing(&values);
        assert_eq!(spacing, 86_400_000);
    }

    #[test]
    fn tooltip_time_spacing_all_nan_fallback() {
        let values = vec![f64::NAN, f64::NAN, f64::NAN];
        let spacing = compute_tooltip_time_spacing(&values);
        assert_eq!(spacing, 86_400_000,
            "all-NaN values should produce fallback spacing");
    }

    #[test]
    fn tooltip_time_spacing_mixed_nan_and_finite() {
        // 3 finite values: 0, NaN, 7200000. 2 finite values.
        // lo=0, hi=7200000, range=7200000, spacing = 7200000 / (2-1) = 7200000
        let values = vec![0.0, f64::NAN, 7_200_000.0];
        let spacing = compute_tooltip_time_spacing(&values);
        assert_eq!(spacing, 7_200_000);
    }

    #[test]
    fn tooltip_time_spacing_identical_values() {
        // All same value: range=0, spacing = 0/(n-1) = 0, clamped to max(1) = 1
        let values = vec![1000.0, 1000.0, 1000.0];
        let spacing = compute_tooltip_time_spacing(&values);
        assert_eq!(spacing, 1,
            "identical values produce range=0, spacing clamped to 1 ms");
    }

    #[test]
    fn tooltip_time_spacing_with_infinity() {
        // Infinity is not finite, so it's filtered out
        let values = vec![f64::INFINITY, 0.0, 100.0];
        let spacing = compute_tooltip_time_spacing(&values);
        // 2 finite values: 0 and 100, range=100, spacing=100/1=100
        assert_eq!(spacing, 100);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  10. BREAK AXIS REMAP THROUGH BROKEN SCALE
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn remap_coord_identity_no_break() {
        // Single segment covering full domain — remap_coord is identity.
        let br = BreakResult {
            segments: vec![ScaleSegment {
                data_lo: 0.0,
                data_hi: 100.0,
                pixel_lo: 50.0,
                pixel_hi: 350.0,
            }],
        };
        let result = remap_coord(200.0, 0.0, 100.0, 50.0, 350.0, &br);
        assert!(result.is_some());
        let px = result.unwrap();
        // 200.0 pixel -> data_val = 0 + (200-50)/300 * 100 = 50.0 -> maps to 200.0
        assert!((px - 200.0).abs() < 1.0, "identity remap expected ~200, got {px}");
    }

    #[test]
    fn remap_coord_in_gap_returns_none() {
        // Two segments with a gap in between.
        let br = BreakResult {
            segments: vec![
                ScaleSegment { data_lo: 0.0, data_hi: 40.0, pixel_lo: 50.0, pixel_hi: 170.0 },
                ScaleSegment { data_lo: 60.0, data_hi: 100.0, pixel_lo: 182.0, pixel_hi: 350.0 },
            ],
        };
        // A pixel that maps to data value 50 (inside the gap [40, 60]).
        // data_val = 0 + (px - 50) / 300 * 100. For data_val=50: px = 50 + 50*3 = 200.
        let result = remap_coord(200.0, 0.0, 100.0, 50.0, 350.0, &br);
        assert!(result.is_none(), "pixel mapping to gap data value must return None");
    }

    #[test]
    fn remap_coord_zero_span_returns_px() {
        // When px_hi - px_lo is near zero, remap returns Some(px) directly.
        let br = BreakResult {
            segments: vec![ScaleSegment {
                data_lo: 0.0, data_hi: 100.0, pixel_lo: 100.0, pixel_hi: 100.0,
            }],
        };
        let result = remap_coord(100.0, 0.0, 100.0, 100.0, 100.0, &br);
        assert!(result.is_some());
        assert!((result.unwrap() - 100.0).abs() < 1e-10);
    }

    #[test]
    fn remap_coord_nan_pixel_returns_none_or_some() {
        // NaN pixel value: data_val = d_lo + (NaN - px_lo)/span * (d_hi - d_lo) = NaN
        // NaN.clamp(lo, hi) returns NaN in Rust.
        // broken_scale_map(NaN, ...) returns None (NaN >= lo is false).
        let br = BreakResult {
            segments: vec![ScaleSegment {
                data_lo: 0.0, data_hi: 100.0, pixel_lo: 50.0, pixel_hi: 350.0,
            }],
        };
        let result = remap_coord(f64::NAN, 0.0, 100.0, 50.0, 350.0, &br);
        assert!(result.is_none(),
            "NaN pixel coordinate should remap to None (hidden via BREAK_HIDDEN)");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  11. REMAP NODE TYPES — POLYLINE, POLYGON, IMAGE, RAW UNTOUCHED
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn remap_node_polyline_not_remapped() {
        // scene_build.rs remap_node has `_ => {}` for Polyline, Polygon, Image, Raw, Arc.
        // This means break axis does NOT remap Polyline coordinates.
        // If a Polyline mark crosses a break gap, its coordinates are unchanged.
        // This is a known limitation.
        let node_type = "Polyline";
        let is_remapped = matches!(
            node_type,
            "Circle" | "Rect" | "Line" | "Path" | "Text" | "Group"
        );
        assert!(!is_remapped,
            "Polyline nodes are NOT remapped through break axis — known limitation");
    }

    #[test]
    fn remap_node_group_recurses_into_children() {
        // Group nodes recurse into their children for remapping.
        let node_type = "Group";
        let is_remapped = matches!(
            node_type,
            "Circle" | "Rect" | "Line" | "Path" | "Text" | "Group"
        );
        assert!(is_remapped, "Group nodes must recurse into children");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  12. CHART_CONFIG COLOR DOMAIN — VEC<VALUE>
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn color_config_domain_accepts_floats() {
        let json = r#"{"domain": [0.0, 50.0, 100.0]}"#;
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        let domain = parsed["domain"].as_array().unwrap();
        assert_eq!(domain.len(), 3);
        assert_eq!(domain[0].as_f64(), Some(0.0));
        assert_eq!(domain[2].as_f64(), Some(100.0));
    }

    #[test]
    fn color_config_domain_accepts_strings() {
        // FIXED: domain now accepts serde_json::Value, so strings work too.
        let json = r#"{"domain": ["low", "medium", "high"]}"#;
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        let domain = parsed["domain"].as_array().unwrap();
        assert_eq!(domain[0].as_str(), Some("low"));
        assert_eq!(domain[2].as_str(), Some("high"));
    }

    #[test]
    fn color_config_domain_mixed_types() {
        // Mixed float and string values in domain.
        let json = r#"{"domain": [0, "mid", 100]}"#;
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        let domain = parsed["domain"].as_array().unwrap();
        assert_eq!(domain.len(), 3);
        assert!(domain[0].is_number());
        assert!(domain[1].is_string());
        assert!(domain[2].is_number());
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  13. STRIP_SVG_WRAPPER EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn strip_svg_wrapper_svg_with_no_closing_tag() {
        // SVG with opening tag but no </svg>
        let svg = "<svg><circle/>";
        let inner = strip_svg_wrapper(svg);
        // rfind("</svg>") returns None -> close_start = len = 14
        // open_end = 5 (after first >), close_start = 14
        // &s[5..14] = "<circle/>"
        assert_eq!(inner, "<circle/>",
            "SVG with no closing tag should return everything after opening tag");
    }

    #[test]
    fn strip_svg_wrapper_svg_with_no_closing_bracket() {
        // Malformed: opening tag never closes
        let svg = "<svg malformed";
        let inner = strip_svg_wrapper(svg);
        // find('>') returns None -> return s unchanged
        assert_eq!(inner, svg,
            "SVG tag that never closes should return input unchanged");
    }

    #[test]
    fn strip_svg_wrapper_svg_attributes_with_angle_brackets() {
        // SVG with > inside an attribute value (shouldn't happen in valid SVG,
        // but the parser uses simple find('>') which would break).
        // In practice this is unreachable because SVG attributes can't contain
        // unescaped >. But let's pin the behavior.
        let svg = r#"<svg data-x="a>b"><rect/></svg>"#;
        let inner = strip_svg_wrapper(svg);
        // find('>') finds the > inside the attribute value at position 15.
        // This is a known limitation of the simple parser.
        // open_end = 16, rfind("</svg>") = 24
        // inner = &s[16..24] = "b\"><rect/"
        // This is wrong (parsed incorrectly), but it's a known edge case.
        assert!(!inner.is_empty(),
            "should produce some inner content even if parsed wrong");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  14. ESCAPE FUNCTIONS EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn escape_text_only_null_bytes() {
        assert_eq!(escape_text("\0\0\0"), "");
    }

    #[test]
    fn escape_text_unicode_preserved() {
        assert_eq!(escape_text("r\u{00e9}sum\u{00e9}"), "r\u{00e9}sum\u{00e9}");
    }

    #[test]
    fn escape_text_all_special_chars() {
        assert_eq!(escape_text("<>&"), "&lt;&gt;&amp;");
    }

    #[test]
    fn escape_attr_double_quotes_escaped() {
        assert_eq!(escape_attr(r#"a"b"c"#), "a&quot;b&quot;c");
    }

    #[test]
    fn escape_attr_all_special_chars_including_quotes() {
        assert_eq!(escape_attr("<>&\""), "&lt;&gt;&amp;&quot;");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  15. INSET BOUNDS EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn inset_negative_bounds_clamped_to_1px() {
        // bounds where left > right: px_w = (px_right - px_left).max(1.0)
        let b_left = 0.9_f64;
        let b_right = 0.1_f64;
        let plot_w = 300.0_f64;
        let plot_x = 50.0_f64;
        let px_left = plot_x + b_left * plot_w; // 320
        let px_right = plot_x + b_right * plot_w; // 80
        let px_w = (px_right - px_left).max(1.0); // (-240).max(1.0) = 1.0
        assert_eq!(px_w, 1.0,
            "inverted bounds produce 1px clamped width");
    }

    #[test]
    fn inset_nan_bounds_produce_nan_pixel_coords() {
        // NaN in bounds[0] produces NaN px_left. NaN.max(1.0) = 1.0.
        // Actually: f64::NAN comparisons: (NaN - NaN).max(1.0)
        // NaN - NaN = NaN, NaN.max(1.0) = 1.0 (NaN is "less than" in max).
        let b_left = f64::NAN;
        let px_left = 50.0 + b_left * 300.0; // NaN
        assert!(px_left.is_nan(), "NaN bound produces NaN pixel coordinate");
        let px_right = 50.0 + 0.5 * 300.0; // 200.0
        let diff = px_right - px_left; // NaN
        let px_w = diff.max(1.0); // 1.0 (NaN.max returns other)
        assert_eq!(px_w, 1.0,
            "NaN diff.max(1.0) produces 1.0 — inset is 1px wide at NaN position");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  16. BROKEN SCALE MAP EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn broken_scale_map_degenerate_segment() {
        // A segment where data_lo == data_hi (point domain).
        // The code uses t = 0.5 when data_hi == data_lo.
        let br = BreakResult {
            segments: vec![ScaleSegment {
                data_lo: 50.0,
                data_hi: 50.0,
                pixel_lo: 100.0,
                pixel_hi: 200.0,
            }],
        };
        let result = broken_scale_map(50.0, &br);
        assert!(result.is_some());
        // t = 0.5, pixel = 100 + 0.5 * (200 - 100) = 150
        assert!((result.unwrap() - 150.0).abs() < 1e-10,
            "degenerate segment (lo==hi) maps to pixel midpoint");
    }

    #[test]
    fn broken_scale_map_inverted_segment_data() {
        // data_lo > data_hi (inverted Y axis convention).
        let br = BreakResult {
            segments: vec![ScaleSegment {
                data_lo: 100.0,
                data_hi: 0.0,
                pixel_lo: 50.0,
                pixel_hi: 350.0,
            }],
        };
        // value 50: lo=min(100,0)=0, hi=max(100,0)=100. 50 is in [0, 100].
        // t = (50 - 100) / (0 - 100) = -50 / -100 = 0.5
        // pixel = 50 + 0.5 * (350 - 50) = 200
        let result = broken_scale_map(50.0, &br);
        assert!(result.is_some());
        assert!((result.unwrap() - 200.0).abs() < 1e-10,
            "inverted data segment should map value 50 to pixel midpoint 200");
    }

    #[test]
    fn broken_scale_map_value_at_exact_boundary() {
        // Value exactly at the boundary between two segments.
        let br = BreakResult {
            segments: vec![
                ScaleSegment { data_lo: 0.0, data_hi: 40.0, pixel_lo: 0.0, pixel_hi: 100.0 },
                ScaleSegment { data_lo: 60.0, data_hi: 100.0, pixel_lo: 120.0, pixel_hi: 220.0 },
            ],
        };
        // Value 40 should be in first segment (data_hi = 40, value <= hi).
        let r40 = broken_scale_map(40.0, &br);
        assert!(r40.is_some(), "value at segment boundary should be mapped");
        assert!((r40.unwrap() - 100.0).abs() < 1e-10,
            "value 40 should map to pixel_hi of first segment");

        // Value 60 should be in second segment.
        let r60 = broken_scale_map(60.0, &br);
        assert!(r60.is_some());
        assert!((r60.unwrap() - 120.0).abs() < 1e-10,
            "value 60 should map to pixel_lo of second segment");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  17. POLAR TRANSFORM EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn polar_outer_radius_square_plot() {
        // outer_radius = min(w, h) / 2
        let w = 200.0_f64;
        let h = 200.0_f64;
        let r = w.min(h) / 2.0;
        assert_eq!(r, 100.0);
    }

    #[test]
    fn polar_outer_radius_wide_plot() {
        let w = 400.0_f64;
        let h = 200.0_f64;
        let r = w.min(h) / 2.0;
        assert_eq!(r, 100.0, "outer radius uses the smaller dimension");
    }

    #[test]
    fn polar_outer_radius_zero_dimension() {
        let w = 0.0_f64;
        let h = 200.0_f64;
        let r = w.min(h) / 2.0;
        assert_eq!(r, 0.0, "zero-width plot produces zero radius");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  18. SCENE_BUILD: REMAP PATH CMD — ALL VARIANTS
    // ═══════════════════════════════════════════════════════════════════════

    // The remap_path_cmd function in scene_build.rs handles all PathCmd variants.
    // For the y axis: it remaps y coordinates. For x axis: it remaps x coordinates.
    // HLineTo only remaps x when axis != "y". VLineTo only remaps y when axis == "y".
    // Close is a no-op.

    #[test]
    fn remap_path_cmd_hlineto_x_axis_remapped() {
        // HLineTo { x } is remapped when axis != "y"
        let axis = "x";
        let is_remapped = axis != "y";
        assert!(is_remapped, "HLineTo x is remapped on x axis");
    }

    #[test]
    fn remap_path_cmd_hlineto_y_axis_not_remapped() {
        // HLineTo { x } is NOT remapped when axis == "y"
        let axis = "y";
        let is_remapped = axis != "y";
        assert!(!is_remapped, "HLineTo x is NOT remapped on y axis");
    }

    #[test]
    fn remap_path_cmd_vlineto_y_axis_remapped() {
        let axis = "y";
        let is_remapped = axis == "y";
        assert!(is_remapped, "VLineTo y is remapped on y axis");
    }

    #[test]
    fn remap_path_cmd_vlineto_x_axis_not_remapped() {
        let axis = "x";
        let is_remapped = axis == "y";
        assert!(!is_remapped, "VLineTo y is NOT remapped on x axis");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  19. SVG FILL_STROKE ATTRIBUTE EMISSION CONTRACT
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn fill_opacity_less_than_one_emitted() {
        // push_fill_stroke: `if s.fill_opacity < 1.0 { push_attr "fill-opacity" }`
        let fill_opacity = 0.3_f64;
        assert!(fill_opacity < 1.0, "fill_opacity < 1.0 triggers attribute emission");
    }

    #[test]
    fn stroke_opacity_less_than_one_emitted() {
        let stroke_opacity = 0.5_f64;
        assert!(stroke_opacity < 1.0, "stroke_opacity < 1.0 triggers attribute emission");
    }

    #[test]
    fn fill_opacity_exactly_one_not_emitted() {
        let fill_opacity = 1.0_f64;
        let emitted = fill_opacity < 1.0;
        assert!(!emitted, "fill_opacity == 1.0 must NOT emit fill-opacity attribute");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  20. ANNOTATION RECT — fill_opacity PROPAGATION
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn annotation_rect_opacity_as_fill_opacity_not_opacity() {
        // In annotation.rs AnnotationSpec::Rect handler, the caller-supplied
        // opacity is stored in fill_opacity, not opacity.
        // opacity is set to 1.0 (not forwarded to SVG).
        // This is critical: to_svg_fill_stroke_with_anchor emits fill_opacity
        // but ignores the opacity field for SVG attributes.
        let caller_opacity = 0.3_f64;
        // Post-fix:
        let fs_opacity = 1.0_f64;
        let fs_fill_opacity = caller_opacity;
        assert!((fs_opacity - 1.0).abs() < f64::EPSILON);
        assert!((fs_fill_opacity - 0.3).abs() < f64::EPSILON);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  21. INSET VIEWBOX USED IN NESTED SVG
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn inset_svg_includes_viewbox_in_nested_element() {
        // The build_inset_nodes function creates a nested <svg> with viewBox.
        // Format: <svg x="..." y="..." width="..." height="..." viewBox="..." overflow="hidden">
        let viewbox = extract_viewbox(
            r#"<svg width="200" height="150" viewBox="0 0 200 150"><circle/></svg>"#
        );
        let nested = format!(
            "<svg x=\"100.000\" y=\"50.000\" width=\"200.000\" height=\"150.000\" viewBox=\"{}\" overflow=\"hidden\">content</svg>",
            viewbox
        );
        assert!(nested.contains("viewBox=\"0 0 200 150\""),
            "nested SVG must contain the extracted viewBox");
        assert!(nested.contains("overflow=\"hidden\""),
            "nested SVG must have overflow hidden");
    }

    #[test]
    fn inset_svg_no_viewbox_uses_default() {
        // When the input SVG has no viewBox, the default "0 0 640 480" is used.
        let viewbox = extract_viewbox(
            r#"<svg width="200" height="150"><circle/></svg>"#
        );
        assert_eq!(viewbox, "0 0 640 480",
            "missing viewBox must use default 640x480");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  22. BREAK_HIDDEN CONSTANT
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn break_hidden_is_far_offscreen() {
        // BREAK_HIDDEN = -99999.0 — used to hide marks in gaps.
        // Must be far enough offscreen that no visible viewport includes it.
        let break_hidden = -99999.0_f64;
        assert!(break_hidden < -1000.0,
            "BREAK_HIDDEN must be far offscreen to avoid visible artifacts");
        // It must also not be NaN (which would poison subsequent SVG rendering).
        assert!(break_hidden.is_finite(), "BREAK_HIDDEN must be finite, not NaN");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  23. ANNOTATION ARROW — NaN COORDINATES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn arrow_nan_start_skips_arrowhead() {
        // If x1 or y1 is NaN, dx = x2 - NaN = NaN, len = NaN.sqrt() = NaN.
        // len > 0.0 is false for NaN, so arrowhead is NOT drawn.
        let x1 = f64::NAN;
        let x2 = 200.0_f64;
        let dx = x2 - x1;
        let dy = 0.0_f64;
        let len = (dx * dx + dy * dy).sqrt();
        assert!(!(len > 0.0), "NaN len skips arrowhead branch");
    }

    #[test]
    fn arrow_coincident_endpoints_no_arrowhead() {
        // x1==x2 && y1==y2: len=0, len > 0.0 is false, no arrowhead.
        let len = 0.0_f64;
        assert!(!(len > 0.0), "zero-length arrow skips arrowhead");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  24. CONNECTOR CORNER SORTING WITH NaN COORDS
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn connector_nan_connect_to_sort_uses_equal_fallback() {
        // In inset.rs, connector sorting uses .partial_cmp().unwrap_or(Equal).
        // If connect_to is NaN, all distances are NaN.
        // NaN.partial_cmp(NaN) = None -> Equal. All corners tied.
        let cx = f64::NAN;
        let cy = f64::NAN;
        let corner = (100.0_f64, 200.0_f64);
        let d = (corner.0 - cx).hypot(corner.1 - cy);
        assert!(d.is_nan(), "NaN connect_to produces NaN distance");
        let cmp = d.partial_cmp(&d);
        assert!(cmp.is_none(), "NaN partial_cmp returns None");
        // unwrap_or(Equal) means all corners are considered equal distance.
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  25. LEGEND COLOR CONFIG APPLICATION
    // ═══════════════════════════════════════════════════════════════════════

    // In scene_build.rs::build_legend_decorations, chart_config.color is applied
    // to the legend's color_scale via apply_color_config_to_color_scale.
    // This must happen AFTER scale resolution for both panels AND legend.

    #[test]
    fn legend_color_config_applied_after_resolution() {
        // Contract pin: the legend gets chart_config.color applied.
        // Previously it was only applied to panel color scales, not the legend.
        let config_has_color = true;
        let legend_gets_color_config = true;
        assert!(config_has_color && legend_gets_color_config,
            "legend must receive chart_config.color override after scale resolution");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  26. ANNOTATION IMAGE XML INJECTION
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn annotation_image_src_prevents_xss() {
        let src = r#"evil.png" onload="alert(1)"#;
        let escaped = escape_attr(src);
        let _svg_fragment = format!(r#"<image href="{}"/>"#, escaped);
        // The XSS is neutralized: double quotes are escaped so the browser
        // cannot break out of the href attribute. The literal text "onload="
        // still appears but is inside the attribute value, not as a separate
        // attribute. Verify the quotes are escaped.
        assert!(escaped.contains("&quot;"),
            "double quotes in src must be escaped to &quot;");
        // Verify the escaped string has no raw double quotes that could break
        // out of the attribute.
        assert!(!escaped.contains('"'),
            "escaped src must not contain raw double quotes");
    }

    #[test]
    fn annotation_image_src_ampersand_in_url() {
        let src = "https://example.com/img?a=1&b=2";
        let escaped = escape_attr(src);
        assert!(escaped.contains("&amp;"),
            "ampersand in URL must be escaped to &amp;");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  27. FMT_F PRECISION CONTRACT
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn fmt_f_precision_is_3_digits() {
        // FLOAT_PRECISION = 3, so format!("{:.3}", x) is used.
        assert_eq!(fmt_f(1.2345), "1.234",
            "precision 3 truncates to 3 decimal places (banker's rounding may apply)");
    }

    #[test]
    fn fmt_f_trailing_zeros_trimmed() {
        assert_eq!(fmt_f(1.0), "1");
        assert_eq!(fmt_f(1.5), "1.5");
        assert_eq!(fmt_f(1.50), "1.5");
    }

    #[test]
    fn fmt_f_very_precise_positive() {
        // 0.001 at precision 3: "0.001" — no trimming needed.
        assert_eq!(fmt_f(0.001), "0.001");
    }

    #[test]
    fn fmt_f_value_rounds_to_zero_after_trimming() {
        // 0.0001 at precision 3: format!("{:.3}", 0.0001) = "0.000"
        // Trim trailing zeros: "0." -> trim dot: "0" -> not empty -> return "0".
        // Wait: trim_end_matches('0') on "0.000" produces "0."
        // Then trim_end_matches('.') produces "0".
        // trimmed = "0", which is not empty, not "-", not "-0".
        assert_eq!(fmt_f(0.0001), "0");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  28. SVG TEXT MULTILINE AND TSPAN
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn multiline_text_splits_on_newline() {
        let content = "line1\nline2\nline3";
        let lines: Vec<&str> = content.split('\n').collect();
        assert_eq!(lines.len(), 3);
        assert_eq!(lines[0], "line1");
        assert_eq!(lines[2], "line3");
    }

    #[test]
    fn single_line_text_no_split() {
        let content = "no newlines here";
        assert!(!content.contains('\n'));
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  29. GRIDLINE NODE TYPE DISPATCH
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn gridline_band_rect_falls_through_to_emit_node() {
        // When grid has band_colors, the grid vec contains Rect nodes.
        // emit_gridline_node checks `if let SceneNode::Line { .. } = node`.
        // Rect nodes don't match — they fall through to `emit_node`.
        // This is correct behavior: Rect band fills are emitted as regular nodes.
        let is_line = false;
        let would_call_emit_node = !is_line;
        assert!(would_call_emit_node,
            "grid Rect (band fill) must fall through to emit_node");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  30. CHART_CONFIG INSET CONNECT_TO RESOLVED THROUGH SCALES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn inset_connect_to_data_space_resolved_to_pixels() {
        // In scene_build.rs, connect_to [dx, dy] is resolved through primary
        // scales before passing to build_inset_nodes. If the scale's to_pixel_f64
        // returns None, a linear interpolation fallback is used.
        // Pin the contract: the fallback uses data_domain() fractions.
        let d_lo = 0.0_f64;
        let d_hi = 100.0_f64;
        let plot_x = 50.0_f64;
        let plot_w = 300.0_f64;
        let dx = 50.0_f64; // data-space value
        let frac = (dx - d_lo) / (d_hi - d_lo);
        let px_x = plot_x + frac * plot_w;
        assert!((px_x - 200.0).abs() < 1e-10,
            "data value 50 in [0,100] maps to pixel 200 in [50,350]");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  31. ZOOM TICK LEVELS BREAKPOINTS
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn zoom_breakpoints_cover_full_range() {
        // ZOOM_BREAKPOINTS: [(0.0, 0.5, 4), (0.5, 2.0, 8), (2.0, 4.0, 16), (4.0, 1e9, 32)]
        // min_zoom of first = 0.0, max_zoom of last = 1e9.
        // There should be 4 levels total.
        let breakpoints: &[(f64, f64, usize)] = &[
            (0.0, 0.5, 4),
            (0.5, 2.0, 8),
            (2.0, 4.0, 16),
            (4.0, 1e9, 32),
        ];
        assert_eq!(breakpoints.len(), 4);
        // Verify contiguous coverage: each max_zoom == next min_zoom
        for i in 0..breakpoints.len() - 1 {
            assert!((breakpoints[i].1 - breakpoints[i + 1].0).abs() < 1e-10,
                "zoom breakpoints must be contiguous at index {i}");
        }
        // First starts at 0
        assert_eq!(breakpoints[0].0, 0.0);
        // Last goes to 1e9
        assert_eq!(breakpoints[3].1, 1e9);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  32. ANNOTATION CALLOUT CHAR WIDTH ESTIMATION
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn callout_char_width_uses_char_count_not_byte_count() {
        let text = "\u{00e9}\u{00e9}\u{00e9}"; // 3 chars, 6 bytes (UTF-8)
        let char_width = 7.0_f64;
        let padding = 4.0_f64;
        let text_w = text.chars().count() as f64 * char_width + padding * 2.0;
        assert_eq!(text_w, 3.0 * 7.0 + 8.0, "width uses char count (3), not byte count (6)");
        let byte_based_w = text.len() as f64 * char_width + padding * 2.0;
        assert!(byte_based_w > text_w,
            "byte-based width would be larger — this is the fixed behavior");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  33. SECONDARY AXIS DEGENERATE DOMAIN
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn secondary_y_constant_field_expanded() {
        // When all values in the secondary field are identical,
        // the domain is expanded by +-0.5 to avoid a zero-length scale.
        let mn = 42.0_f64;
        let mx = 42.0_f64;
        let (expanded_mn, expanded_mx) = if mn == mx {
            (mn - 0.5, mx + 0.5)
        } else {
            (mn, mx)
        };
        assert_eq!(expanded_mn, 41.5);
        assert_eq!(expanded_mx, 42.5);
    }

    #[test]
    fn secondary_y_nan_min_max_fallback() {
        // If finite_min_max_f64 returns None (all NaN), fallback is (0.0, 1.0).
        let fallback = (0.0_f64, 1.0_f64);
        assert_eq!(fallback.0, 0.0);
        assert_eq!(fallback.1, 1.0);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  34. ANNOTATION BRACKET UNKNOWN DIRECTION DEFAULTS TO UP
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bracket_unknown_direction_defaults_to_up() {
        let direction = "diagonal";
        let tip_length = 6.0_f64;
        let (tip_dx, tip_dy) = match direction {
            "up" => (0.0, -tip_length),
            "down" => (0.0, tip_length),
            "left" => (-tip_length, 0.0),
            "right" => (tip_length, 0.0),
            _ => (0.0, -tip_length), // default: up
        };
        assert_eq!(tip_dx, 0.0);
        assert_eq!(tip_dy, -6.0, "unknown direction defaults to up (negative Y)");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  35. CHART CONFIG STRUCTURAL SPEC TAG VARIANTS
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn structural_spec_secondary_y_tag() {
        let json = r#"{"type": "secondary_y", "field": "col"}"#;
        let v: serde_json::Value = serde_json::from_str(json).unwrap();
        assert_eq!(v["type"], "secondary_y");
    }

    #[test]
    fn structural_spec_break_axis_tag() {
        let json = r#"{"type": "break_axis", "axis": "y", "gaps": [[10, 50]]}"#;
        let v: serde_json::Value = serde_json::from_str(json).unwrap();
        assert_eq!(v["type"], "break_axis");
    }

    #[test]
    fn structural_spec_inset_tag() {
        let json = r#"{"type": "inset", "svg": "<svg></svg>", "bounds": [0,0,1,1]}"#;
        let v: serde_json::Value = serde_json::from_str(json).unwrap();
        assert_eq!(v["type"], "inset");
    }
}
