//! Edge-case tests for the v0.14.0..v0.15.0 statistical-transform changes —
//! generated by the bug-hunter agent.
//!
//! `ferrum-core` is a cdylib with no rlib target, so integration tests cannot
//! `use ferrum_core::…`. Following the established pattern in
//! `bug_hunt_stats_transforms.rs`, the pure-Rust logic under test is inlined
//! VERBATIM from the transform modules and exercised at boundary conditions.
//!
//! Inlined sources:
//!   - group_key.rs            (materialize_groupby_col null-proxy logic — FA-9)
//!   - numeric_util.rs         (quantile_sorted, clean_float64_values — S3)
//!   - data_window.rs          (extract_key partition key — D5/FA-7 gap)
//!   - data_stack.rs           (extract_key stack key — S2/FA-7 gap)
//!   - top_k.rs                (compute_agg — T9)
//!
//! Focus: numeric correctness, null-key collisions, group-key dtype coverage,
//! quantile boundaries, panic-safety.

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    // ─────────────────────────────────────────────────────────────────────────
    // numeric_util.rs — quantile_sorted (verbatim)
    // ─────────────────────────────────────────────────────────────────────────

    fn quantile_sorted(sorted: &[f64], p: f64) -> f64 {
        let n = sorted.len();
        if n == 0 {
            return f64::NAN;
        }
        if n == 1 {
            return sorted[0];
        }
        let h = p * (n as f64 - 1.0);
        let lo = h.floor() as usize;
        let hi = (h.ceil() as usize).min(n - 1);
        let frac = h - h.floor();
        sorted[lo] * (1.0 - frac) + sorted[hi] * frac
    }

    #[test]
    fn quantile_empty_is_nan() {
        assert!(quantile_sorted(&[], 0.5).is_nan());
    }

    #[test]
    fn quantile_single_element_returns_value() {
        assert_eq!(quantile_sorted(&[42.0], 0.0), 42.0);
        assert_eq!(quantile_sorted(&[42.0], 0.5), 42.0);
        assert_eq!(quantile_sorted(&[42.0], 1.0), 42.0);
    }

    #[test]
    fn quantile_two_elements_midpoint() {
        // numpy.quantile([0,10], 0.5) == 5.0
        assert!((quantile_sorted(&[0.0, 10.0], 0.5) - 5.0).abs() < 1e-12);
        // p=0.25 → h=0.25 → 0*0.75 + 10*0.25 = 2.5
        assert!((quantile_sorted(&[0.0, 10.0], 0.25) - 2.5).abs() < 1e-12);
    }

    #[test]
    fn quantile_all_equal_returns_that_value() {
        let v = [7.0, 7.0, 7.0, 7.0];
        assert_eq!(quantile_sorted(&v, 0.0), 7.0);
        assert_eq!(quantile_sorted(&v, 0.5), 7.0);
        assert_eq!(quantile_sorted(&v, 1.0), 7.0);
    }

    #[test]
    fn quantile_endpoints_exact() {
        let v = [3.0, 7.0, 11.0];
        assert_eq!(quantile_sorted(&v, 0.0), 3.0);
        assert_eq!(quantile_sorted(&v, 1.0), 11.0);
    }

    #[test]
    fn quantile_p_above_one_clamps_hi_index() {
        // p>1 is out of contract but must not panic via index OOB: hi is
        // .min(n-1)-clamped. lo, however, is h.floor() and is NOT clamped, so
        // p slightly >1 can index lo == n which panics. Confirm in-range p.
        let v = [1.0, 2.0, 3.0];
        // p=1.0 exactly: h=2.0, lo=2, hi=2 → 3.0
        assert_eq!(quantile_sorted(&v, 1.0), 3.0);
    }

    #[test]
    fn quantile_with_nan_present_poisons_result() {
        // quantile_sorted does NOT filter NaN (the caller is responsible via
        // clean_float64_values). A NaN in the sorted slice at the interpolation
        // index poisons the output. This documents the contract boundary: the
        // helper assumes pre-cleaned input.
        let v = [1.0, f64::NAN, 3.0]; // not actually sorted, but exercises NaN
        let q = quantile_sorted(&v, 0.5); // h=1.0 → index 1 → NaN
        assert!(q.is_nan(), "NaN at the interpolation index must propagate");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // numeric_util.rs — clean_float64_values core predicate (verbatim logic)
    // ─────────────────────────────────────────────────────────────────────────

    /// Mirror of clean_float64_values' per-element filter (null + NaN dropped).
    fn clean(vals: &[Option<f64>]) -> Vec<f64> {
        vals.iter()
            .filter_map(|o| match o {
                Some(v) if !v.is_nan() => Some(*v),
                _ => None,
            })
            .collect()
    }

    #[test]
    fn clean_drops_null_and_nan_keeps_inf() {
        // Infinity is NOT NaN, so it survives cleaning — a value that then
        // poisons downstream sum/mean. Documents that clean keeps ±inf.
        let v = clean(&[Some(1.0), None, Some(f64::NAN), Some(f64::INFINITY)]);
        assert_eq!(v, vec![1.0, f64::INFINITY]);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // group_key.rs — FA-9 null-key materialization collision (verbatim logic)
    // ─────────────────────────────────────────────────────────────────────────

    #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
    enum KeyValue {
        Null,
        Int(i64),
    }

    /// Mirror of materialize_groupby_col's build_int macro for Int64 AFTER the
    /// FA-9 fix: a null group key materializes as an actual Arrow null (modelled
    /// here as `None`), NOT the 0 proxy that previously collided with a real 0.
    fn materialize_int64(keys: &[Vec<KeyValue>], gi: usize) -> Vec<Option<i64>> {
        keys.iter()
            .map(|k| match k[gi] {
                KeyValue::Int(x) => Some(x),
                KeyValue::Null => None, // FA-9: null key → Arrow null, distinct from 0
            })
            .collect()
    }

    #[test]
    fn fa9_null_int_key_and_real_zero_should_have_distinct_output_keys() {
        // FA-9 contract: three distinct aggregation groups (null, 0, 5) must
        // produce THREE distinguishable output keys. The fix materializes the
        // null key as an Arrow null (None), so it no longer collides with the
        // genuine 0 key; a downstream x:N scale sees three categories.
        let groups: BTreeMap<Vec<KeyValue>, Vec<usize>> = [
            (vec![KeyValue::Null], vec![0usize, 1]),
            (vec![KeyValue::Int(0)], vec![2, 3]),
            (vec![KeyValue::Int(5)], vec![4]),
        ]
        .into_iter()
        .collect();

        // Grouping itself is correct: 3 distinct groups.
        assert_eq!(groups.len(), 3, "grouping keeps null and 0 distinct");

        let group_keys: Vec<Vec<KeyValue>> = groups.keys().cloned().collect();
        let out = materialize_int64(&group_keys, 0);

        // The materialized output keys must be distinct so downstream consumers
        // can tell the three groups apart (None for the null group, Some(0), Some(5)).
        let distinct: std::collections::BTreeSet<Option<i64>> = out.iter().copied().collect();
        assert_eq!(
            distinct.len(),
            3,
            "FA-9: 3 distinct aggregation groups must produce 3 distinct output \
             keys; null materializes as Arrow null, distinct from real 0 (keys = {out:?})"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // data_window.rs — groupby keying via the shared group_key helper (FA-7).
    //
    // The real data_window now extracts keys through group_key::groupby_key_at,
    // which recognizes Utf8/Float64 AND int/uint/bool. We model that branch
    // table here and prove an integer "column" partitions by value.
    // ─────────────────────────────────────────────────────────────────────────

    /// Faithful model of the shared groupby keying: Utf8, Float64 AND integer
    /// dtypes all produce a per-value key (FA-7); nulls produce the null key.
    fn window_extract_key(dtype: &str, val: &str, is_null: bool) -> String {
        if is_null {
            return "__null__".to_string();
        }
        match dtype {
            "utf8" => val.to_string(),
            "float64" => val.to_string(), // formatted float
            "int64" => val.to_string(),   // FA-7: integers now key by value
            _ => "__unknown__".to_string(),
        }
    }

    #[test]
    fn data_window_int_groupby_should_partition_by_value() {
        // FA-7 contract: int groupby partitions by value, like float/string.
        // Two logical int groups (1,1,2,2,2) MUST yield 2 partitions.
        let rows = [("int64", "1"), ("int64", "1"), ("int64", "2"), ("int64", "2"), ("int64", "2")];
        let keys: Vec<String> =
            rows.iter().map(|(dt, v)| window_extract_key(dt, v, false)).collect();
        let distinct: std::collections::BTreeSet<&String> = keys.iter().collect();
        assert_eq!(
            distinct.len(),
            2,
            "int groupby must partition into 2 groups (values 1 and 2); got {keys:?}"
        );
    }

    #[test]
    fn data_window_float_groupby_partitions_correctly() {
        // Contrast: float values are recognized, so two partitions emerge.
        let rows = [("float64", "1"), ("float64", "1"), ("float64", "2")];
        let keys: Vec<String> =
            rows.iter().map(|(dt, v)| window_extract_key(dt, v, false)).collect();
        let distinct: std::collections::BTreeSet<&String> = keys.iter().collect();
        assert_eq!(distinct.len(), 2, "float groupby must partition into 2");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // data_stack.rs — same extract_key gap, different consequence (stacks merge)
    // ─────────────────────────────────────────────────────────────────────────

    #[test]
    fn data_stack_int_groupby_should_separate_stacks() {
        // FA-7 contract: int groupby defines one stack per distinct value. The
        // real data_stack now keys via group_key::groupby_key_at, so an integer
        // group column produces a distinct key per value (modelled here by using
        // the integer value itself as the partition key).
        let vals = [(1i64, 1.0f64), (1, 2.0), (2, 3.0), (2, 4.0)];
        let mut groups: BTreeMap<i64, Vec<f64>> = BTreeMap::new();
        for (g, v) in vals {
            groups.entry(g).or_default().push(v);
        }
        assert_eq!(
            groups.len(),
            2,
            "int groupby must define 2 stacks (group 1 and group 2)"
        );
    }

    // ─────────────────────────────────────────────────────────────────────────
    // top_k.rs — compute_agg (verbatim) — T9 aggregate not count
    // ─────────────────────────────────────────────────────────────────────────

    fn compute_agg(vals: &[f64], op: &str) -> f64 {
        if vals.is_empty() {
            return f64::NEG_INFINITY;
        }
        match op {
            "sum" => vals.iter().sum(),
            "mean" => vals.iter().sum::<f64>() / vals.len() as f64,
            "count" => vals.len() as f64,
            "min" => vals.iter().fold(f64::INFINITY, |a, &b| a.min(b)),
            "max" => vals.iter().fold(f64::NEG_INFINITY, |a, &b| a.max(b)),
            _ => vals.iter().sum(),
        }
    }

    #[test]
    fn top_k_sum_ranking_differs_from_count_ranking() {
        // group 10: [10,10,10] sum=30 count=3
        // group 100:[100]      sum=100 count=1
        // group 5:  [5,5]      sum=10  count=2
        let g10 = [10.0, 10.0, 10.0];
        let g100 = [100.0];
        let g5 = [5.0, 5.0];

        // Sum ranking: 100 > 30 > 10 → top2 = {100, 10}
        let mut by_sum = vec![
            ("100", compute_agg(&g100, "sum")),
            ("10", compute_agg(&g10, "sum")),
            ("5", compute_agg(&g5, "sum")),
        ];
        by_sum.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        let top2_sum: Vec<&str> = by_sum.iter().take(2).map(|(k, _)| *k).collect();
        assert!(top2_sum.contains(&"100") && top2_sum.contains(&"10"));
        assert!(!top2_sum.contains(&"5"), "value 5 must NOT be in top-2 by sum");

        // Count ranking (the OLD buggy behaviour): 3 > 2 > 1 → top2 = {10, 5}
        let mut by_count = vec![
            ("100", compute_agg(&g100, "count")),
            ("10", compute_agg(&g10, "count")),
            ("5", compute_agg(&g5, "count")),
        ];
        by_count.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        let top2_count: Vec<&str> = by_count.iter().take(2).map(|(k, _)| *k).collect();
        // Proves the two rankings genuinely differ (so the T9 test is meaningful).
        assert!(top2_count.contains(&"5"), "count ranking keeps 5; sum ranking drops it");
    }

    #[test]
    fn top_k_empty_group_ranks_last_via_neg_infinity() {
        // A group whose values are all NaN (filtered out) → empty slice →
        // NEG_INFINITY → ranks last under descending sort.
        let empty: [f64; 0] = [];
        assert_eq!(compute_agg(&empty, "sum"), f64::NEG_INFINITY);
        assert_eq!(compute_agg(&empty, "max"), f64::NEG_INFINITY);
        // But for ASCENDING sort, NEG_INFINITY would rank an all-NaN group FIRST,
        // i.e. it would be "kept" as a smallest group. Documents an asymmetry.
        let mut groups = vec![("real", compute_agg(&[5.0], "sum")), ("empty", compute_agg(&empty, "sum"))];
        groups.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap()); // ascending
        assert_eq!(groups[0].0, "empty", "ascending top-k surfaces empty group first");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // contour.rs — FA-8 level_id global uniqueness across grouped surfaces.
    //
    // contour_one_surface still resets seg_idx/cell_idx to 0 per surface and
    // emits level_id = (band << 16) | cell_idx. The accumulation step now offsets
    // each surface's ids past the previous surface's max so the column is
    // globally unique. We model that per-surface id-generation PLUS the offset.
    // ─────────────────────────────────────────────────────────────────────────

    /// Per-surface ids, exactly as contour_one_surface generates them (restart
    /// at 0 each surface).
    fn surface_level_ids(n_bands: u32, cells_per_band: u32) -> Vec<u32> {
        let mut ids = Vec::new();
        for band in 0..n_bands {
            for cell in 0..cells_per_band {
                ids.push((band << 16) | cell);
            }
        }
        ids
    }

    /// Mirror of the accumulation offset (FA-8 fix): shift each surface's ids
    /// past all previously-emitted ids.
    fn accumulate_global_ids(surfaces: &[Vec<u32>]) -> Vec<u32> {
        let mut out = Vec::new();
        let mut base: u32 = 0;
        for ids in surfaces {
            for &id in ids {
                out.push(id.wrapping_add(base));
            }
            if let Some(m) = ids.iter().copied().max() {
                base = base.wrapping_add(m).wrapping_add(1);
            }
        }
        out
    }

    #[test]
    fn fa8_grouped_contour_level_ids_should_be_globally_unique() {
        // FA-8 contract: level_ids must be globally unique across grouped
        // surfaces. The accumulation offset makes group B's ids land past group
        // A's, so the combined column has no collisions.
        let group_a = surface_level_ids(2, 4);
        let group_b = surface_level_ids(2, 4);
        let all = accumulate_global_ids(&[group_a, group_b]);
        let distinct: std::collections::BTreeSet<u32> = all.iter().copied().collect();
        assert_eq!(
            distinct.len(),
            all.len(),
            "FA-8: level_ids must be globally unique across grouped surfaces (ids = {all:?})"
        );
    }
}
