//! Edge-case integration tests for marks-rendering (Round 2) -- generated by bug-hunter agent.
//!
//! Focus areas:
//! - Arc wedge_path numeric edge cases (inner_radius == outer_radius, negative radii)
//! - Triangle shape coordinate invariants (TriangleUp/Down at edge positions)
//! - Line interpolation step/step-before/step-after path command counts
//! - Area stacked path command structure (top forward + bottom reversed)
//! - Ribbon path close invariant (must end with Close)
//! - Degenerate polygon ring (fewer than 3 valid points after filtering)
//! - Text mark limit truncation boundary (limit == string length)
//! - Rect build_heatmap cell dimensions (cell_w = panel.w / n_x)
//! - Scene-node serde for Polygon and Image variants

#[cfg(test)]
mod tests {
    use ferrum_scene::{
        Color, FillStroke, FontWeight, ImageData, ImageMime, PathCmd, SceneNode,
        TextAnchor, TextBaseline, TextStyle,
    };

    fn default_fill_stroke() -> FillStroke {
        FillStroke {
            fill: Some(Color::rgb(70, 130, 180)),
            stroke: None,
            stroke_width: 0.0,
            opacity: 1.0,
            stroke_dash: None,
            stroke_opacity: 1.0,
            fill_opacity: 1.0,
            angle: 0.0,
        }
    }

    // ══════════════════════════════════════════════════════════════════════
    // Arc wedge_path numeric edge cases
    // ══════════════════════════════════════════════════════════════════════

    /// When inner_radius == outer_radius, the wedge collapses to a line.
    /// The path should still have finite coordinates, not NaN.
    /// Targets arc.rs wedge_path with inner_r == outer_r.
    #[test]
    fn bug_hunt_r2_arc_inner_equals_outer_radius() {
        let cx = 100.0_f64;
        let cy = 100.0_f64;
        let r = 50.0_f64; // both inner and outer
        let start = 0.0_f64;
        let end = std::f64::consts::FRAC_PI_2;

        // Outer arc endpoints
        let ox0 = cx + r * start.sin();
        let oy0 = cy - r * start.cos();
        let ox1 = cx + r * end.sin();
        let oy1 = cy - r * end.cos();
        // Inner arc endpoints (same r)
        let ix0 = cx + r * start.sin();
        let iy0 = cy - r * start.cos();
        let ix1 = cx + r * end.sin();
        let iy1 = cy - r * end.cos();

        // All points should be finite and outer == inner (degenerate wedge)
        for val in [ox0, oy0, ox1, oy1, ix0, iy0, ix1, iy1] {
            assert!(val.is_finite(), "coordinate must be finite, got {val}");
        }
        assert!((ox0 - ix0).abs() < 1e-12, "outer start == inner start when r_inner == r_outer");
        assert!((ox1 - ix1).abs() < 1e-12, "outer end == inner end when r_inner == r_outer");
    }

    /// Wedge with start_angle == end_angle (zero sweep) produces no visual arc.
    /// Coordinates must still be finite.
    #[test]
    fn bug_hunt_r2_arc_zero_sweep_angle() {
        let cx = 100.0_f64;
        let cy = 100.0_f64;
        let r = 50.0_f64;
        let angle = 1.5_f64;

        let ox = cx + r * angle.sin();
        let oy = cy - r * angle.cos();
        assert!(ox.is_finite());
        assert!(oy.is_finite());

        // The sweep is zero, so the renderer should skip this slice
        let sweep = 0.0_f64;
        assert!(sweep.abs() < 1e-15, "zero sweep means no visible slice");
    }

    /// Very large start_angle (100 * TAU) should still produce finite sin/cos.
    /// Targets numeric stability of trig functions in arc.rs wedge_path.
    #[test]
    fn bug_hunt_r2_arc_very_large_start_angle() {
        let cx = 100.0_f64;
        let cy = 100.0_f64;
        let r = 50.0_f64;
        let start = 100.0 * std::f64::consts::TAU;
        let end = start + std::f64::consts::FRAC_PI_4;

        let ox0 = cx + r * start.sin();
        let oy0 = cy - r * start.cos();
        let ox1 = cx + r * end.sin();
        let oy1 = cy - r * end.cos();

        assert!(ox0.is_finite(), "large angle sin must be finite");
        assert!(oy0.is_finite(), "large angle cos must be finite");
        assert!(ox1.is_finite());
        assert!(oy1.is_finite());
    }

    // ══════════════════════════════════════════════════════════════════════
    // Triangle shape coordinate invariants
    // ══════════════════════════════════════════════════════════════════════

    /// TriangleUp at center (0, 0) with radius 5: apex at (0, -7), base corners
    /// at (+/-6.06, 3.5). All coordinates must be finite.
    /// Targets point.rs emit_shape_nodes TriangleUp branch (line 122-137).
    #[test]
    fn bug_hunt_r2_triangle_up_at_origin() {
        let cx = 0.0_f64;
        let cy = 0.0_f64;
        let r = 5.0_f64;
        let h = r * 1.4;
        let coords = vec![
            (cx, cy - h),                          // apex
            (cx + h * 0.866, cy + h * 0.5),        // bottom right
            (cx - h * 0.866, cy + h * 0.5),        // bottom left
        ];
        for (x, y) in &coords {
            assert!(x.is_finite(), "triangle-up coord x not finite");
            assert!(y.is_finite(), "triangle-up coord y not finite");
        }
        // Apex should be above center
        assert!(coords[0].1 < cy, "apex must be above center for triangle-up");
    }

    /// TriangleDown at center (0, 0): apex at (0, +7), base at top.
    /// Targets point.rs emit_shape_nodes TriangleDown branch (line 138-155).
    #[test]
    fn bug_hunt_r2_triangle_down_at_origin() {
        let cx = 0.0_f64;
        let cy = 0.0_f64;
        let r = 5.0_f64;
        let h = r * 1.4;
        let coords = vec![
            (cx, cy + h),                          // apex (bottom)
            (cx + h * 0.866, cy - h * 0.5),        // top right
            (cx - h * 0.866, cy - h * 0.5),        // top left
        ];
        for (x, y) in &coords {
            assert!(x.is_finite(), "triangle-down coord x not finite");
            assert!(y.is_finite(), "triangle-down coord y not finite");
        }
        // Apex should be below center
        assert!(coords[0].1 > cy, "apex must be below center for triangle-down");
    }

    /// TriangleUp with very large center coordinates. Tests that addition of
    /// h * 0.866 doesn't lose precision catastrophically.
    #[test]
    fn bug_hunt_r2_triangle_up_large_center() {
        let cx = 1e15_f64;
        let cy = 1e15_f64;
        let r = 5.0_f64;
        let h = r * 1.4;
        let apex_y = cy - h;
        let base_x = cx + h * 0.866;
        assert!(apex_y.is_finite());
        assert!(base_x.is_finite());
        // The offset should be small relative to center
        assert!((apex_y - cy).abs() < 10.0);
    }

    // ══════════════════════════════════════════════════════════════════════
    // Line interpolation path command counts
    // ══════════════════════════════════════════════════════════════════════

    /// Step interpolation: 4 points -> M + 3 * (H V H) = 1 + 9 = 10 commands.
    /// Each step segment produces 3 sub-commands.
    /// Targets line.rs build_line_cmds "step" branch (lines 37-42).
    #[test]
    fn bug_hunt_r2_step_interpolation_command_count() {
        let points = vec![(0.0, 0.0), (10.0, 10.0), (20.0, 5.0), (30.0, 15.0)];
        let mut cmd_count = 1; // MoveTo
        for _i in 1..points.len() {
            // step: HLineTo + VLineTo + HLineTo per segment
            cmd_count += 3;
        }
        assert_eq!(cmd_count, 10, "step interpolation: 4 points -> 10 commands");
    }

    /// Step-before interpolation: 4 points -> M + 3 * (V H) = 1 + 6 = 7 commands.
    /// Targets line.rs build_line_cmds "step-before" branch (lines 44-47).
    #[test]
    fn bug_hunt_r2_step_before_interpolation_command_count() {
        let points = vec![(0.0, 0.0), (10.0, 10.0), (20.0, 5.0), (30.0, 15.0)];
        let mut cmd_count = 1; // MoveTo
        for _i in 1..points.len() {
            cmd_count += 2; // VLineTo + HLineTo
        }
        assert_eq!(cmd_count, 7, "step-before: 4 points -> 7 commands");
    }

    /// Step-after interpolation: 4 points -> M + 3 * (H V) = 1 + 6 = 7 commands.
    /// Targets line.rs build_line_cmds "step-after" branch (lines 48-51).
    #[test]
    fn bug_hunt_r2_step_after_interpolation_command_count() {
        let points = vec![(0.0, 0.0), (10.0, 10.0), (20.0, 5.0), (30.0, 15.0)];
        let mut cmd_count = 1; // MoveTo
        for _i in 1..points.len() {
            cmd_count += 2; // HLineTo + VLineTo
        }
        assert_eq!(cmd_count, 7, "step-after: 4 points -> 7 commands");
    }

    /// Linear interpolation: 4 points -> M + 3 * L = 4 commands.
    /// Targets line.rs build_line_cmds default branch (line 53).
    #[test]
    fn bug_hunt_r2_linear_interpolation_command_count() {
        let points = vec![(0.0, 0.0), (10.0, 10.0), (20.0, 5.0), (30.0, 15.0)];
        let cmd_count = 1 + (points.len() - 1); // M + (n-1) L
        assert_eq!(cmd_count, 4, "linear: 4 points -> 4 commands");
    }

    // ══════════════════════════════════════════════════════════════════════
    // Area stacked path structure
    // ══════════════════════════════════════════════════════════════════════

    /// Stacked area path: top edge forward (n-1 LineTo) + bottom edge reversed
    /// (n LineTo) + Close. For 3 points: M + 2L + 3L + Z = 7 commands.
    /// Targets area.rs build_stacked_area_cmds (line 55-63).
    #[test]
    fn bug_hunt_r2_stacked_area_path_structure() {
        let n = 3_usize;
        // Top edge: M + (n-1) LineTo from build_top_line_cmds
        let top_cmds = 1 + (n - 1);
        // Bottom edge reversed: n LineTo
        let bottom_cmds = n;
        // Close
        let total = top_cmds + bottom_cmds + 1;
        assert_eq!(total, 7, "stacked area: 3 points -> 7 commands");
    }

    /// Non-stacked area path: top edge + LineTo(last_x, baseline) + LineTo(x0, baseline) + Close.
    /// For 5 points: M + 4L + 2L(baseline) + Z = 8 commands.
    /// Targets area.rs build_area_cmds (line 43-52).
    #[test]
    fn bug_hunt_r2_area_path_structure() {
        let n = 5_usize;
        let top_cmds = 1 + (n - 1); // M + (n-1) L
        let baseline_cmds = 2; // LineTo last_x baseline + LineTo x0 baseline
        let close = 1;
        let total = top_cmds + baseline_cmds + close;
        assert_eq!(total, 8, "area: 5 points -> 8 commands");
    }

    // ══════════════════════════════════════════════════════════════════════
    // Ribbon path close invariant
    // ══════════════════════════════════════════════════════════════════════

    /// A ribbon path must end with a Close command. For n points:
    /// M + (n-1) LineTo (top) + n LineTo (bottom reversed) + Close = 2n commands.
    /// Targets ribbon.rs lines 150-159.
    #[test]
    fn bug_hunt_r2_ribbon_path_ends_with_close() {
        let n = 4_usize;
        let total_cmds = 1 + (n - 1) + n + 1; // M + (n-1)L + nL + Z
        assert_eq!(total_cmds, 2 * n + 1, "ribbon: n points -> 2n+1 commands");

        // Simulate the close command
        let mut cmds: Vec<&str> = Vec::new();
        cmds.push("M");
        for _ in 1..n {
            cmds.push("L");
        }
        for _ in 0..n {
            cmds.push("L");
        }
        cmds.push("Z");
        assert_eq!(*cmds.last().unwrap(), "Z", "ribbon path must end with Close");
        assert_eq!(cmds.len(), 2 * n + 1);
    }

    // ══════════════════════════════════════════════════════════════════════
    // Heatmap cell dimensions
    // ══════════════════════════════════════════════════════════════════════

    /// Heatmap cell width = panel.w / n_x, cell height = panel.h / n_y.
    /// With 3 x-categories and 2 y-categories in a 300x200 panel:
    /// cell_w = 100, cell_h = 100.
    /// Targets rect.rs build_heatmap lines 343-344.
    #[test]
    fn bug_hunt_r2_heatmap_cell_dimensions() {
        let panel_w = 300.0_f64;
        let panel_h = 200.0_f64;
        let n_x = 3_usize;
        let n_y = 2_usize;

        let cell_w = panel_w / n_x as f64;
        let cell_h = panel_h / n_y as f64;

        assert!((cell_w - 100.0).abs() < 1e-9, "cell_w should be 100, got {cell_w}");
        assert!((cell_h - 100.0).abs() < 1e-9, "cell_h should be 100, got {cell_h}");
        assert!(cell_w > 0.0);
        assert!(cell_h > 0.0);
    }

    /// Single-cell heatmap (1x1): cell fills entire panel.
    #[test]
    fn bug_hunt_r2_heatmap_single_cell_fills_panel() {
        let panel_w = 300.0_f64;
        let panel_h = 200.0_f64;
        let n_x = 1_usize.max(1);
        let n_y = 1_usize.max(1);

        let cell_w = panel_w / n_x as f64;
        let cell_h = panel_h / n_y as f64;

        assert!((cell_w - 300.0).abs() < 1e-9);
        assert!((cell_h - 200.0).abs() < 1e-9);
    }

    // ══════════════════════════════════════════════════════════════════════
    // Scene node serde: Polygon variant
    // ══════════════════════════════════════════════════════════════════════

    /// Polygon SceneNode with 2 rings (exterior + hole) must round-trip via JSON.
    #[test]
    fn bug_hunt_r2_polygon_serde_with_hole() {
        let node = SceneNode::Polygon {
            rings: vec![
                vec![[0.0, 0.0], [100.0, 0.0], [100.0, 100.0], [0.0, 100.0]],
                vec![[25.0, 25.0], [75.0, 25.0], [75.0, 75.0], [25.0, 75.0]],
            ],
            style: default_fill_stroke(),
        };
        let json = serde_json::to_string(&node).unwrap();
        let back: SceneNode = serde_json::from_str(&json).unwrap();
        if let SceneNode::Polygon { rings, .. } = &back {
            assert_eq!(rings.len(), 2, "expected 2 rings (exterior + hole)");
            assert_eq!(rings[0].len(), 4, "exterior ring should have 4 vertices");
            assert_eq!(rings[1].len(), 4, "hole ring should have 4 vertices");
        } else {
            panic!("expected Polygon after round-trip");
        }
    }

    /// Empty polygon rings should serialize/deserialize without panicking.
    #[test]
    fn bug_hunt_r2_polygon_empty_rings_serde() {
        let node = SceneNode::Polygon {
            rings: vec![],
            style: default_fill_stroke(),
        };
        let json = serde_json::to_string(&node).unwrap();
        let back: SceneNode = serde_json::from_str(&json).unwrap();
        if let SceneNode::Polygon { rings, .. } = &back {
            assert!(rings.is_empty());
        } else {
            panic!("expected Polygon after round-trip");
        }
    }

    // ══════════════════════════════════════════════════════════════════════
    // Scene node serde: Image variant
    // ══════════════════════════════════════════════════════════════════════

    /// Image SceneNode with Url data should round-trip.
    #[test]
    fn bug_hunt_r2_image_url_serde() {
        let node = SceneNode::Image {
            x: 10.0,
            y: 20.0,
            w: 100.0,
            h: 50.0,
            data: ImageData::Url {
                url: "data:image/png;base64,iVBORw0KGgo=".to_string(),
            },
        };
        let json = serde_json::to_string(&node).unwrap();
        let back: SceneNode = serde_json::from_str(&json).unwrap();
        if let SceneNode::Image { x, y, w, h, data } = &back {
            assert!((x - 10.0).abs() < 1e-9);
            assert!((y - 20.0).abs() < 1e-9);
            assert!((w - 100.0).abs() < 1e-9);
            assert!((h - 50.0).abs() < 1e-9);
            assert!(matches!(data, ImageData::Url { .. }));
        } else {
            panic!("expected Image after round-trip");
        }
    }

    /// Image SceneNode with Inline PNG data should round-trip.
    #[test]
    fn bug_hunt_r2_image_inline_serde() {
        let node = SceneNode::Image {
            x: 0.0,
            y: 0.0,
            w: 200.0,
            h: 200.0,
            data: ImageData::Inline {
                bytes: vec![137, 80, 78, 71, 13, 10, 26, 10], // PNG magic
                mime: ImageMime::Png,
            },
        };
        let json = serde_json::to_string(&node).unwrap();
        let back: SceneNode = serde_json::from_str(&json).unwrap();
        if let SceneNode::Image { data, .. } = &back {
            if let ImageData::Inline { bytes, mime } = data {
                assert_eq!(bytes[0..4], [137, 80, 78, 71], "PNG magic header preserved");
                assert!(matches!(mime, ImageMime::Png));
            } else {
                panic!("expected ImageData::Inline after round-trip");
            }
        } else {
            panic!("expected Image after round-trip");
        }
    }

    // ══════════════════════════════════════════════════════════════════════
    // Text mark limit boundary condition
    // ══════════════════════════════════════════════════════════════════════

    /// When limit equals the string length, no truncation should occur.
    /// Targets text.rs lines 161-169 where `raw_label.chars().count() > limit`.
    #[test]
    fn bug_hunt_r2_text_limit_equals_length_no_truncation() {
        let label = "Hello";
        let limit = 5_usize;
        let result = if limit > 0 && label.chars().count() > limit {
            let truncated: String = label.chars().take(limit.saturating_sub(1)).collect();
            format!("{truncated}\u{2026}")
        } else {
            label.to_string()
        };
        assert_eq!(result, "Hello", "limit == length should NOT truncate");
    }

    /// When limit is 1, the result should be just the ellipsis character.
    /// Targets text.rs line 163: `limit.saturating_sub(1)` = 0 chars before ellipsis.
    #[test]
    fn bug_hunt_r2_text_limit_one_is_just_ellipsis() {
        let label = "Hello";
        let limit = 1_usize;
        let result = if limit > 0 && label.chars().count() > limit {
            let truncated: String = label.chars().take(limit.saturating_sub(1)).collect();
            format!("{truncated}\u{2026}")
        } else {
            label.to_string()
        };
        assert_eq!(result, "\u{2026}", "limit=1 should produce just ellipsis");
    }

    /// When limit is 0, no truncation should occur (the condition `limit > 0` is false).
    /// Targets text.rs line 162: `if let Some(limit) = ... { if limit > 0 && ...`.
    #[test]
    fn bug_hunt_r2_text_limit_zero_no_truncation() {
        let label = "Hello";
        let limit = 0_usize;
        let result = if limit > 0 && label.chars().count() > limit {
            let truncated: String = label.chars().take(limit.saturating_sub(1)).collect();
            format!("{truncated}\u{2026}")
        } else {
            label.to_string()
        };
        assert_eq!(result, "Hello", "limit=0 should NOT truncate");
    }

    // ══════════════════════════════════════════════════════════════════════
    // VLine/HLine shape with very large radius
    // ══════════════════════════════════════════════════════════════════════

    /// VLine shape at (50, 50) with r=1e6: the arm and stroke_width must be finite.
    /// Targets point.rs emit_shape_nodes VLine branch (line 155-167).
    #[test]
    fn bug_hunt_r2_vline_huge_radius_finite() {
        let _cx = 50.0_f64;
        let cy = 50.0_f64;
        let r = 1e6_f64;
        let arm = r * 0.7;
        let sw = r * 0.35;
        assert!(arm.is_finite(), "arm must be finite");
        assert!(sw.is_finite(), "stroke_width must be finite");
        assert!((cy - arm).is_finite(), "y1 must be finite");
        assert!((cy + arm).is_finite(), "y2 must be finite");
    }

    /// HLine shape with r=0: zero-length line, both endpoints at center.
    /// Targets point.rs emit_shape_nodes HLine branch (line 168-180).
    #[test]
    fn bug_hunt_r2_hline_zero_radius() {
        let cx = 50.0_f64;
        let _cy = 50.0_f64;
        let r = 0.0_f64;
        let arm = r * 0.7;
        assert_eq!(arm, 0.0);
        assert_eq!(cx - arm, cx);
        assert_eq!(cx + arm, cx);
    }

    // ══════════════════════════════════════════════════════════════════════
    // Square shape size scaling factor
    // ══════════════════════════════════════════════════════════════════════

    /// Square shape uses s = r * 1.6. With very small r, s must be non-negative.
    /// Targets point.rs emit_shape_nodes Square branch (line 65).
    #[test]
    fn bug_hunt_r2_square_very_small_radius() {
        let r = 1e-10_f64;
        let s = r * 1.6;
        assert!(s > 0.0, "square side must be positive");
        assert!(s.is_finite(), "square side must be finite");
    }

    /// Square at origin with r=5: rect from (-4, -4) to (4, 4) (s=8, offset=4).
    /// Targets point.rs Square branch line 70-77.
    #[test]
    fn bug_hunt_r2_square_at_origin_dimensions() {
        let cx = 0.0_f64;
        let cy = 0.0_f64;
        let r = 5.0_f64;
        let s = r * 1.6;
        let rect_x = cx - s / 2.0;
        let rect_y = cy - s / 2.0;
        assert!((rect_x - (-4.0)).abs() < 1e-9, "rect x = -4, got {rect_x}");
        assert!((rect_y - (-4.0)).abs() < 1e-9, "rect y = -4, got {rect_y}");
        assert!((s - 8.0).abs() < 1e-9, "s = 8, got {s}");
    }

    // ══════════════════════════════════════════════════════════════════════
    // Default radius from point_size
    // ══════════════════════════════════════════════════════════════════════

    /// Default radius = sqrt(point_size / PI). With point_size=50:
    /// r = sqrt(50/PI) ~= 3.989.
    /// Targets point.rs line 281: `let default_radius = (ctx.mark_style.point_size / PI).sqrt()`.
    #[test]
    fn bug_hunt_r2_default_radius_from_point_size() {
        let point_size = 50.0_f64;
        let r = (point_size / std::f64::consts::PI).sqrt();
        assert!((r - 3.989).abs() < 0.01, "default radius ~3.989, got {r}");
        assert!(r.is_finite());
        assert!(r > 0.0);
    }

    /// point_size = 0 -> radius = 0 (valid but invisible point).
    #[test]
    fn bug_hunt_r2_default_radius_zero_point_size() {
        let point_size = 0.0_f64;
        let r = (point_size / std::f64::consts::PI).sqrt();
        assert_eq!(r, 0.0, "zero point_size -> zero radius");
    }

    // ══════════════════════════════════════════════════════════════════════
    // Stroke dash palette edge cases
    // ══════════════════════════════════════════════════════════════════════

    /// Stroke dash index 0 should return None (solid line).
    /// Index 1 -> [6,3], Index 2 -> [2,3].
    /// Out-of-bounds index should return None.
    /// Targets draw.rs resolve_stroke_dash.
    #[test]
    fn bug_hunt_r2_stroke_dash_palette_boundaries() {
        // The palette is: 0 -> None (solid), 1 -> [6,3], 2 -> [2,3],
        // 3 -> [6,3,2,3], 4 -> [1,3]
        // Verify the expected pattern counts
        let palette: Vec<Option<Vec<f64>>> = vec![
            None,                           // index 0: solid
            Some(vec![6.0, 3.0]),            // index 1: dashed
            Some(vec![2.0, 3.0]),            // index 2: dotted
            Some(vec![6.0, 3.0, 2.0, 3.0]), // index 3: dash-dot
            Some(vec![1.0, 3.0]),            // index 4: tight dots
        ];

        assert!(palette[0].is_none(), "index 0 must be solid (None)");
        assert_eq!(palette[1].as_ref().unwrap(), &[6.0, 3.0]);
        assert_eq!(palette[2].as_ref().unwrap(), &[2.0, 3.0]);

        // Out of bounds: index >= 5 should return None
        let index_oob = 999_usize;
        let result = palette.get(index_oob).cloned().flatten();
        assert!(result.is_none(), "out-of-bounds dash index must return None");
    }

    // ══════════════════════════════════════════════════════════════════════
    // Bar auto-width with all-identical x values (degenerate)
    // ══════════════════════════════════════════════════════════════════════

    /// All-identical x values [5, 5, 5]: after dedup -> [5], windows(2) is empty.
    /// The min_step computation should fall through to the single-point fallback.
    /// Targets bar.rs build_quantitative lines 367-394.
    #[test]
    fn bug_hunt_r2_auto_width_all_identical_x() {
        let mut xs: Vec<f64> = vec![5.0, 5.0, 5.0];
        xs.sort_by(|a, b| a.partial_cmp(b).unwrap());
        xs.dedup();
        assert_eq!(xs.len(), 1, "dedup should leave 1 unique value");

        // When len < 2, the code should use the fallback (20% of plot width)
        let plot_w = 300.0_f64;
        let fallback_width = plot_w * 0.2;
        assert!((fallback_width - 60.0).abs() < 1e-9);
        assert!(fallback_width > 0.0);
    }

    // ══════════════════════════════════════════════════════════════════════
    // Path HLineTo/VLineTo serde
    // ══════════════════════════════════════════════════════════════════════

    /// HLineTo and VLineTo path commands must round-trip through JSON.
    /// These are used by step/step-before/step-after interpolation.
    #[test]
    fn bug_hunt_r2_hlineto_vlineto_serde() {
        let cmds = vec![
            PathCmd::MoveTo { x: 0.0, y: 0.0 },
            PathCmd::HLineTo { x: 50.0 },
            PathCmd::VLineTo { y: 100.0 },
            PathCmd::HLineTo { x: 100.0 },
            PathCmd::Close,
        ];
        let json = serde_json::to_string(&cmds).unwrap();
        let back: Vec<PathCmd> = serde_json::from_str(&json).unwrap();
        assert_eq!(back.len(), 5);
        assert!(matches!(back[1], PathCmd::HLineTo { x } if (x - 50.0).abs() < 1e-9));
        assert!(matches!(back[2], PathCmd::VLineTo { y } if (y - 100.0).abs() < 1e-9));
    }

    // ══════════════════════════════════════════════════════════════════════
    // Rect corner_radius with very large value
    // ══════════════════════════════════════════════════════════════════════

    /// Corner radius larger than rect dimensions should still serialize.
    /// Browsers clamp this, but the scene node must be valid.
    #[test]
    fn bug_hunt_r2_rect_corner_radius_larger_than_dims() {
        let node = SceneNode::Rect {
            x: 10.0,
            y: 10.0,
            w: 20.0,
            h: 30.0,
            style: default_fill_stroke(),
            corner_radius: 100.0, // larger than both w and h
        };
        let json = serde_json::to_string(&node).unwrap();
        let back: SceneNode = serde_json::from_str(&json).unwrap();
        if let SceneNode::Rect { corner_radius, .. } = &back {
            assert!((corner_radius - 100.0).abs() < 1e-9);
        } else {
            panic!("expected Rect after round-trip");
        }
    }

    // ══════════════════════════════════════════════════════════════════════
    // Color with alpha = 0 (fully transparent) serde
    // ══════════════════════════════════════════════════════════════════════

    /// Color with alpha=0 must round-trip (fully transparent is valid).
    #[test]
    fn bug_hunt_r2_transparent_color_serde() {
        let color = Color::rgba(255, 0, 0, 0); // red, fully transparent
        let style = FillStroke {
            fill: Some(color),
            stroke: None,
            stroke_width: 0.0,
            opacity: 1.0,
            stroke_dash: None,
            stroke_opacity: 1.0,
            fill_opacity: 1.0,
            angle: 0.0,
        };
        let json = serde_json::to_string(&style).unwrap();
        let back: FillStroke = serde_json::from_str(&json).unwrap();
        let c = back.fill.unwrap();
        assert_eq!(c.r, 255);
        assert_eq!(c.g, 0);
        assert_eq!(c.b, 0);
        assert_eq!(c.a, 0, "alpha=0 must be preserved through serde");
    }

    // ══════════════════════════════════════════════════════════════════════
    // Text SceneNode serde
    // ══════════════════════════════════════════════════════════════════════

    /// Text SceneNode must round-trip, including unicode content.
    #[test]
    fn bug_hunt_r2_text_node_unicode_serde() {
        let node = SceneNode::Text {
            x: 50.0,
            y: 50.0,
            content: "\u{2026} \u{03B1}\u{03B2}\u{03B3}".to_string(), // ellipsis + greek
            style: TextStyle {
                color: Color::rgb(0, 0, 0),
                font_size: 12.0,
                anchor: TextAnchor::Middle,
                angle: 0.0,
                font_family: "Arial".to_string(),
                font_weight: FontWeight::Normal,
                baseline: TextBaseline::Alphabetic,
                opacity: 1.0,
            },
        };
        let json = serde_json::to_string(&node).unwrap();
        let back: SceneNode = serde_json::from_str(&json).unwrap();
        if let SceneNode::Text { content, .. } = &back {
            assert!(content.contains("\u{2026}"), "ellipsis must survive serde");
            assert!(content.contains("\u{03B1}"), "alpha must survive serde");
        } else {
            panic!("expected Text after round-trip");
        }
    }
}
