//! Edge-case integration tests for marks-rendering -- generated by bug-hunter agent.
//!
//! Focus areas (Phase 12):
//! - PowScale/SqrtScale numeric correctness via scene-graph coordinate invariants
//! - Bar auto-width computation edge cases (single point, degenerate domain)
//! - Scene node geometry invariants (no NaN, no negative width/height)
//! - Per-instance style overrides boundary values (opacity, stroke_width)
//! - Serde round-trip for new style fields
//! - BandScale/PointScale positioning correctness

#[cfg(test)]
mod tests {
    use ferrum_scene::{Color, FillStroke, PathCmd, SceneNode, StrokeCap, StrokeJoin, StrokeStyle};

    fn default_fill_stroke() -> FillStroke {
        FillStroke {
            fill: Some(Color::rgb(70, 130, 180)),
            stroke: None,
            stroke_width: 0.0,
            opacity: 1.0,
            stroke_dash: None,
            stroke_opacity: 1.0,
            fill_opacity: 1.0,
            angle: 0.0,
        }
    }

    // ── PowScale numeric correctness (validated at scene-graph level) ────

    #[test]
    fn pow_scale_output_coordinates_finite_for_positive_domain() {
        // Simulate what PowScale(domain=[0, 100], range=[0, 500], exponent=2)
        // would produce for x=50:
        // pow_fwd(50)=2500, pow_fwd(0)=0, pow_fwd(100)=10000
        // t = 2500/10000 = 0.25; pixel = 0 + 0.25*500 = 125.0
        let domain = [0.0_f64, 100.0];
        let range = [0.0_f64, 500.0];
        let exponent = 2.0_f64;
        let x = 50.0_f64;

        let pow_fwd = |v: f64| v.signum() * v.abs().powf(exponent);
        let t = (pow_fwd(x) - pow_fwd(domain[0])) / (pow_fwd(domain[1]) - pow_fwd(domain[0]));
        let pixel = range[0] + t * (range[1] - range[0]);

        assert!(pixel.is_finite(), "pixel must be finite, got {pixel}");
        assert!((pixel - 125.0).abs() < 1e-9, "expected 125.0, got {pixel}");

        // Verify circle at this position would be valid
        let node = SceneNode::Circle {
            cx: pixel,
            cy: 200.0,
            r: 5.0,
            style: default_fill_stroke(),
        };
        if let SceneNode::Circle { cx, cy, r, .. } = &node {
            assert!(cx.is_finite());
            assert!(cy.is_finite());
            assert!(*r > 0.0);
        }
    }

    #[test]
    fn sqrt_scale_output_at_quarter_domain_is_half_range() {
        // SqrtScale(domain=[0, 100], range=[0, 400], exponent=0.5)
        // x=25: pow_fwd(25) = 25^0.5 = 5; pow_fwd(0)=0, pow_fwd(100)=10
        // t = 5/10 = 0.5; pixel = 0 + 0.5*400 = 200.0
        let domain = [0.0_f64, 100.0];
        let range = [0.0_f64, 400.0];
        let exponent = 0.5_f64;
        let x = 25.0_f64;

        let pow_fwd = |v: f64| v.signum() * v.abs().powf(exponent);
        let t = (pow_fwd(x) - pow_fwd(domain[0])) / (pow_fwd(domain[1]) - pow_fwd(domain[0]));
        let pixel = range[0] + t * (range[1] - range[0]);

        assert!((pixel - 200.0).abs() < 1e-9, "expected 200.0, got {pixel}");
    }

    #[test]
    fn pow_scale_domain_boundary_values() {
        // At domain boundaries, output should exactly match range boundaries.
        let domain = [10.0_f64, 1000.0];
        let range = [50.0_f64, 550.0];
        let exponent = 2.0_f64;

        let pow_fwd = |v: f64| v.signum() * v.abs().powf(exponent);

        // x = domain[0] -> t=0 -> range[0]
        let t0 = (pow_fwd(domain[0]) - pow_fwd(domain[0])) / (pow_fwd(domain[1]) - pow_fwd(domain[0]));
        let p0 = range[0] + t0 * (range[1] - range[0]);
        assert!((p0 - 50.0).abs() < 1e-9, "domain[0] -> range[0], got {p0}");

        // x = domain[1] -> t=1 -> range[1]
        let t1 = (pow_fwd(domain[1]) - pow_fwd(domain[0])) / (pow_fwd(domain[1]) - pow_fwd(domain[0]));
        let p1 = range[0] + t1 * (range[1] - range[0]);
        assert!((p1 - 550.0).abs() < 1e-9, "domain[1] -> range[1], got {p1}");
    }

    #[test]
    fn pow_scale_zero_in_domain_does_not_divide_by_zero() {
        // Domain [0, 0] (degenerate) would cause division by zero.
        // The renderer should guard against this.
        let domain = [0.0_f64, 0.0];
        let exponent = 2.0_f64;

        let pow_fwd = |v: f64| v.signum() * v.abs().powf(exponent);
        let denom = pow_fwd(domain[1]) - pow_fwd(domain[0]);

        // denom is 0 -> t would be NaN -> renderer should skip or clamp
        assert_eq!(denom, 0.0, "degenerate domain produces zero denominator");
        let t = if denom == 0.0 { 0.5 } else { 0.0 / denom }; // guard
        assert!(t.is_finite());
    }

    // ── Bar auto-width computation edge cases ────────────────────────────

    #[test]
    fn auto_width_uniform_spacing_produces_consistent_widths() {
        // Simulate auto-width for 4 uniformly-spaced x values [1, 2, 3, 4]
        // in a 300px plot area. Min step = 1.0.
        let xs = vec![1.0_f64, 2.0, 3.0, 4.0];
        let plot_w = 300.0_f64;
        let domain = [1.0_f64, 4.0];
        let range = [0.0_f64, plot_w];

        // Linear scale: pixel(x) = (x - d0)/(d1 - d0) * (r1 - r0) + r0
        let to_pixel = |x: f64| (x - domain[0]) / (domain[1] - domain[0]) * (range[1] - range[0]) + range[0];

        let mut sorted_xs = xs.clone();
        sorted_xs.sort_by(|a, b| a.partial_cmp(b).unwrap());
        sorted_xs.dedup();

        let min_step = sorted_xs.windows(2)
            .map(|w| (w[1] - w[0]).abs())
            .filter(|s| *s > 0.0)
            .fold(f64::INFINITY, f64::min);

        assert!((min_step - 1.0).abs() < 1e-9);

        let p0 = to_pixel(sorted_xs[0]);
        let p1 = to_pixel(sorted_xs[0] + min_step);
        let bar_width = (p1 - p0).abs() * 0.8;

        assert!(bar_width > 0.0, "bar width must be positive");
        assert!(bar_width < plot_w / 3.0, "bar width must be reasonable");
        // All bars should have the same width and finite positions
        for &x in &xs {
            let cx = to_pixel(x);
            let rect_x = cx - bar_width / 2.0;
            assert!(rect_x.is_finite(), "bar rect_x must be finite for x={x}");
            assert!(bar_width.is_finite(), "bar_width must be finite");
            // Bars at domain boundaries may extend past the plot edge (clipped by renderer)
            // but the rect_x must still be finite and the width positive.
        }
    }

    #[test]
    fn auto_width_single_point_uses_fallback() {
        // Single data point -> fallback width = 20% of plot width
        let plot_w = 200.0_f64;
        let fallback_width = plot_w * 0.2;
        assert!((fallback_width - 40.0).abs() < 1e-9);
        assert!(fallback_width > 0.0);
    }

    #[test]
    fn auto_width_duplicate_x_values_deduped_correctly() {
        // Duplicates [1, 1, 2, 3]: after dedup -> [1, 2, 3], min_step = 1
        let mut xs = vec![1.0_f64, 1.0, 2.0, 3.0];
        xs.sort_by(|a, b| a.partial_cmp(b).unwrap());
        xs.dedup();
        assert_eq!(xs, vec![1.0, 2.0, 3.0]);
        let min_step = xs.windows(2)
            .map(|w| (w[1] - w[0]).abs())
            .filter(|s| *s > 0.0)
            .fold(f64::INFINITY, f64::min);
        assert!((min_step - 1.0).abs() < 1e-9);
        assert!(min_step > 0.0);
    }

    #[test]
    fn auto_width_with_nan_filtered_out() {
        // NaN values should be filtered before computing min step.
        let xs: Vec<f64> = vec![1.0, f64::NAN, 3.0, 4.0];
        let mut sorted_xs: Vec<f64> = xs.iter()
            .copied()
            .filter(|v| v.is_finite())
            .collect();
        sorted_xs.sort_by(|a, b| a.partial_cmp(b).unwrap());
        sorted_xs.dedup();
        assert_eq!(sorted_xs, vec![1.0, 3.0, 4.0]);
        let min_step = sorted_xs.windows(2)
            .map(|w| (w[1] - w[0]).abs())
            .filter(|s| *s > 0.0)
            .fold(f64::INFINITY, f64::min);
        assert!((min_step - 1.0).abs() < 1e-9);
    }

    // ── Scene node geometry invariants ───────────────────────────────────

    #[test]
    fn rect_node_width_and_height_non_negative() {
        // Bar rendering must never produce negative width or height.
        let node = SceneNode::Rect {
            x: 10.0,
            y: 20.0,
            w: 0.0, // minimum valid (zero-height bar)
            h: 0.0,
            style: default_fill_stroke(),
            corner_radius: 0.0,
        };
        if let SceneNode::Rect { w, h, .. } = &node {
            assert!(*w >= 0.0, "rect width must be >= 0");
            assert!(*h >= 0.0, "rect height must be >= 0");
        }
    }

    #[test]
    fn rect_node_coordinates_all_finite() {
        let coords = [(10.0, 20.0, 50.0, 30.0), (0.0, 0.0, 1.0, 1.0), (500.0, 300.0, 0.5, 0.5)];
        for (x, y, w, h) in coords {
            let node = SceneNode::Rect {
                x, y, w, h,
                style: default_fill_stroke(),
                corner_radius: 0.0,
            };
            if let SceneNode::Rect { x, y, w, h, .. } = &node {
                assert!(x.is_finite(), "x must be finite");
                assert!(y.is_finite(), "y must be finite");
                assert!(w.is_finite(), "w must be finite");
                assert!(h.is_finite(), "h must be finite");
            }
        }
    }

    #[test]
    fn circle_node_radius_positive() {
        let node = SceneNode::Circle {
            cx: 100.0,
            cy: 200.0,
            r: 0.1, // very small but valid
            style: default_fill_stroke(),
        };
        if let SceneNode::Circle { r, .. } = &node {
            assert!(*r > 0.0, "circle radius must be positive");
            assert!(r.is_finite());
        }
    }

    // ── Per-instance style boundary values ───────────────────────────────

    #[test]
    fn fill_stroke_opacity_clamped_range() {
        // stroke_opacity and fill_opacity must be in [0, 1].
        for &val in &[0.0, 0.5, 1.0] {
            let style = FillStroke {
                fill: Some(Color::rgb(100, 100, 100)),
                stroke: Some(Color::rgb(0, 0, 0)),
                stroke_width: 1.0,
                opacity: 1.0,
                stroke_dash: None,
                stroke_opacity: val,
                fill_opacity: val,
                angle: 0.0,
            };
            assert!(style.stroke_opacity >= 0.0 && style.stroke_opacity <= 1.0);
            assert!(style.fill_opacity >= 0.0 && style.fill_opacity <= 1.0);
        }
    }

    #[test]
    fn fill_stroke_zero_stroke_width_valid() {
        let style = FillStroke {
            fill: Some(Color::rgb(100, 100, 100)),
            stroke: Some(Color::rgb(0, 0, 0)),
            stroke_width: 0.0,
            opacity: 1.0,
            stroke_dash: None,
            stroke_opacity: 1.0,
            fill_opacity: 1.0,
            angle: 0.0,
        };
        assert_eq!(style.stroke_width, 0.0);
        assert!(style.stroke.is_some());
    }

    #[test]
    fn fill_stroke_angle_large_values_finite() {
        // Large angle values (multiple rotations) must stay finite.
        for &angle in &[-720.0, -360.0, 0.0, 360.0, 720.0, 99999.0] {
            let style = FillStroke {
                fill: Some(Color::rgb(100, 100, 100)),
                stroke: None,
                stroke_width: 0.0,
                opacity: 1.0,
                stroke_dash: None,
                stroke_opacity: 1.0,
                fill_opacity: 1.0,
                angle,
            };
            assert!(style.angle.is_finite(), "angle must be finite: {angle}");
        }
    }

    #[test]
    fn stroke_style_negative_width_clamped() {
        // Renderer should never produce negative stroke width.
        let clamped = (-1.0_f64).max(0.0);
        let style = StrokeStyle {
            color: Color::rgb(0, 0, 0),
            width: clamped,
            opacity: 1.0,
            dash: None,
            stroke_cap: None,
            stroke_join: None,
            stroke_opacity: 1.0,
        };
        assert!(style.width >= 0.0);
    }

    // ── Serde round-trip for scene nodes ─────────────────────────────────

    #[test]
    fn circle_serde_round_trip_preserves_all_fields() {
        let node = SceneNode::Circle {
            cx: 123.456,
            cy: 789.012,
            r: 5.5,
            style: FillStroke {
                fill: Some(Color::rgba(255, 0, 0, 128)),
                stroke: Some(Color::rgb(0, 0, 0)),
                stroke_width: 1.5,
                opacity: 0.8,
                stroke_dash: Some(vec![4.0, 2.0]),
                stroke_opacity: 0.6,
                fill_opacity: 0.4,
                angle: 45.0,
            },
        };
        let json = serde_json::to_string(&node).unwrap();
        let back: SceneNode = serde_json::from_str(&json).unwrap();
        if let SceneNode::Circle { cx, cy, r, style } = &back {
            assert!((cx - 123.456).abs() < 1e-9);
            assert!((cy - 789.012).abs() < 1e-9);
            assert!((r - 5.5).abs() < 1e-9);
            assert!((style.stroke_opacity - 0.6).abs() < 1e-9);
            assert!((style.fill_opacity - 0.4).abs() < 1e-9);
            assert!((style.angle - 45.0).abs() < 1e-9);
            assert_eq!(style.stroke_dash.as_ref().unwrap(), &[4.0, 2.0]);
        } else {
            panic!("expected Circle after round-trip");
        }
    }

    #[test]
    fn rect_serde_round_trip_preserves_corner_radius() {
        let node = SceneNode::Rect {
            x: 10.0,
            y: 20.0,
            w: 80.0,
            h: 60.0,
            style: FillStroke {
                fill: Some(Color::rgb(50, 100, 200)),
                stroke: None,
                stroke_width: 0.0,
                opacity: 1.0,
                stroke_dash: None,
                stroke_opacity: 1.0,
                fill_opacity: 0.9,
                angle: 0.0,
            },
            corner_radius: 5.0,
        };
        let json = serde_json::to_string(&node).unwrap();
        let back: SceneNode = serde_json::from_str(&json).unwrap();
        if let SceneNode::Rect { corner_radius, style, .. } = &back {
            assert!((corner_radius - 5.0).abs() < 1e-9);
            assert!((style.fill_opacity - 0.9).abs() < 1e-9);
        } else {
            panic!("expected Rect after round-trip");
        }
    }

    #[test]
    fn polyline_serde_round_trip_preserves_points() {
        let points = vec![(0.0, 0.0), (50.0, 100.0), (100.0, 50.0), (150.0, 75.0)];
        let node = SceneNode::Polyline {
            points: points.clone(),
            style: StrokeStyle {
                color: Color::rgb(0, 128, 255),
                width: 2.0,
                opacity: 1.0,
                dash: None,
                stroke_cap: Some(StrokeCap::Round),
                stroke_join: Some(StrokeJoin::Round),
                stroke_opacity: 0.8,
            },
        };
        let json = serde_json::to_string(&node).unwrap();
        let back: SceneNode = serde_json::from_str(&json).unwrap();
        if let SceneNode::Polyline { points: pts, style } = &back {
            assert_eq!(pts.len(), 4);
            assert!((pts[0].0 - 0.0).abs() < 1e-9);
            assert!((pts[3].1 - 75.0).abs() < 1e-9);
            assert!((style.stroke_opacity - 0.8).abs() < 1e-9);
            assert_eq!(style.stroke_cap, Some(StrokeCap::Round));
            assert_eq!(style.stroke_join, Some(StrokeJoin::Round));
        } else {
            panic!("expected Polyline after round-trip");
        }
    }

    #[test]
    fn path_close_cmd_serde_round_trip() {
        let node = SceneNode::Path {
            commands: vec![
                PathCmd::MoveTo { x: 0.0, y: 0.0 },
                PathCmd::LineTo { x: 100.0, y: 0.0 },
                PathCmd::LineTo { x: 50.0, y: 100.0 },
                PathCmd::Close,
            ],
            style: default_fill_stroke(),
            closed: true,
        };
        let json = serde_json::to_string(&node).unwrap();
        let back: SceneNode = serde_json::from_str(&json).unwrap();
        if let SceneNode::Path { commands, closed, .. } = &back {
            assert_eq!(commands.len(), 4);
            assert!(matches!(commands[3], PathCmd::Close));
            assert!(*closed);
        } else {
            panic!("expected Path after round-trip");
        }
    }

    // ── BandScale/PointScale positioning correctness ─────────────────────

    #[test]
    fn band_scale_three_categories_even_spacing() {
        // Simulate BandScale with 3 categories, no padding, range=[0, 300]
        // step = 300 / 3 = 100; centers at 0, 100, 200 (d3 convention)
        let n = 3_usize;
        let range_extent = 300.0_f64;
        let padding_inner = 0.0_f64;
        let padding_outer = 0.0_f64;

        let denom = (n as f64 - padding_inner + padding_outer * 2.0).max(1.0);
        let step = range_extent / denom;
        assert!((step - 100.0).abs() < 1e-9, "step={step}");

        let bandwidth = step * (1.0 - padding_inner);
        assert!((bandwidth - 100.0).abs() < 1e-9, "bandwidth={bandwidth}");

        // Centers: start + i*step + step*padding_inner/2
        let start = 0.0 + padding_outer * step;
        for i in 0..n {
            let center = start + (i as f64) * step + step * padding_inner / 2.0;
            assert!(center.is_finite());
            assert!(center >= 0.0 && center <= range_extent);
        }
    }

    #[test]
    fn point_scale_single_category_at_center() {
        // Single category -> placed at center of range
        let range_lo = 0.0_f64;
        let range_hi = 200.0_f64;
        let center = (range_lo + range_hi) / 2.0;
        assert!((center - 100.0).abs() < 1e-9);
    }

    #[test]
    fn point_scale_reverse_swaps_positions() {
        // 3 categories, no padding, range=[0, 300]
        // Normal: a=0, b=150, c=300
        // Reversed: a=300, b=150, c=0
        let n = 3_usize;
        let range_lo = 0.0_f64;
        let range_hi = 300.0_f64;
        let padding = 0.0_f64;
        let denom = (n as f64 - 1.0) + padding * 2.0;
        let step = (range_hi - range_lo) / denom;
        assert!((step - 150.0).abs() < 1e-9);

        let positions: Vec<f64> = (0..n).map(|i| range_lo + (i as f64) * step).collect();
        let reversed: Vec<f64> = positions.iter().map(|p| range_hi - (p - range_lo)).collect();

        assert!((reversed[0] - 300.0).abs() < 1e-9);
        assert!((reversed[1] - 150.0).abs() < 1e-9);
        assert!((reversed[2] - 0.0).abs() < 1e-9);
    }

    // ── NaN safety in path commands ──────────────────────────────────────

    #[test]
    fn path_commands_must_have_finite_coordinates() {
        // If any path command has NaN/Inf coordinates, SVG will be invalid.
        let commands = vec![
            PathCmd::MoveTo { x: 10.0, y: 20.0 },
            PathCmd::LineTo { x: 50.0, y: 80.0 },
            PathCmd::LineTo { x: 90.0, y: 30.0 },
            PathCmd::Close,
        ];
        for cmd in &commands {
            match cmd {
                PathCmd::MoveTo { x, y } | PathCmd::LineTo { x, y } => {
                    assert!(x.is_finite(), "x must be finite in path cmd");
                    assert!(y.is_finite(), "y must be finite in path cmd");
                }
                PathCmd::HLineTo { x } => assert!(x.is_finite()),
                PathCmd::VLineTo { y } => assert!(y.is_finite()),
                PathCmd::Close => {}
                _ => {} // QuadTo, CubicTo, ArcTo have their own coordinate checks
            }
        }
    }

    #[test]
    fn fill_stroke_default_fields_omitted_in_json() {
        // When stroke_opacity=1.0, fill_opacity=1.0, angle=0.0, they should be
        // omitted from JSON (skip_serializing_if).
        let style = FillStroke {
            fill: Some(Color::rgb(100, 100, 100)),
            stroke: None,
            stroke_width: 0.0,
            opacity: 1.0,
            stroke_dash: None,
            stroke_opacity: 1.0,
            fill_opacity: 1.0,
            angle: 0.0,
        };
        let json = serde_json::to_string(&style).unwrap();
        assert!(!json.contains("stroke_opacity"),
            "stroke_opacity=1.0 should be omitted, got: {json}");
        assert!(!json.contains("fill_opacity"),
            "fill_opacity=1.0 should be omitted, got: {json}");
        assert!(!json.contains("angle"),
            "angle=0.0 should be omitted, got: {json}");
    }

    #[test]
    fn fill_stroke_non_default_fields_present_in_json() {
        let style = FillStroke {
            fill: Some(Color::rgb(100, 100, 100)),
            stroke: None,
            stroke_width: 0.0,
            opacity: 1.0,
            stroke_dash: None,
            stroke_opacity: 0.5,
            fill_opacity: 0.3,
            angle: 45.0,
        };
        let json = serde_json::to_string(&style).unwrap();
        assert!(json.contains("stroke_opacity"),
            "stroke_opacity=0.5 must be present, got: {json}");
        assert!(json.contains("fill_opacity"),
            "fill_opacity=0.3 must be present, got: {json}");
        assert!(json.contains("angle"),
            "angle=45.0 must be present, got: {json}");
    }
}
