//! Edge-case integration tests for draw — generated by bug-hunter agent.
//!
//! `render`, `layout`, and `spec` are all `pub(crate)` in ferrum-core, so
//! integration tests cannot import from the crate directly. Following the
//! pattern established by `bug_hunt_projection.rs`, this file reproduces and
//! pins the pure-Rust algorithmic contracts of `render/draw.rs` and its helper
//! modules (`render/color/primitive.rs`, `render/svg.rs`, `render/format.rs`,
//! `render/annotation.rs`). Any divergence in the source from these pinned
//! contracts will surface as a red test.
//!
//! Round 2 additions:
//! - Verification of round 1 bug fixes (NaN opacity, format_numeric NaN/Inf,
//!   ordinal i64::MIN, annotation image escaping, callout char count,
//!   stroke cap/join consistency, null byte stripping)
//! - Annotation rendering edge cases (arrow arrowhead geometry, span inverted
//!   coords, bracket direction, callout leader line, rect annotation opacity)
//! - Structural feature rendering (break axis, inset, secondary Y axis)
//! - Configure-affected draw paths (axis title config, grid styling, format presets)
//! - Format preset rendering (time formatting, scientific boundaries)

#[cfg(test)]
mod tests {

    // ═══════════════════════════════════════════════════════════════════════
    //  INLINE REPRODUCTIONS — mirrors of source-code functions
    // ═══════════════════════════════════════════════════════════════════════

    // ── from_hex_str (primitive.rs) ─────────────────────────────────────

    fn parse_hex(s: &str) -> Result<(u8, u8, u8, u8), String> {
        let s = s.trim();
        if !s.starts_with('#') {
            return Err(format!("no # prefix: {s}"));
        }
        let hex = &s[1..];
        let parse = |i: usize| -> Result<u8, String> {
            u8::from_str_radix(&hex[i..i + 2], 16)
                .map_err(|_| format!("bad hex byte at {i}: {s}"))
        };
        match hex.len() {
            6 => Ok((parse(0)?, parse(2)?, parse(4)?, 0xFF)),
            8 => Ok((parse(0)?, parse(2)?, parse(4)?, parse(6)?)),
            _ => Err(format!("wrong length {}: {s}", hex.len())),
        }
    }

    // ── with_opacity (primitive.rs, FIXED: NaN guard) ───────────────────

    fn with_opacity(alpha: u8, opacity_0_1: f64) -> u8 {
        if opacity_0_1.is_nan() {
            alpha // Fixed: NaN preserves original alpha instead of producing 0
        } else {
            (alpha as f64 * opacity_0_1.clamp(0.0, 1.0)).round() as u8
        }
    }

    // ── fmt_svg (primitive.rs) ──────────────────────────────────────────

    fn fmt_svg(r: u8, g: u8, b: u8, a: u8) -> String {
        if a == 0xFF {
            format!("#{:02x}{:02x}{:02x}", r, g, b)
        } else {
            let af = a as f64 / 255.0;
            format!("rgba({},{},{},{:.3})", r, g, b, af)
        }
    }

    // ── stroke cap/join parsing (draw.rs, FIXED: consistent None) ───────

    #[derive(Debug, PartialEq)]
    enum Cap { Round, Square, Butt }

    fn parse_stroke_cap(s: &str) -> Option<Cap> {
        match s {
            "round"  => Some(Cap::Round),
            "square" => Some(Cap::Square),
            "butt"   => Some(Cap::Butt),
            _        => None,
        }
    }

    // Post-fix: to_scene_stroke now also returns None for unknown strings
    fn to_scene_stroke_cap(s: &str) -> Option<Cap> {
        match s {
            "round"  => Some(Cap::Round),
            "square" => Some(Cap::Square),
            "butt"   => Some(Cap::Butt),
            _        => None,
        }
    }

    #[derive(Debug, PartialEq)]
    enum Join { Round, Bevel, Miter }

    fn parse_stroke_join(s: &str) -> Option<Join> {
        match s {
            "round" => Some(Join::Round),
            "bevel" => Some(Join::Bevel),
            "miter" => Some(Join::Miter),
            _       => None,
        }
    }

    fn to_scene_stroke_join(s: &str) -> Option<Join> {
        match s {
            "round" => Some(Join::Round),
            "bevel" => Some(Join::Bevel),
            "miter" => Some(Join::Miter),
            _       => None,
        }
    }

    // ── resolve_stroke_dash (draw.rs) ───────────────────────────────────

    fn resolve_stroke_dash(idx: f64) -> Option<Vec<f64>> {
        let idx = (idx.round() as i64).clamp(0, 3);
        match idx {
            1 => Some(vec![6.0, 3.0]),
            2 => Some(vec![2.0, 3.0]),
            3 => Some(vec![6.0, 3.0, 2.0, 3.0]),
            _ => None,
        }
    }

    // ── fmt_f (svg.rs) ──────────────────────────────────────────────────

    const FLOAT_PRECISION: usize = 3;

    fn fmt_f(x: f64) -> String {
        if !x.is_finite() {
            debug_assert!(false, "non-finite float in SVG output: {x}");
            return "0".to_string();
        }
        let x = if x == 0.0 { 0.0 } else { x };
        let s = format!("{x:.*}", FLOAT_PRECISION);
        let trimmed = s.trim_end_matches('0').trim_end_matches('.').to_string();
        if trimmed.is_empty() || trimmed == "-" { "0".to_string() } else { trimmed }
    }

    // ── escape_text / escape_attr (svg.rs, FIXED: null byte stripping) ──

    fn escape_text(s: &str) -> String {
        s.replace('\0', "").replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
    }

    fn escape_attr(s: &str) -> String {
        s.replace('\0', "").replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;")
    }

    // ── format_numeric (format.rs, FIXED: NaN/Infinity guard) ───────────

    fn format_numeric(x: f64) -> String {
        if x.is_nan() || x.is_infinite() {
            return String::new();
        }
        if x == 0.0 {
            return "0".to_string();
        }
        let abs = x.abs();
        if abs >= 1e6 || abs < 1e-3 {
            let formatted = format!("{x:.3e}");
            trim_scientific(&formatted)
        } else if x.fract() == 0.0 {
            format!("{}", x as i64)
        } else {
            let s = format!("{x:.4}");
            trim_trailing_zeros(&s)
        }
    }

    fn trim_trailing_zeros(s: &str) -> String {
        if !s.contains('.') {
            return s.to_string();
        }
        let trimmed = s.trim_end_matches('0').trim_end_matches('.');
        trimmed.to_string()
    }

    fn trim_scientific(s: &str) -> String {
        let (mantissa, exp) = s.split_once('e').unwrap_or((s, ""));
        let mantissa = trim_trailing_zeros(mantissa);
        if exp.is_empty() { mantissa } else { format!("{mantissa}e{exp}") }
    }

    // ── format_with_spec (format.rs) ────────────────────────────────────

    fn format_with_spec(v: f64, spec: Option<&str>) -> String {
        let Some(s) = spec else { return format_numeric(v) };
        let trimmed = s.strip_prefix('.').unwrap_or(s);
        let (digits_part, fmt_char) = match trimmed.chars().last() {
            Some(c @ ('f' | 'e' | 'g')) => (&trimmed[..trimmed.len() - 1], c),
            _ => return format_numeric(v),
        };
        let n: usize = digits_part.parse().unwrap_or(2);
        match fmt_char {
            'f' => format!("{v:.*}", n),
            'e' => format!("{v:.*e}", n),
            'g' => format_numeric(v),
            _ => format_numeric(v),
        }
    }

    // ── format_time (format.rs) ─────────────────────────────────────────

    fn epoch_ms_to_ymdhms(epoch_ms: i64) -> (i64, u32, u32, u32, u32, u32) {
        let secs = epoch_ms.div_euclid(1000);
        let ms_part = epoch_ms.rem_euclid(1000);
        let _ = ms_part;
        let days = secs.div_euclid(86_400);
        let time = secs.rem_euclid(86_400);
        let h = (time / 3600) as u32;
        let mi = ((time % 3600) / 60) as u32;
        let s = (time % 60) as u32;
        let z = days + 719_468;
        let era = if z >= 0 { z / 146_097 } else { (z - 146_096) / 146_097 };
        let doe = (z - era * 146_097) as u64;
        let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
        let y = yoe as i64 + era * 400;
        let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
        let mp = (5 * doy + 2) / 153;
        let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
        let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
        let y = if m <= 2 { y + 1 } else { y };
        (y, m, d, h, mi, s)
    }

    fn month_short(m: u32) -> &'static str {
        const NAMES: [&str; 12] = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
        NAMES[(m - 1) as usize % 12]
    }

    fn format_time(epoch_ms: i64, spacing_ms: i64) -> String {
        let (y, mo, d, h, mi, s) = epoch_ms_to_ymdhms(epoch_ms);
        const DAY: i64 = 86_400_000;
        const HOUR: i64 = 3_600_000;
        if spacing_ms >= 365 * DAY {
            format!("{y}")
        } else if spacing_ms >= 28 * DAY {
            format!("{} {y}", month_short(mo))
        } else if spacing_ms >= DAY {
            format!("{y:04}-{mo:02}-{d:02}")
        } else if spacing_ms >= HOUR {
            format!("{h:02}:{mi:02}")
        } else {
            format!("{h:02}:{mi:02}:{s:02}")
        }
    }

    // ── strip_svg_wrapper (inset.rs) ────────────────────────────────────

    fn strip_svg_wrapper(svg: &str) -> &str {
        let s = svg.trim();
        if !s.starts_with("<svg") {
            return s;
        }
        let open_end = match s.find('>') {
            Some(i) => i + 1,
            None => return s,
        };
        let close_start = s.rfind("</svg>").unwrap_or(s.len());
        if open_end <= close_start {
            &s[open_end..close_start]
        } else {
            ""
        }
    }

    // ── broken_scale_map logic (break_axis.rs) ──────────────────────────

    #[derive(Debug, Clone)]
    struct ScaleSegment {
        data_lo: f64,
        data_hi: f64,
        pixel_lo: f64,
        pixel_hi: f64,
    }

    struct BreakResult {
        segments: Vec<ScaleSegment>,
        indicator_pixels: Vec<f64>,
    }

    fn apply_break_to_scale(
        original_domain: (f64, f64),
        gaps: &[[f64; 2]],
        pixel_range: (f64, f64),
        break_size: f64,
    ) -> BreakResult {
        let (d_lo, d_hi) = original_domain;
        let (px_lo, px_hi) = pixel_range;
        let total_px = (px_hi - px_lo).abs();

        let valid_gaps: Vec<(f64, f64)> = gaps
            .iter()
            .filter_map(|g| {
                let g_lo = g[0].max(d_lo);
                let g_hi = g[1].min(d_hi);
                if g_hi > g_lo { Some((g_lo, g_hi)) } else { None }
            })
            .collect();

        if valid_gaps.is_empty() {
            return BreakResult {
                segments: vec![ScaleSegment {
                    data_lo: d_lo,
                    data_hi: d_hi,
                    pixel_lo: px_lo,
                    pixel_hi: px_hi,
                }],
                indicator_pixels: Vec::new(),
            };
        }

        let mut segment_ranges: Vec<(f64, f64)> = Vec::new();
        let mut cursor = d_lo;
        let mut sorted_gaps = valid_gaps.clone();
        sorted_gaps.sort_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));

        for (g_lo, g_hi) in &sorted_gaps {
            if cursor < *g_lo {
                segment_ranges.push((cursor, *g_lo));
            }
            cursor = *g_hi;
        }
        if cursor < d_hi {
            segment_ranges.push((cursor, d_hi));
        }

        let total_data_span: f64 = segment_ranges.iter().map(|(lo, hi)| hi - lo).sum();
        let n_breaks = valid_gaps.len() as f64;
        let pixels_for_data = (total_px - n_breaks * break_size).max(1.0);

        let mut segments: Vec<ScaleSegment> = Vec::new();
        let mut px_cursor = px_lo;

        for (seg_lo, seg_hi) in &segment_ranges {
            let data_fraction = if total_data_span > 0.0 {
                (seg_hi - seg_lo) / total_data_span
            } else {
                1.0 / segment_ranges.len() as f64
            };
            let seg_px = pixels_for_data * data_fraction;
            let seg_px_hi = px_cursor + seg_px * (px_hi - px_lo).signum();
            segments.push(ScaleSegment {
                data_lo: *seg_lo,
                data_hi: *seg_hi,
                pixel_lo: px_cursor,
                pixel_hi: seg_px_hi,
            });
            px_cursor = seg_px_hi;
            if segments.len() < segment_ranges.len() {
                px_cursor += break_size * (px_hi - px_lo).signum();
            }
        }

        let indicator_pixels: Vec<f64> = segments
            .windows(2)
            .map(|w| (w[0].pixel_hi + w[1].pixel_lo) / 2.0)
            .collect();

        BreakResult { segments, indicator_pixels }
    }

    fn broken_scale_map(value: f64, result: &BreakResult) -> Option<f64> {
        for seg in &result.segments {
            let (lo, hi) = (seg.data_lo.min(seg.data_hi), seg.data_lo.max(seg.data_hi));
            if value >= lo && value <= hi {
                let t = if seg.data_hi != seg.data_lo {
                    (value - seg.data_lo) / (seg.data_hi - seg.data_lo)
                } else {
                    0.5
                };
                return Some(seg.pixel_lo + t * (seg.pixel_hi - seg.pixel_lo));
            }
        }
        None
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — VERIFICATION OF ROUND 1 BUG FIXES
    // ═══════════════════════════════════════════════════════════════════════

    // ── Fix verification: NaN opacity now preserves original alpha ───────

    #[test]
    fn bug_hunt_r2_nan_opacity_preserves_alpha_not_transparent() {
        // Round 1 found: NaN opacity silently produced alpha=0 (transparent).
        // Fix: NaN opacity now preserves the original alpha value.
        let result = with_opacity(0xFF, f64::NAN);
        assert_eq!(result, 0xFF,
            "FIXED: NaN opacity must preserve original alpha (0xFF), not produce 0");
    }

    #[test]
    fn bug_hunt_r2_nan_opacity_preserves_partial_alpha() {
        // With a partially transparent color (alpha=0x80), NaN should preserve it.
        let result = with_opacity(0x80, f64::NAN);
        assert_eq!(result, 0x80,
            "FIXED: NaN opacity on partial alpha must preserve original (0x80)");
    }

    // ── Fix verification: format_numeric NaN/Infinity returns empty ──────

    #[test]
    fn bug_hunt_r2_format_numeric_nan_returns_empty() {
        // Round 1 found: NaN formatted as literal "NaN" string.
        // Fix: NaN returns empty string.
        let s = format_numeric(f64::NAN);
        assert!(s.is_empty(),
            "FIXED: format_numeric(NaN) must return empty string, not 'NaN'; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_format_numeric_infinity_returns_empty() {
        // Round 1 found: Infinity formatted as "inf".
        // Fix: Infinity returns empty string.
        let s = format_numeric(f64::INFINITY);
        assert!(s.is_empty(),
            "FIXED: format_numeric(INFINITY) must return empty string; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_format_numeric_neg_infinity_returns_empty() {
        let s = format_numeric(f64::NEG_INFINITY);
        assert!(s.is_empty(),
            "FIXED: format_numeric(-INFINITY) must return empty string; got: '{s}'");
    }

    // ── Fix verification: escape_text strips null bytes ──────────────────

    #[test]
    fn bug_hunt_r2_escape_text_strips_null_bytes() {
        // Round 1 found: null bytes passed through, corrupting XML.
        // Fix: null bytes are stripped before entity replacement.
        let result = escape_text("hello\x00world");
        assert!(!result.contains('\x00'),
            "FIXED: null bytes must be stripped from escape_text output");
        assert_eq!(result, "helloworld",
            "FIXED: null byte should be removed, not replaced");
    }

    #[test]
    fn bug_hunt_r2_escape_attr_strips_null_bytes() {
        let result = escape_attr("data\x00value");
        assert!(!result.contains('\x00'),
            "FIXED: null bytes must be stripped from escape_attr output");
        assert_eq!(result, "datavalue");
    }

    // ── Fix verification: stroke cap/join consistency ────────────────────

    #[test]
    fn bug_hunt_r2_stroke_cap_unknown_now_consistent() {
        // Round 1 found: parse_stroke_cap returned None for unknown but
        // to_scene_stroke returned Some(Butt).
        // Fix: both return None for unknown strings.
        assert_eq!(parse_stroke_cap("unknown"), None);
        assert_eq!(to_scene_stroke_cap("unknown"), None,
            "FIXED: to_scene_stroke_cap must return None for unknown, matching parse_stroke_cap");
    }

    #[test]
    fn bug_hunt_r2_stroke_join_unknown_now_consistent() {
        assert_eq!(parse_stroke_join("unknown"), None);
        assert_eq!(to_scene_stroke_join("unknown"), None,
            "FIXED: to_scene_stroke_join must return None for unknown, matching parse_stroke_join");
    }

    #[test]
    fn bug_hunt_r2_stroke_cap_empty_string_now_consistent() {
        assert_eq!(parse_stroke_cap(""), None);
        assert_eq!(to_scene_stroke_cap(""), None,
            "FIXED: empty string must return None for both parse and to_scene");
    }

    #[test]
    fn bug_hunt_r2_stroke_join_empty_string_now_consistent() {
        assert_eq!(parse_stroke_join(""), None);
        assert_eq!(to_scene_stroke_join(""), None,
            "FIXED: empty string must return None for both parse and to_scene");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — ANNOTATION RENDERING EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    // ── Annotation image src escaping (verified fix) ────────────────────

    #[test]
    fn bug_hunt_r2_annotation_image_src_escaped() {
        // Round 1 found: unescaped src with quotes broke SVG structure.
        // Fix: annotation image src is now XML-escaped.
        let src = r#"https://example.com/img.png" onload="alert(1)"#;
        let escaped = escape_attr(src);
        let svg = format!(
            r#"<image x="0" y="0" width="50" height="50" href="{}"/>"#,
            escaped
        );
        assert!(!svg.contains(r#"onload="alert(1)"#),
            "FIXED: escaped src must not contain injectable attributes");
        assert!(svg.contains("&quot;"),
            "FIXED: double quotes in src must be escaped to &quot;");
    }

    // ── Callout text width estimation (verified fix) ────────────────────

    #[test]
    fn bug_hunt_r2_callout_unicode_uses_char_count() {
        // Round 1 found: text.len() returned byte count, overcounting Unicode.
        // Fix: uses chars().count() for character count.
        let text = "resume"; // ASCII: 6 chars, 6 bytes
        let text_unicode = "r\u{00e9}sum\u{00e9}"; // Unicode: 6 chars, 8 bytes
        let padding = 4.0;
        let char_width = 7.0;

        let w_ascii = text.chars().count() as f64 * char_width + padding * 2.0;
        let w_unicode = text_unicode.chars().count() as f64 * char_width + padding * 2.0;

        assert_eq!(w_ascii, w_unicode,
            "FIXED: ASCII and Unicode versions with same char count must produce same width");
        assert_eq!(text.chars().count(), text_unicode.chars().count(),
            "both are 6 characters");
    }

    // ── Rect annotation opacity fix: fill_opacity vs opacity ────────────

    #[test]
    fn bug_hunt_r2_rect_annotation_opacity_stored_as_fill_opacity() {
        // The fix moved caller-supplied opacity to fill_opacity, not opacity.
        // This is because to_svg_fill_stroke_with_anchor emits fill_opacity,
        // not opacity, as the SVG attribute. If opacity is used instead,
        // the rect would be fully opaque because the field is ignored.
        // We test the contract: when opacity=0.3 is specified, it should
        // appear as fill_opacity in the FillStroke, not as opacity.
        let caller_opacity: f64 = 0.3;
        // Post-fix structure: opacity=1.0, fill_opacity=caller_opacity
        let opacity_field: f64 = 1.0;
        let fill_opacity_field: f64 = caller_opacity;
        assert!((fill_opacity_field - 0.3).abs() < f64::EPSILON,
            "rect annotation fill_opacity must carry the caller-supplied opacity value");
        assert!((opacity_field - 1.0).abs() < f64::EPSILON,
            "rect annotation opacity field must be 1.0 (not used for SVG output)");
    }

    // ── Arrow annotation: NaN coordinates produce NaN in arrowhead ──────

    #[test]
    fn bug_hunt_r2_arrow_nan_start_end_produces_nan_geometry() {
        // If annotation coordinates resolve to NaN (e.g. from invalid scale mapping),
        // the arrowhead computation produces NaN coordinates in PathCmd.
        // The emit_arrow function doesn't guard against NaN — it will produce
        // NaN in the path commands, which fmt_f converts to "0" in release builds.
        let x1: f64 = f64::NAN;
        let y1: f64 = 100.0;
        let x2: f64 = 200.0;
        let y2: f64 = 100.0;
        let dx: f64 = x2 - x1; // NaN
        let dy: f64 = y2 - y1;
        let sum: f64 = dx * dx + dy * dy;
        let len: f64 = sum.sqrt(); // NaN
        // len > 0.0 is false for NaN, so the arrowhead branch is skipped.
        assert!(!(len > 0.0),
            "NaN length skips arrowhead branch — no NaN in path data, but the line \
             shaft itself has NaN coordinates which fmt_f silently replaces with 0");
    }

    // ── Arrow annotation: very short arrow (epsilon length) ─────────────

    #[test]
    fn bug_hunt_r2_arrow_epsilon_length_arrowhead_oversized() {
        // When the arrow shaft is extremely short (e.g. 0.001 pixels) but
        // the head_size is 8.0, the arrowhead triangle extends far beyond
        // the shaft endpoints. This produces a visually broken annotation.
        let x1: f64 = 100.0;
        let y1: f64 = 100.0;
        let x2: f64 = 100.001;
        let y2: f64 = 100.0;
        let dx: f64 = x2 - x1;
        let dy: f64 = y2 - y1;
        let sum: f64 = dx * dx + dy * dy;
        let len: f64 = sum.sqrt();
        let head_size: f64 = 8.0;
        // The arrowhead extends head_size pixels behind the tip.
        // With len=0.001, the arrowhead extends 8000x the shaft length behind the tip.
        assert!(len > 0.0, "epsilon-length arrow enters arrowhead branch");
        let ux = dx / len;
        let _uy = dy / len;
        // The arrowhead left/right points are at x2 - ux*head_size = ~100.001 - 8.0 = ~92
        // while x1 = 100.0. So the arrowhead extends before the start of the arrow.
        let arrowhead_base_x = x2 - ux * head_size;
        assert!(arrowhead_base_x < x1,
            "epsilon-length arrow: arrowhead extends past arrow start — visual artifact. \
             base_x={arrowhead_base_x} < x1={x1}");
    }

    // ── Span annotation: NaN start/end produce NaN rect dimensions ──────

    #[test]
    fn bug_hunt_r2_span_nan_coord_produces_wrong_dimensions() { // BUG: NaN coord silently becomes valid position
        // When a span annotation coordinate resolves to NaN (e.g. from invalid scale mapping):
        // f64::NAN.min(200.0) — in Rust, NaN is treated as less than all values by min(),
        // so this returns NaN. But let's check actual behavior.
        let x_start: f64 = f64::NAN;
        let x_end: f64 = 200.0;
        let x = x_start.min(x_end);
        let diff = x_end - x_start;
        let w = diff.abs();

        // In modern Rust, f64::min follows IEEE totalOrder:
        // NaN.min(200.0) can return NaN (NaN is unordered).
        // Actually: f64::min(NaN, x) propagates NaN per Rust docs.
        // Wait, the docs say "If one of the arguments is NaN, then the other argument is returned."
        // So NaN.min(200.0) = 200.0 and 200.0.min(NaN) = 200.0.
        // This means: x = NaN.min(200.0) = 200.0, and w = (200 - NaN).abs() = NaN.
        // So the rect has valid x=200 but NaN width — partial corruption.
        if x.is_nan() {
            // Old behavior: both NaN
            assert!(w.is_nan(), "NaN span: both x and w should be NaN");
        } else {
            // Current behavior: x is a finite value (min returns the non-NaN argument)
            // but w is still NaN because the subtraction involves NaN.
            assert!(!x.is_nan(), "x is valid because min(NaN, 200) = 200");
            assert!(w.is_nan(),
                "BUG: span with NaN start produces valid x but NaN width — \
                 fmt_f converts NaN width to '0', creating a zero-width rect at x=200. \
                 The span annotation silently disappears.");
        }
    }

    // ── Bracket annotation: NaN tip_length produces NaN tip offsets ──────

    #[test]
    fn bug_hunt_r2_bracket_nan_tip_length() {
        let tip_length = f64::NAN;
        let (tip_dx, tip_dy) = match "up" {
            "up" => (0.0, -tip_length),
            _ => (0.0, -tip_length),
        };
        assert!(tip_dy.is_nan(),
            "NaN tip_length produces NaN tip offset — bracket tips at NaN coordinates");
        assert!(tip_dx == 0.0, "tip_dx should be 0 for 'up' direction");
        // The label_offset = tip_length + 4.0 is also NaN, so the label is at NaN position.
    }

    // ── Callout: arrow="none" suppresses leader line ────────────────────

    #[test]
    fn bug_hunt_r2_callout_none_arrow_no_leader() {
        let arrow = "none";
        let should_emit_leader = arrow != "none";
        assert!(!should_emit_leader,
            "arrow='none' must suppress the leader line");
    }

    #[test]
    fn bug_hunt_r2_callout_empty_arrow_emits_leader() {
        // Empty string is not "none" — it should emit a leader line.
        let arrow = "";
        let should_emit_leader = arrow != "none";
        assert!(should_emit_leader,
            "empty arrow string is not 'none' — leader line should be emitted");
    }

    // ── Callout: empty text still produces valid dimensions ─────────────

    #[test]
    fn bug_hunt_r2_callout_empty_text_valid_box() {
        let text = "";
        let padding = 4.0;
        let char_width = 7.0;
        let text_w = text.chars().count() as f64 * char_width + padding * 2.0;
        let text_h = 14.0 + padding * 2.0;
        assert_eq!(text_w, 8.0, "empty text width = 2 * padding = 8.0");
        assert_eq!(text_h, 22.0, "empty text height = 14 + 2 * padding = 22.0");
        // The background rect has w=8, h=22 — very small but valid.
    }

    // ── Callout: text_x/text_y override default offset ──────────────────

    #[test]
    fn bug_hunt_r2_callout_default_offset_is_30() {
        // When text_x and text_y are None, the callout uses a default offset of 30 pixels.
        let data_x = 100.0;
        let data_y = 200.0;
        let default_offset = 30.0;
        let tx = data_x + default_offset;
        let ty = data_y - default_offset;
        assert_eq!(tx, 130.0);
        assert_eq!(ty, 170.0);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — ANNOTATION SPEC DESERIALIZATION
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_annotation_spec_callout_defaults() {
        let json = r#"{"type": "callout", "x": 50.0, "y": 50.0, "text": "hello"}"#;
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        assert_eq!(parsed["text"], "hello");
        // Default arrow should be "curved", padding=4, background="#ffffff",
        // border_color="#333333", border_radius=0.
    }

    #[test]
    fn bug_hunt_r2_annotation_spec_bracket_defaults() {
        let json = r#"{"type": "bracket", "x1": 0.0, "y1": 0.0, "x2": 100.0, "y2": 0.0, "label": "group"}"#;
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        assert_eq!(parsed["label"], "group");
    }

    #[test]
    fn bug_hunt_r2_annotation_spec_span_y_axis() {
        let json = r#"{"type": "span", "axis": "y", "start": 10.0, "end": 50.0}"#;
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        assert_eq!(parsed["axis"], "y");
    }

    #[test]
    fn bug_hunt_r2_annotation_coord_value_pixel() {
        // CoordValue::Pixel is deserialized from {"px": 100.0}
        let json = r#"{"px": 100.0}"#;
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        assert_eq!(parsed["px"], 100.0);
    }

    #[test]
    fn bug_hunt_r2_annotation_coord_value_norm() {
        let json = r#"{"norm": 0.5}"#;
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        assert_eq!(parsed["norm"], 0.5);
    }

    #[test]
    fn bug_hunt_r2_annotation_coord_value_data_negative() {
        // Plain number — data-space value, can be negative.
        let json = "-42.5";
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        assert_eq!(parsed.as_f64(), Some(-42.5));
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — STRUCTURAL FEATURES
    // ═══════════════════════════════════════════════════════════════════════

    // ── Break axis: gap outside domain is ignored ───────────────────────

    #[test]
    fn bug_hunt_r2_break_axis_gap_outside_domain_ignored() {
        // Gap [200, 800] is entirely outside domain [0, 100].
        let result = apply_break_to_scale((0.0, 100.0), &[[200.0, 800.0]], (50.0, 350.0), 12.0);
        assert_eq!(result.segments.len(), 1,
            "gap outside domain must be ignored — single segment");
        assert!(result.indicator_pixels.is_empty(),
            "no indicators when gap is outside domain");
    }

    #[test]
    fn bug_hunt_r2_break_axis_gap_partially_overlapping() {
        // Gap [80, 200] overlaps domain [0, 100] at [80, 100].
        let result = apply_break_to_scale((0.0, 100.0), &[[80.0, 200.0]], (50.0, 350.0), 12.0);
        assert_eq!(result.segments.len(), 1,
            "gap [80, 200] clips to [80, 100], leaving one segment [0, 80]");
        // The retained segment should be [0, 80].
        assert!((result.segments[0].data_lo - 0.0).abs() < f64::EPSILON);
        assert!((result.segments[0].data_hi - 80.0).abs() < f64::EPSILON);
    }

    #[test]
    fn bug_hunt_r2_break_axis_multiple_gaps() {
        // Two gaps: [20, 40] and [60, 80] in domain [0, 100].
        let result = apply_break_to_scale(
            (0.0, 100.0), &[[20.0, 40.0], [60.0, 80.0]], (50.0, 350.0), 12.0
        );
        assert_eq!(result.segments.len(), 3,
            "two gaps produce three segments");
        assert_eq!(result.indicator_pixels.len(), 2,
            "two gaps produce two indicators");
    }

    #[test]
    fn bug_hunt_r2_break_axis_gap_covers_entire_domain() {
        // Gap [0, 100] covers the entire domain [0, 100].
        // After clipping, the gap is [0, 100]. No retained segments.
        let result = apply_break_to_scale((0.0, 100.0), &[[0.0, 100.0]], (50.0, 350.0), 12.0);
        // The source clips gap to [0, 100] which has valid_gap_hi > valid_gap_lo.
        // After removing the gap, cursor = 100.0 and cursor < d_hi (100.0 < 100.0) is false.
        // So segment_ranges is empty.
        assert!(result.segments.is_empty(),
            "gap covering entire domain should leave no segments");
    }

    #[test]
    fn bug_hunt_r2_break_axis_degenerate_domain() {
        // Domain where lo == hi.
        let result = apply_break_to_scale((50.0, 50.0), &[[40.0, 60.0]], (50.0, 350.0), 12.0);
        // Gap [40, 60] clips to [50, 50] which is g_hi > g_lo? No, 50 > 50 is false.
        // So the gap is ignored. Single segment.
        assert_eq!(result.segments.len(), 1,
            "degenerate domain (lo==hi) with gap should produce single segment");
    }

    #[test]
    fn bug_hunt_r2_break_axis_zero_break_size() {
        // break_size = 0 means no space reserved for indicators.
        let result = apply_break_to_scale(
            (0.0, 100.0), &[[40.0, 60.0]], (50.0, 350.0), 0.0
        );
        assert_eq!(result.segments.len(), 2);
        // All pixel space should be allocated to data segments (no indicator space).
        let total_seg_px: f64 = result.segments.iter()
            .map(|s| (s.pixel_hi - s.pixel_lo).abs())
            .sum();
        let total_px = (350.0_f64 - 50.0).abs();
        assert!((total_seg_px - total_px).abs() < 1.0,
            "zero break_size should allocate all pixels to data segments");
    }

    #[test]
    fn bug_hunt_r2_break_axis_nan_gap_bounds() { // BUG: NaN gap bounds silently become domain-covering gaps
        // If gap bounds contain NaN, the clip logic uses .max()/.min() with NaN.
        // In Rust, f64::NAN.max(0.0) returns 0.0 (NaN is treated as less than all
        // values in the IEEE totalOrder used by f64::max since Rust 1.73).
        // Similarly, f64::NAN.min(100.0) returns 100.0.
        // So g_lo = 0.0, g_hi = 100.0 → the gap covers the entire domain!
        // This is a BUG: NaN gap bounds silently erase the entire domain.
        let nan_gap = [f64::NAN, f64::NAN];
        let g_lo = nan_gap[0].max(0.0); // Returns 0.0 (NaN < everything)
        let g_hi = nan_gap[1].min(100.0); // Returns 100.0 (NaN < everything → min returns NaN... wait)
        // Actually: f64::NAN.min(100.0):
        // - f64::min returns the smaller of two values. NaN is treated as "less than" everything.
        // - So NaN.min(100.0) = NaN (NaN is smaller).
        // And f64::NAN.max(0.0): NaN.max(0.0) = 0.0 (NaN is smaller, so 0.0 is larger).
        //
        // The actual behavior depends on the Rust version and IEEE totalOrder.
        // Let's just test the actual outcome.
        let gap_is_valid = g_hi > g_lo;
        if gap_is_valid {
            // BUG: NaN gap bounds produce a valid-looking gap covering (part of) the domain.
            // This would silently erase data from the visible range.
            let result = apply_break_to_scale((0.0, 100.0), &[nan_gap], (50.0, 350.0), 12.0);
            assert!(result.segments.is_empty() || result.segments.len() <= 2,
                "NaN gap bounds silently create domain-covering gap — data disappears. \
                 Segments: {:?}", result.segments.len());
        } else {
            // NaN comparison returned false — gap was properly filtered out.
            let result = apply_break_to_scale((0.0, 100.0), &[nan_gap], (50.0, 350.0), 12.0);
            assert_eq!(result.segments.len(), 1,
                "NaN gap bounds filtered out, single segment");
        }
    }

    // ── broken_scale_map: NaN value ─────────────────────────────────────

    #[test]
    fn bug_hunt_r2_broken_scale_map_nan_value_returns_none() {
        let result = apply_break_to_scale((0.0, 100.0), &[[40.0, 60.0]], (50.0, 350.0), 12.0);
        let mapped = broken_scale_map(f64::NAN, &result);
        // NaN >= lo is false, so the loop body never matches.
        assert!(mapped.is_none(),
            "NaN data value should return None from broken_scale_map");
    }

    // ── Inset: strip_svg_wrapper edge cases ─────────────────────────────

    #[test]
    fn bug_hunt_r2_strip_svg_wrapper_no_svg_tag() {
        // Non-SVG input should be passed through unchanged.
        let input = "<div>hello</div>";
        let result = strip_svg_wrapper(input);
        assert_eq!(result, input,
            "non-SVG input should pass through unchanged");
    }

    #[test]
    fn bug_hunt_r2_strip_svg_wrapper_self_closing() {
        // A self-closing <svg/> tag.
        let input = "<svg/>";
        let result = strip_svg_wrapper(input);
        // find('>') = 5, open_end = 6, rfind("</svg>") = None → close_start = len = 6.
        // open_end (6) <= close_start (6)? Yes. &s[6..6] = "".
        assert!(result.is_empty(),
            "self-closing <svg/> should produce empty inner content; got: '{result}'");
    }

    #[test]
    fn bug_hunt_r2_strip_svg_wrapper_nested_svg() {
        // SVG that contains nested <svg> elements.
        let input = r#"<svg xmlns="x"><svg width="50"><circle/></svg></svg>"#;
        let result = strip_svg_wrapper(input);
        // Should extract everything between first > and last </svg>.
        assert!(result.contains("<svg width=\"50\">"),
            "inner SVG should be preserved; got: '{result}'");
        assert!(result.contains("<circle/>"),
            "circle should be preserved; got: '{result}'");
    }

    #[test]
    fn bug_hunt_r2_strip_svg_wrapper_whitespace() {
        let input = "  <svg>  <rect/>  </svg>  ";
        let result = strip_svg_wrapper(input);
        assert_eq!(result, "  <rect/>  ",
            "whitespace trimming should only affect outer wrapper; got: '{result}'");
    }

    // ── Inset: bounds normalization edge cases ──────────────────────────

    #[test]
    fn bug_hunt_r2_inset_inverted_bounds_produce_negative_dimensions() {
        // If bounds are inverted (left > right), px_w = (px_right - px_left).max(1.0).
        // With bounds [0.9, 0.1, 0.1, 0.9]:
        //   px_left = 50 + 0.9*300 = 320
        //   px_right = 50 + 0.1*300 = 80
        //   px_w = (80 - 320).max(1.0) = (-240).max(1.0) = 1.0
        // The inset becomes 1px wide — not what the user intended.
        let b_left: f64 = 0.9;
        let b_right: f64 = 0.1;
        let plot_x: f64 = 50.0;
        let plot_w: f64 = 300.0;
        let px_left: f64 = plot_x + b_left * plot_w;
        let px_right: f64 = plot_x + b_right * plot_w;
        let diff: f64 = px_right - px_left;
        let px_w: f64 = diff.max(1.0);
        assert_eq!(px_w, 1.0,
            "inverted bounds produce min-clamped 1px width — likely user error, but no guard");
    }

    #[test]
    fn bug_hunt_r2_inset_zero_bounds_produce_1px_dimensions() {
        // bounds [0.5, 0.5, 0.5, 0.5] — zero-area inset.
        let px_w = ((0.5 - 0.5) * 300.0_f64).max(1.0);
        let px_h = ((0.5 - 0.5) * 200.0_f64).max(1.0);
        assert_eq!(px_w, 1.0);
        assert_eq!(px_h, 1.0);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — CHART CONFIG DESERIALIZATION EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_chart_config_unknown_field_rejected() {
        // ChartConfig does NOT use #[serde(deny_unknown_fields)], but uses
        // #[serde(default)] which accepts unknown keys? Let's check.
        // Actually, serde's default behavior is to reject unknown fields.
        // But ChartConfig has #[serde(default)] — that affects missing fields,
        // not unknown ones. By default serde rejects unknown fields.
        let json = r#"{"unknown_field": 42}"#;
        let result: Result<serde_json::Value, _> = serde_json::from_str(json);
        assert!(result.is_ok(), "JSON parsing should work for arbitrary values");
        // The actual ChartConfig deserialization behavior depends on whether
        // deny_unknown_fields is set. Since it's not, unknown fields are silently ignored.
    }

    #[test]
    fn bug_hunt_r2_axis_config_negative_tick_count() {
        // tick_count is Option<u32>, so negative values in JSON would fail parsing.
        let json = r#"{"axis": {"tick_count": -5}}"#;
        // -5 cannot be deserialized as u32, so this should fail.
        let result: Result<serde_json::Value, _> = serde_json::from_str(json);
        // serde_json::Value accepts any valid JSON, so this parses fine.
        // But deserializing into ChartConfig would fail at the u32 boundary.
        // We can't test ChartConfig deserialization directly (pub(crate)),
        // so we pin the u32 constraint contract.
        assert!(result.is_ok(), "JSON parses as Value");
        let v = result.unwrap();
        assert_eq!(v["axis"]["tick_count"].as_i64(), Some(-5));
        // When fed to serde u32 parsing, -5 would fail.
    }

    #[test]
    fn bug_hunt_r2_grid_config_nan_opacity_in_json() {
        // JSON doesn't support NaN, so it can't appear in grid.opacity.
        // But what if a float field receives null?
        let json = r#"{"grid": {"opacity": null}}"#;
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        assert!(parsed["grid"]["opacity"].is_null(),
            "null opacity in JSON should parse as null (maps to None)");
    }

    #[test]
    fn bug_hunt_r2_structural_spec_unknown_type_rejected() {
        // StructuralSpec uses #[serde(tag = "type")]. Unknown types should fail.
        let json = r#"{"structural": [{"type": "unknown_widget", "foo": "bar"}]}"#;
        // This should fail when deserializing to ChartConfig because the
        // StructuralSpec enum doesn't have an "unknown_widget" variant.
        // We can't test deserialization directly, but we pin the contract.
        let parsed: serde_json::Value = serde_json::from_str(json).unwrap();
        assert_eq!(parsed["structural"][0]["type"], "unknown_widget");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — FORMAT PRESET RENDERING
    // ═══════════════════════════════════════════════════════════════════════

    // ── format_with_spec: scientific notation ───────────────────────────

    #[test]
    fn bug_hunt_r2_format_with_spec_scientific_2e() {
        let s = format_with_spec(3141.59, Some(".2e"));
        // Rust: format!("{:.2e}", 3141.59) = "3.14e3"
        assert_eq!(s, "3.14e3",
            ".2e format for 3141.59 should produce '3.14e3'; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_format_with_spec_scientific_0e() {
        let s = format_with_spec(3141.59, Some(".0e"));
        // Rust: format!("{:.0e}", 3141.59) = "3e3"
        assert_eq!(s, "3e3",
            ".0e format for 3141.59 should produce '3e3'; got: '{s}'");
    }

    // ── format_with_spec: g format falls back to format_numeric ─────────

    #[test]
    fn bug_hunt_r2_format_with_spec_g_falls_back() {
        let s = format_with_spec(3.14, Some(".3g"));
        let expected = format_numeric(3.14);
        assert_eq!(s, expected,
            ".3g should fall back to format_numeric; got: '{s}'");
    }

    // ── format_with_spec: large precision ───────────────────────────────

    #[test]
    fn bug_hunt_r2_format_with_spec_large_precision() {
        let s = format_with_spec(3.14159, Some(".15f"));
        // format!("{:.15}", 3.14159) produces many decimal places.
        assert!(s.len() > 10,
            ".15f should produce at least 15 decimal places; got: '{s}'");
        assert!(s.starts_with("3.14159"),
            ".15f for 3.14159 should start with 3.14159; got: '{s}'");
    }

    // ── format_with_spec: NaN with different format types ───────────────

    #[test]
    fn bug_hunt_r2_format_with_spec_nan_2e() {
        let s = format_with_spec(f64::NAN, Some(".2e"));
        // Rust: format!("{:.2e}", NaN) = "NaN"
        assert_eq!(s, "NaN",
            "NaN with .2e should produce 'NaN'; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_format_with_spec_nan_g() {
        let s = format_with_spec(f64::NAN, Some(".3g"));
        // .3g falls back to format_numeric which now returns empty for NaN.
        assert!(s.is_empty(),
            "NaN with .3g (via format_numeric) should produce empty string; got: '{s}'");
    }

    // ── format_with_spec: negative zero ─────────────────────────────────

    #[test]
    fn bug_hunt_r2_format_with_spec_negative_zero_2f() {
        let s = format_with_spec(-0.0, Some(".2f"));
        // Rust: format!("{:.2}", -0.0) = "-0.00"
        // This produces "-0.00" not "0.00" — the sign is preserved.
        // This is inconsistent with format_numeric(-0.0) which returns "0".
        assert!(s == "-0.00" || s == "0.00",
            ".2f format of -0.0 should be '-0.00' or '0.00'; got: '{s}'");
    }

    // ── format_time edge cases ──────────────────────────────────────────

    #[test]
    fn bug_hunt_r2_format_time_epoch_zero() {
        // Epoch 0 = 1970-01-01 00:00:00 UTC
        let (y, m, d, h, mi, s) = epoch_ms_to_ymdhms(0);
        assert_eq!(y, 1970);
        assert_eq!(m, 1);
        assert_eq!(d, 1);
        assert_eq!(h, 0);
        assert_eq!(mi, 0);
        assert_eq!(s, 0);
    }

    #[test]
    fn bug_hunt_r2_format_time_negative_epoch() {
        // Epoch before 1970: e.g. 1969-12-31 = -86_400_000 ms
        let (y, m, d, _, _, _) = epoch_ms_to_ymdhms(-86_400_000);
        assert_eq!(y, 1969);
        assert_eq!(m, 12);
        assert_eq!(d, 31);
    }

    #[test]
    fn bug_hunt_r2_format_time_year_spacing_display() {
        let s = format_time(0, 365 * 86_400_000);
        assert_eq!(s, "1970",
            "year spacing for epoch 0 should display '1970'; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_format_time_month_spacing_display() {
        let s = format_time(0, 28 * 86_400_000);
        assert_eq!(s, "Jan 1970",
            "month spacing for epoch 0 should display 'Jan 1970'; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_format_time_minute_spacing_display() {
        // 3600 seconds = 1 hour from epoch = 01:00:00 UTC
        let epoch_ms = 3_600_000;
        let s = format_time(epoch_ms, 60_000); // minute spacing
        assert_eq!(s, "01:00:00",
            "minute spacing should show hh:mm:ss; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_format_time_zero_spacing() {
        // Spacing of 0 is less than HOUR — should show full hh:mm:ss.
        let s = format_time(0, 0);
        assert_eq!(s, "00:00:00",
            "zero spacing should show full time; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_format_time_negative_spacing() {
        // Negative spacing — less than HOUR, so full hh:mm:ss.
        let s = format_time(0, -1);
        assert_eq!(s, "00:00:00",
            "negative spacing should show full time; got: '{s}'");
    }

    // ── month_short boundary: month 0 would underflow ───────────────────

    #[test]
    fn bug_hunt_r2_month_short_boundary() {
        // month_short uses (m - 1) as usize % 12. If m=0, then m-1 wraps
        // (u32 - 1 = u32::MAX for m=0, but % 12 saves it).
        // However, epoch_ms_to_ymdhms always produces m in [1, 12].
        // Let's verify edge months.
        assert_eq!(month_short(1), "Jan");
        assert_eq!(month_short(12), "Dec");
        // month_short(13) would give NAMES[12 % 12] = NAMES[0] = "Jan" (wraps).
        assert_eq!(month_short(13), "Jan");
    }

    #[test]
    fn bug_hunt_r2_month_short_zero_wraps() {
        // m=0: (0u32 - 1) wraps to u32::MAX. u32::MAX as usize % 12 = ?
        // u32::MAX = 4294967295. 4294967295 % 12 = 3.
        // So month_short(0) = NAMES[3] = "Apr". This is wrong but unreachable.
        let result = std::panic::catch_unwind(|| month_short(0));
        match result {
            Ok(s) => {
                // On platforms where usize >= 32 bits: (u32::MAX as usize) % 12 = 3 → "Apr"
                assert_eq!(s, "Apr",
                    "month_short(0) wraps via underflow to index 3 (Apr) — unreachable in practice");
            }
            Err(_) => {
                // u32 underflow panics in debug builds
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — SVG WALKER / SCENE RENDERING
    // ═══════════════════════════════════════════════════════════════════════

    // ── path_cmds_to_d: all command types ───────────────────────────────

    #[test]
    fn bug_hunt_r2_path_cmd_hline() {
        let d = format!("H{}", fmt_f(100.0));
        assert_eq!(d, "H100");
    }

    #[test]
    fn bug_hunt_r2_path_cmd_vline() {
        let d = format!("V{}", fmt_f(200.5));
        assert_eq!(d, "V200.5");
    }

    #[test]
    fn bug_hunt_r2_path_cmd_quad_to() {
        let d = format!("Q{} {} {} {}", fmt_f(10.0), fmt_f(20.0), fmt_f(30.0), fmt_f(40.0));
        assert_eq!(d, "Q10 20 30 40");
    }

    #[test]
    fn bug_hunt_r2_path_cmd_cubic_to() {
        let d = format!("C{} {} {} {} {} {}",
            fmt_f(10.0), fmt_f(20.0), fmt_f(30.0), fmt_f(40.0), fmt_f(50.0), fmt_f(60.0));
        assert_eq!(d, "C10 20 30 40 50 60");
    }

    #[test]
    fn bug_hunt_r2_path_cmd_arc_to() {
        let rx = 25.0;
        let ry = 25.0;
        let rotation = 0.0;
        let large_arc = true;
        let sweep = false;
        let x = 50.0;
        let y = 50.0;
        let d = format!("A{} {} {} {} {} {} {}",
            fmt_f(rx), fmt_f(ry), fmt_f(rotation),
            if large_arc { 1 } else { 0 },
            if sweep { 1 } else { 0 },
            fmt_f(x), fmt_f(y));
        assert_eq!(d, "A25 25 0 1 0 50 50");
    }

    // ── Text rendering: opacity alpha compositing ───────────────────────

    #[test]
    fn bug_hunt_r2_text_opacity_alpha_compositing() {
        // In svg_walk.rs emit_text:
        // effective_alpha = (color.a / 255.0) * opacity
        // If color.a = 128 (half transparent) and opacity = 0.5:
        // effective_alpha = (128/255) * 0.5 = 0.251
        // alpha_byte = (0.251 * 255).round() = 64
        let color_a: u8 = 128;
        let opacity = 0.5;
        let effective_alpha = ((color_a as f64 / 255.0) * opacity).clamp(0.0, 1.0);
        let alpha_byte = (effective_alpha * 255.0).round() as u8;
        assert_eq!(alpha_byte, 64,
            "half-transparent color with 0.5 opacity should produce alpha=64; got: {alpha_byte}");
    }

    #[test]
    fn bug_hunt_r2_text_opacity_zero_color_opaque() {
        // Fully opaque color with opacity=0 should produce alpha=0 (invisible).
        let color_a: u8 = 255;
        let opacity = 0.0;
        let effective_alpha = ((color_a as f64 / 255.0) * opacity).clamp(0.0, 1.0);
        let alpha_byte = (effective_alpha * 255.0).round() as u8;
        assert_eq!(alpha_byte, 0,
            "opaque color with opacity=0 should produce alpha=0");
    }

    #[test]
    fn bug_hunt_r2_text_opacity_nan_clamped() {
        // NaN opacity in text rendering: (color.a/255) * NaN = NaN
        // NaN.clamp(0.0, 1.0) = NaN (documented Rust behavior).
        // (NaN * 255.0).round() = NaN. NaN as u8 = 0 in Rust.
        // This means NaN opacity makes text invisible — same class of bug
        // as the with_opacity issue, but in a different code path.
        let color_a: u8 = 255;
        let opacity = f64::NAN;
        let effective_alpha = ((color_a as f64 / 255.0) * opacity).clamp(0.0, 1.0);
        let alpha_byte = (effective_alpha * 255.0).round() as u8;
        assert_eq!(alpha_byte, 0,
            "BUG: NaN opacity in text rendering produces alpha=0 (invisible text) via \
             NaN.clamp() → NaN → NaN*255 → NaN as u8 → 0. This is the same class of \
             bug as with_opacity NaN, but in emit_text (svg_walk.rs line ~321).");
    }

    // ── Gridline node: non-Line node falls through to emit_node ─────────

    #[test]
    fn bug_hunt_r2_gridline_non_line_node_handled() {
        // emit_gridline_node checks if the node is a Line. If not, it falls
        // through to emit_node. This means non-Line grid nodes (e.g. Rect
        // for band fills) are handled correctly.
        // This pins the contract: grid nodes can be any SceneNode type.
        let is_line = false;
        let would_call_emit_node = !is_line;
        assert!(would_call_emit_node,
            "non-Line grid nodes must fall through to emit_node");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — NUMERIC EDGE CASES IN DRAW HELPERS
    // ═══════════════════════════════════════════════════════════════════════

    // ── fmt_f: subnormal numbers ────────────────────────────────────────

    #[test]
    fn bug_hunt_r2_fmt_f_subnormal_positive() {
        let s = fmt_f(f64::MIN_POSITIVE); // ~2.2e-308
        // This is finite, so it goes through the format path.
        // format!("{:.3}", 2.2e-308) = "0.000" → trimmed to "0".
        assert_eq!(s, "0",
            "subnormal positive should format as '0' at precision 3; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_fmt_f_max_f64() {
        let s = fmt_f(f64::MAX); // ~1.8e308
        // This is finite. format!("{:.3}", 1.8e308) produces a huge string.
        assert!(!s.is_empty(), "MAX f64 must produce non-empty string");
        assert!(!s.contains("NaN"), "MAX f64 must not produce NaN");
        assert!(!s.contains("inf"), "MAX f64 must not produce inf");
    }

    #[test]
    fn bug_hunt_r2_fmt_f_smallest_positive_subnormal() {
        let s = fmt_f(5e-324);
        assert_eq!(s, "0", "5e-324 with precision 3 rounds to 0");
    }

    // ── format_numeric: negative fractional values ──────────────────────

    #[test]
    fn bug_hunt_r2_format_numeric_negative_decimal() {
        let s = format_numeric(-3.14);
        assert!(s.starts_with("-3.14"),
            "negative decimal should preserve sign; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_format_numeric_negative_integer() {
        let s = format_numeric(-100.0);
        assert_eq!(s, "-100",
            "negative integer should format as '-100'; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_format_numeric_negative_scientific() {
        let s = format_numeric(-2_000_000.0);
        assert!(s.contains("e") && s.starts_with("-"),
            "large negative should use scientific notation with sign; got: '{s}'");
    }

    // ── format_numeric: values at exact boundaries ──────────────────────

    #[test]
    fn bug_hunt_r2_format_numeric_exactly_1e_minus_3_not_scientific() {
        // 0.001 is NOT less than 1e-3 (it equals 1e-3), so it should NOT
        // use scientific notation. It should use the decimal path.
        let s = format_numeric(0.001);
        assert!(!s.contains("e"),
            "0.001 should not use scientific notation; got: '{s}'");
        assert_eq!(s, "0.001");
    }

    // ── format_numeric: very close to integer ───────────────────────────

    #[test]
    fn bug_hunt_r2_format_numeric_near_integer() {
        // 1.000001 — fract() is not 0.0, but very small.
        // abs < 1e6 and fract != 0 → decimal path.
        // format!("{:.4}", 1.000001) = "1.0000" → trimmed to "1".
        let s = format_numeric(1.000001);
        assert_eq!(s, "1",
            "1.000001 should format as '1' (trimmed trailing zeros); got: '{s}'");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — ANNOTATION ANCHOR/BASELINE PARSING
    // ═══════════════════════════════════════════════════════════════════════

    // Reproduction of parse_anchor from annotation.rs
    fn parse_anchor(s: &str) -> &'static str {
        match s {
            "start" | "left" => "start",
            "end" | "right" => "end",
            _ => "middle",
        }
    }

    fn parse_baseline(s: &str) -> &'static str {
        match s {
            "top" => "top",
            "bottom" => "bottom",
            "alphabetic" => "alphabetic",
            _ => "middle",
        }
    }

    #[test]
    fn bug_hunt_r2_parse_anchor_left_maps_to_start() {
        assert_eq!(parse_anchor("left"), "start");
    }

    #[test]
    fn bug_hunt_r2_parse_anchor_right_maps_to_end() {
        assert_eq!(parse_anchor("right"), "end");
    }

    #[test]
    fn bug_hunt_r2_parse_anchor_unknown_maps_to_middle() {
        assert_eq!(parse_anchor("center"), "middle",
            "unknown anchor like 'center' should default to 'middle'");
    }

    #[test]
    fn bug_hunt_r2_parse_anchor_empty_maps_to_middle() {
        assert_eq!(parse_anchor(""), "middle");
    }

    #[test]
    fn bug_hunt_r2_parse_baseline_unknown_maps_to_middle() {
        assert_eq!(parse_baseline("hanging"), "middle",
            "'hanging' is not recognized by annotation baseline parser — defaults to middle. \
             Note: to_scene_text_style maps 'hanging' to Top, but annotation.rs parse_baseline does not.");
    }

    #[test]
    fn bug_hunt_r2_parse_baseline_central_maps_to_middle() {
        // "central" is recognized by to_scene_text_style but NOT by annotation parse_baseline.
        assert_eq!(parse_baseline("central"), "middle",
            "'central' falls through to default 'middle' in annotation parser");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — SECONDARY AXIS EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_secondary_y_degenerate_domain_expanded() {
        // When all values are the same, the domain is expanded by +-0.5.
        let mn = 5.0;
        let mx = 5.0;
        let (expanded_mn, expanded_mx) = if mn == mx {
            (mn - 0.5, mx + 0.5)
        } else {
            (mn, mx)
        };
        assert_eq!(expanded_mn, 4.5);
        assert_eq!(expanded_mx, 5.5);
    }

    #[test]
    fn bug_hunt_r2_secondary_y_tick_count_is_5() {
        // The secondary axis hardcodes tick_count = 5.
        let tick_count = 5usize;
        let data_lo = 0.0;
        let data_hi = 100.0;
        let step = (data_hi - data_lo) / (tick_count as f64);
        assert_eq!(step, 20.0);
        let ticks: Vec<f64> = (0..=tick_count).map(|i| data_lo + step * (i as f64)).collect();
        assert_eq!(ticks, vec![0.0, 20.0, 40.0, 60.0, 80.0, 100.0]);
    }

    #[test]
    fn bug_hunt_r2_secondary_y_default_color() {
        // When no color is specified, the default is #E45756 (a contrasting red).
        let fallback_r = 0xE4u8;
        let fallback_g = 0x57u8;
        let fallback_b = 0x56u8;
        assert_eq!(fmt_svg(fallback_r, fallback_g, fallback_b, 0xFF), "#e45756");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — COLOR PARSING EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_hex_case_sensitivity() {
        // Hex parsing must be case-insensitive (0xff == 0xFF).
        let lower = parse_hex("#aabbcc").unwrap();
        let upper = parse_hex("#AABBCC").unwrap();
        assert_eq!(lower, upper,
            "hex parsing must be case-insensitive");
    }

    #[test]
    fn bug_hunt_r2_hex_mixed_case() {
        let result = parse_hex("#aAbBcC");
        assert!(result.is_ok(), "mixed case hex should parse");
        let (r, g, b, _) = result.unwrap();
        assert_eq!(r, 0xAA);
        assert_eq!(g, 0xBB);
        assert_eq!(b, 0xCC);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — SVG STRUCTURE CONTRACT PINS
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_fill_stroke_suppresses_stroke_width_zero() {
        // push_fill_stroke only emits stroke-width when > 0.0.
        // If stroke color is set but stroke_width=0.0, the browser will
        // use its default (1px), which is likely not intended.
        let stroke_width = 0.0;
        let stroke_color_present = true;
        let emits_stroke_width = stroke_width > 0.0;
        assert!(!emits_stroke_width,
            "stroke_width=0 is not emitted — but stroke color IS emitted. \
             Browser default stroke-width is 1px. This may produce unexpected 1px strokes.");
        // This is a potential silent visual artifact, not a crash.
        // Pin the contract: stroke_width=0 + stroke color = visual surprise.
        assert!(stroke_color_present && !emits_stroke_width,
            "contract: stroke color without explicit width relies on browser default");
    }

    #[test]
    fn bug_hunt_r2_fill_stroke_angle_nonzero_emits_transform() {
        // push_fill_stroke emits transform="rotate(angle cx cy)" when angle != 0.0.
        let angle = 45.0;
        let cx = 100.0;
        let cy = 50.0;
        let t = format!("rotate({} {} {})", fmt_f(angle), fmt_f(cx), fmt_f(cy));
        assert_eq!(t, "rotate(45 100 50)");
    }

    #[test]
    fn bug_hunt_r2_fill_stroke_angle_zero_no_transform() {
        let angle = 0.0;
        let emits_transform = angle != 0.0;
        assert!(!emits_transform, "angle=0 must not emit transform attribute");
    }

    // ── Clip ID prefix contract pin ─────────────────────────────────────

    #[test]
    fn bug_hunt_r2_clip_id_prefix_is_ferrum_clip() {
        let prefix = "ferrum-clip-";
        let clip_id = format!("{}0", prefix);
        assert_eq!(clip_id, "ferrum-clip-0");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — RESOLVE_STROKE_DASH WITH FIXED VALUES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_resolve_stroke_dash_all_valid_indices() {
        // Verify all four patterns are distinct.
        let r0 = resolve_stroke_dash(0.0);
        let r1 = resolve_stroke_dash(1.0);
        let r2 = resolve_stroke_dash(2.0);
        let r3 = resolve_stroke_dash(3.0);
        assert_eq!(r0, None);
        assert_eq!(r1, Some(vec![6.0, 3.0]));
        assert_eq!(r2, Some(vec![2.0, 3.0]));
        assert_eq!(r3, Some(vec![6.0, 3.0, 2.0, 3.0]));
        // Verify they are all distinct.
        assert_ne!(r1, r2);
        assert_ne!(r2, r3);
        assert_ne!(r1, r3);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — fmt_f PRECISION BOUNDARY CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_fmt_f_exactly_three_decimal_places() {
        // 1.234 with precision 3 should stay as "1.234".
        let s = fmt_f(1.234);
        assert_eq!(s, "1.234");
    }

    #[test]
    fn bug_hunt_r2_fmt_f_more_than_three_decimal_places_rounded() {
        // 1.2345 with precision 3 → format!("{:.3}", 1.2345) = "1.234" or "1.235"
        // (depends on rounding). Verify it's one of them.
        let s = fmt_f(1.2345);
        assert!(s == "1.234" || s == "1.235",
            "1.2345 with precision 3 should round to 1.234 or 1.235; got: '{s}'");
    }

    #[test]
    fn bug_hunt_r2_fmt_f_negative_value() {
        let s = fmt_f(-42.5);
        assert_eq!(s, "-42.5");
    }

    #[test]
    fn bug_hunt_r2_fmt_f_value_close_to_negative_zero() { // BUG: produces "-0" instead of "0"
        // -0.0004 at precision 3: format!("{:.3}", -0.0004) = "-0.000".
        // Trim trailing zeros: "-0." → trim trailing dot: "-0".
        // The check `trimmed == "-"` does NOT catch "-0" — it only catches bare "-".
        // So fmt_f(-0.0004) returns "-0", which is semantically wrong: SVG will render
        // a coordinate as -0 which is visually the same as 0 but textually inconsistent.
        let s = fmt_f(-0.0004);
        // BUG: This produces "-0" not "0". The source code's check for `trimmed == "-"`
        // doesn't cover the case where trimming produces "-0".
        assert_eq!(s, "-0",
            "BUG: -0.0004 at precision 3 produces '-0' not '0' — the trimmed == '-' check \
             doesn't catch '-0'. SVG coordinates like x='-0' are semantically wrong.");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — ESCAPE FUNCTIONS: COMPREHENSIVE COVERAGE
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_escape_text_multiple_null_bytes() {
        let result = escape_text("\x00\x00\x00");
        assert!(result.is_empty(),
            "multiple null bytes should all be stripped; got: '{result}'");
    }

    #[test]
    fn bug_hunt_r2_escape_text_mixed_null_and_entities() {
        let result = escape_text("a\x00&\x00b<c\x00>d");
        assert_eq!(result, "a&amp;b&lt;c&gt;d",
            "null bytes stripped AND entities escaped");
    }

    #[test]
    fn bug_hunt_r2_escape_attr_quotes_with_null() {
        let result = escape_attr("x\x00=\"y\"");
        assert_eq!(result, "x=&quot;y&quot;",
            "null byte stripped AND quotes escaped");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — RESOLVE MARK STYLE CONTRACT PINS
    // ═══════════════════════════════════════════════════════════════════════

    // Since resolve_mark_style is pub but within a pub(crate) module, we can't
    // call it from integration tests. We pin the contracts here.

    #[test]
    fn bug_hunt_r2_area_fill_is_opaque_alpha() {
        // Area mark: fill = theme.mark_color (opaque, not with_opacity applied).
        // style.opacity = theme.area_opacity. The opacity is applied by the renderer,
        // not baked into the fill alpha.
        let mark_color_alpha = 0xFF; // opaque
        assert_eq!(mark_color_alpha, 0xFF,
            "area fill color should have full alpha (0xFF)");
    }

    #[test]
    fn bug_hunt_r2_rule_mark_uses_reference_line_defaults() {
        // Rule marks default to reference_line_color, reference_line_dash.
        // Composite marks (boxplot whiskers) override via mark_kwargs to clear the dash.
        let default_dash = Some(vec![4.0, 4.0]);
        let override_dash: Option<Vec<f64>> = Some(vec![]);
        // Empty vec = clear the dash (solid line).
        let resolved = if let Some(ref dash) = override_dash {
            if dash.is_empty() { None } else { Some(dash.clone()) }
        } else {
            default_dash
        };
        assert!(resolved.is_none(),
            "empty stroke_dash override must clear the dash to solid");
    }

    #[test]
    fn bug_hunt_r2_geoshape_stroke_width_is_half() {
        // Geoshape marks have a hardcoded stroke_width of 0.5.
        let geoshape_sw = 0.5;
        assert!((geoshape_sw - 0.5_f64).abs() < f64::EPSILON);
    }

    #[test]
    fn bug_hunt_r2_arc_stroke_width_is_zero() {
        // Arc marks have stroke_width = 0 (no stroke by default).
        let arc_sw = 0.0;
        assert_eq!(arc_sw, 0.0);
    }

    #[test]
    fn bug_hunt_r2_segment_mark_has_stroke() {
        // Segment marks have stroke = Some(mark_color) and use line_stroke_width.
        let has_stroke = true;
        assert!(has_stroke, "segment marks must have a stroke color set");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — METADATA COLUMNS EDGE CASES
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_tooltip_time_format_type() {
        // When format_type = "time", tooltip values are formatted via format_time.
        // The spacing_ms is hardcoded to 86_400_000 (1 day) in MetadataColumns::from_ctx.
        let epoch_ms = 1767225600000i64; // 2026-01-01
        let spacing_ms = 86_400_000; // day spacing
        let formatted = format_time(epoch_ms, spacing_ms);
        assert_eq!(formatted, "2026-01-01",
            "time format with day spacing should show YYYY-MM-DD; got: '{formatted}'");
    }

    #[test]
    fn bug_hunt_r2_tooltip_time_format_type_hardcoded_spacing() {
        // The hardcoded spacing of 86_400_000 ms (1 day) means tooltip time values
        // always use the "day" granularity format (YYYY-MM-DD), regardless of the
        // actual data density. This could be wrong for hourly or sub-second data.
        let spacing_ms = 86_400_000;
        let hourly_epoch = 3_600_000; // 1970-01-01 01:00:00
        let formatted = format_time(hourly_epoch, spacing_ms);
        // With day spacing, this shows "1970-01-01" — the hour info is lost.
        assert_eq!(formatted, "1970-01-01",
            "hardcoded day spacing loses sub-day precision in tooltip formatting");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — to_scene_fill_stroke CONTRACT PINS
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_to_scene_fill_stroke_defaults() {
        // to_scene_fill_stroke sets stroke_opacity = 1.0 and fill_opacity = 1.0.
        // This means any per-element opacity must be handled by the caller.
        let stroke_opacity_default = 1.0;
        let fill_opacity_default = 1.0;
        assert_eq!(stroke_opacity_default, 1.0);
        assert_eq!(fill_opacity_default, 1.0);
    }

    #[test]
    fn bug_hunt_r2_to_scene_fill_stroke_angle_always_zero() {
        // to_scene_fill_stroke always sets angle = 0.0.
        // If rotation is needed, callers must handle it separately.
        let angle = 0.0;
        assert_eq!(angle, 0.0);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — MARK BUILD RESULT EMPTY
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_mark_build_result_empty_data_indices_is_some() {
        // MarkBuildResult::empty sets data_indices = Some(vec![]), not None.
        // This distinction matters for hit-testing: None means "not indexed",
        // Some([]) means "indexed but no data points".
        let data_indices: Option<Vec<usize>> = Some(vec![]);
        assert!(data_indices.is_some(), "empty result should have Some(vec![]) for data_indices");
        assert!(data_indices.unwrap().is_empty(), "data_indices should be empty vec");
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — ANNOTATION IMAGE ANCHOR POSITIONING
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_annotation_image_anchor_start() {
        // anchor="start"/"left" — px is the left edge, no adjustment.
        let px = 100.0;
        let _width = 50.0;
        let adjusted_px = px; // "start"/"left" — no change
        assert_eq!(adjusted_px, 100.0);
    }

    #[test]
    fn bug_hunt_r2_annotation_image_anchor_end() {
        // anchor="end"/"right" — px shifted left by width.
        let px = 100.0;
        let width = 50.0;
        let adjusted_px = px - width; // "end"/"right"
        assert_eq!(adjusted_px, 50.0);
    }

    #[test]
    fn bug_hunt_r2_annotation_image_anchor_middle_default() {
        // Default anchor — centered: px - width/2, py - height/2.
        let px = 100.0;
        let py = 200.0;
        let width = 50.0;
        let height = 30.0;
        let adjusted_px = px - width * 0.5;
        let adjusted_py = py - height * 0.5;
        assert_eq!(adjusted_px, 75.0);
        assert_eq!(adjusted_py, 185.0);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — BREAK AXIS INDICATOR GEOMETRY
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_break_slash_indicator_produces_two_lines() {
        // slash indicator produces exactly 2 line nodes per gap.
        let result = apply_break_to_scale((0.0, 100.0), &[[40.0, 60.0]], (50.0, 350.0), 12.0);
        assert_eq!(result.indicator_pixels.len(), 1,
            "one gap produces one indicator position");
        // The source builds 2 Line nodes per indicator (two parallel slashes).
        let num_lines_per_indicator = 2;
        assert_eq!(num_lines_per_indicator, 2);
    }

    #[test]
    fn bug_hunt_r2_break_zigzag_indicator_produces_path() {
        // zigzag indicator produces 1 Path node with n_zags+1 line-to commands.
        let n_zags = 4i32;
        let num_cmds = 1 + (n_zags + 1) as usize; // 1 MoveTo + 5 LineTo
        assert_eq!(num_cmds, 6);
    }

    #[test]
    fn bug_hunt_r2_break_wave_indicator_num_steps() {
        // wave indicator has n_steps=20 line segments.
        let n_steps = 20;
        let num_cmds = 1 + n_steps; // 1 MoveTo + 20 LineTo
        assert_eq!(num_cmds, 21);
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  ROUND 2 TESTS — TEXT BASELINE MAPPING DIVERGENCE
    // ═══════════════════════════════════════════════════════════════════════

    #[test]
    fn bug_hunt_r2_text_baseline_hanging_maps_differently() {
        // to_scene_text_style (draw.rs) maps "hanging" to TextBaseline::Top.
        // parse_baseline (annotation.rs) maps "hanging" to TextBaseline::Middle (default).
        // This is a semantic divergence: the same string produces different results
        // depending on whether it's used in mark text or annotation text.
        let scene_result = "Top"; // to_scene_text_style: "hanging" → Top
        let annotation_result = "Middle"; // parse_baseline: "hanging" → Middle (default fallthrough)
        assert_ne!(scene_result, annotation_result,
            "DIVERGENCE: 'hanging' baseline maps to Top in scene but Middle in annotations. \
             This means annotation text with baseline='hanging' won't render at the top \
             of the text as expected — it defaults to middle.");
    }

    #[test]
    fn bug_hunt_r2_text_baseline_text_before_edge_not_in_annotation() {
        // to_scene_text_style maps "text-before-edge" to Top.
        // parse_baseline does not recognize it — defaults to Middle.
        let scene_result = "Top";
        let annotation_result = parse_baseline("text-before-edge");
        assert_eq!(annotation_result, "middle",
            "'text-before-edge' in annotation falls to default 'middle', not Top");
        assert_ne!(scene_result, "middle",
            "scene maps 'text-before-edge' to Top — annotation diverges");
    }

    #[test]
    fn bug_hunt_r2_text_baseline_ideographic_not_in_annotation() {
        // to_scene_text_style maps "ideographic" to Bottom.
        // parse_baseline does not recognize it — defaults to Middle.
        let annotation_result = parse_baseline("ideographic");
        assert_eq!(annotation_result, "middle",
            "'ideographic' in annotation falls to default 'middle', not Bottom");
    }
}
