"""Edge-case tests for coerce-transport — generated by bug-hunter agent."""
from __future__ import annotations

import json
import math

import pyarrow as pa
import polars as pl
import pytest

from ferrum._coerce import to_arrow_table


# ── Polars paths ─────────────────────────────────────────────────────────────

def test_polars_lazyframe_collected():
    """LazyFrame should be collected and returned as an Arrow Table."""
    lf = pl.LazyFrame({"x": [10, 20, 30], "y": [1.0, 2.0, 3.0]})
    tbl = to_arrow_table(lf)
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 3
    assert tbl.column_names == ["x", "y"]


def test_polars_dataframe_with_nulls_preserved():
    """Null values in a polars DataFrame should survive the Arrow round-trip."""
    df = pl.DataFrame({"a": [1, None, 3], "b": [None, 2.0, 3.0]})
    tbl = to_arrow_table(df)
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 3
    # null count preserved
    assert tbl.column("a").null_count == 1
    assert tbl.column("b").null_count == 1


def test_polars_all_null_column():
    """An all-null column should be representable (not raise)."""
    df = pl.DataFrame({"a": pl.Series([None, None, None], dtype=pl.Int64)})
    tbl = to_arrow_table(df)
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 3
    assert tbl.column("a").null_count == 3


def test_polars_boolean_column():
    """Boolean columns should pass through without coercion errors."""
    df = pl.DataFrame({"flag": [True, False, True]})
    tbl = to_arrow_table(df)
    assert isinstance(tbl, pa.Table)
    assert tbl.column("flag").type == pa.bool_()


def test_polars_string_column_with_numeric_strings():
    """String columns containing numeric-looking values stay as strings."""
    df = pl.DataFrame({"val": ["1", "2.5", "3"]})
    tbl = to_arrow_table(df)
    assert tbl.column("val").type in (pa.string(), pa.large_string())


def test_polars_zero_row_dataframe():
    """A zero-row polars DataFrame should produce a zero-row Arrow Table."""
    df = pl.DataFrame({"a": pl.Series([], dtype=pl.Int64), "b": pl.Series([], dtype=pl.Float64)})
    tbl = to_arrow_table(df)
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 0
    assert "a" in tbl.column_names
    assert "b" in tbl.column_names


# ── PyArrow paths ─────────────────────────────────────────────────────────────

def test_pyarrow_recordbatch_schema_preserved():
    """RecordBatch wrapping preserves column types."""
    schema = pa.schema([("x", pa.int32()), ("y", pa.float64())])
    rb = pa.RecordBatch.from_pydict({"x": pa.array([1, 2], type=pa.int32()),
                                     "y": pa.array([3.0, 4.0], type=pa.float64())},
                                    schema=schema)
    tbl = to_arrow_table(rb)
    assert isinstance(tbl, pa.Table)
    assert tbl.schema.field("x").type == pa.int32()
    assert tbl.schema.field("y").type == pa.float64()


def test_pyarrow_empty_table_passthrough():
    """An empty pyarrow Table (0 rows) is returned unchanged."""
    empty = pa.table({"a": pa.array([], type=pa.int64())})
    tbl = to_arrow_table(empty)
    assert tbl is empty
    assert tbl.num_rows == 0


# ── dict paths ────────────────────────────────────────────────────────────────

def test_dict_with_empty_columns():
    """A dict with no keys should produce a zero-column table, not raise."""
    tbl = to_arrow_table({})
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 0
    assert tbl.num_columns == 0


def test_dict_mixed_types():
    """A dict with mixed value types (int, float, str) should coerce cleanly."""
    tbl = to_arrow_table({"a": [1, 2, 3], "b": [1.1, 2.2, 3.3], "c": ["x", "y", "z"]})
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 3
    assert tbl.num_columns == 3


def test_dict_with_none_values_in_lists():
    """Lists with None entries (null scalars) should be accepted."""
    tbl = to_arrow_table({"a": [1, None, 3]})
    assert isinstance(tbl, pa.Table)
    assert tbl.column("a").null_count == 1


# ── list paths ────────────────────────────────────────────────────────────────

def test_empty_list_raises_value_error():
    """An empty list should raise ValueError, not produce a broken table."""
    with pytest.raises(ValueError, match="empty list"):
        to_arrow_table([])


def test_list_of_non_dicts_raises_type_error():
    """A list of non-dict items should raise TypeError with a legible message."""
    with pytest.raises(TypeError, match="list of dicts"):
        to_arrow_table([1, 2, 3])


def test_single_row_list():
    """A list with exactly one dict should produce a 1-row table."""
    tbl = to_arrow_table([{"a": 42, "b": "hello"}])
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 1


def test_list_of_dicts_with_missing_keys():
    """Rows that have different keys should fill missing ones with null."""
    tbl = to_arrow_table([{"a": 1, "b": 2}, {"a": 3}])
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 2
    assert "b" in tbl.column_names
    # second row's "b" should be null
    assert tbl.column("b")[1].as_py() is None


# ── numpy paths ───────────────────────────────────────────────────────────────

def test_numpy_3d_raises_type_error():
    """3D numpy arrays should raise TypeError."""
    np = pytest.importorskip("numpy")
    arr = np.zeros((2, 3, 4))
    with pytest.raises(TypeError, match="ndim=3"):
        to_arrow_table(arr)


def test_numpy_2d_zero_rows():
    """A 2D numpy array with 0 rows should produce an empty table."""
    np = pytest.importorskip("numpy")
    arr = np.empty((0, 3), dtype=float)
    tbl = to_arrow_table(arr)
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 0
    assert tbl.column_names == ["col_0", "col_1", "col_2"]


def test_numpy_2d_single_row():
    """A 2D numpy array with exactly 1 row should produce a 1-row table."""
    np = pytest.importorskip("numpy")
    arr = np.array([[10.0, 20.0, 30.0]])
    tbl = to_arrow_table(arr)
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 1
    assert tbl.column_names == ["col_0", "col_1", "col_2"]


def test_numpy_2d_float_inf_nan():
    """inf/nan values in a 2D numpy array should be representable in the Arrow table."""
    np = pytest.importorskip("numpy")
    arr = np.array([[float("inf"), float("-inf"), float("nan")]])
    tbl = to_arrow_table(arr)
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 1
    val = tbl.column("col_0")[0].as_py()
    assert math.isinf(val) and val > 0


# ── GeoJSON paths ─────────────────────────────────────────────────────────────

def test_geojson_feature_collection_properties_become_columns():
    """GeoJSON FeatureCollection: properties should become Arrow columns."""
    fc = {
        "type": "FeatureCollection",
        "features": [
            {"type": "Feature", "geometry": {"type": "Point", "coordinates": [0, 0]},
             "properties": {"name": "A", "value": 1}},
            {"type": "Feature", "geometry": {"type": "Point", "coordinates": [1, 1]},
             "properties": {"name": "B", "value": 2}},
        ],
    }
    tbl = to_arrow_table(fc)
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 2
    assert "name" in tbl.column_names
    assert "value" in tbl.column_names
    assert "__geometry__" in tbl.column_names


def test_geojson_feature_collection_geometry_is_json_string():
    """The __geometry__ column should contain valid JSON strings."""
    fc = {
        "type": "FeatureCollection",
        "features": [
            {"type": "Feature",
             "geometry": {"type": "Point", "coordinates": [10.0, 20.0]},
             "properties": {}},
        ],
    }
    tbl = to_arrow_table(fc)
    geom_str = tbl.column("__geometry__")[0].as_py()
    parsed = json.loads(geom_str)
    assert parsed["type"] == "Point"
    assert parsed["coordinates"] == [10.0, 20.0]


def test_geojson_feature_collection_null_geometry():
    """Features with null geometry should store 'null' in __geometry__."""
    fc = {
        "type": "FeatureCollection",
        "features": [
            {"type": "Feature", "geometry": None, "properties": {"a": 1}},
        ],
    }
    tbl = to_arrow_table(fc)
    assert tbl.column("__geometry__")[0].as_py() == "null"


def test_geojson_empty_features_list():
    """A FeatureCollection with no features returns a table with __geometry__ column."""
    fc = {"type": "FeatureCollection", "features": []}
    tbl = to_arrow_table(fc)
    assert isinstance(tbl, pa.Table)
    assert "__geometry__" in tbl.column_names
    assert tbl.num_rows == 0


def test_geojson_bare_geometry_wrapped():
    """A bare GeoJSON Geometry dict should be wrapped and yield a 1-row table."""
    geom = {"type": "Point", "coordinates": [5.0, 10.0]}
    tbl = to_arrow_table(geom)
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 1
    assert "__geometry__" in tbl.column_names
    parsed = json.loads(tbl.column("__geometry__")[0].as_py())
    assert parsed["type"] == "Point"


def test_geojson_polygon_bare_geometry():
    """A bare Polygon geometry should be wrapped into a single-row table."""
    geom = {
        "type": "Polygon",
        "coordinates": [[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]],
    }
    tbl = to_arrow_table(geom)
    assert isinstance(tbl, pa.Table)
    assert tbl.num_rows == 1
    assert "__geometry__" in tbl.column_names


def test_regular_dict_with_type_key_not_geojson():  # BUG: _is_geojson_geometry_root raises TypeError: unhashable type: 'list' when dict["type"] is a list
    """A dict with a 'type' key that is not a GeoJSON type is treated as a plain dict."""
    # Use parallel lists so pyarrow can build a valid table
    d = {"type": ["foo", "bar"], "data": [1, 2]}
    tbl = to_arrow_table(d)
    assert isinstance(tbl, pa.Table)
    assert "type" in tbl.column_names
    assert "data" in tbl.column_names
    assert tbl.num_rows == 2


# ── error contracts ───────────────────────────────────────────────────────────

def test_none_raises_value_error_with_legible_message():
    """None input should raise ValueError mentioning per-layer data."""
    with pytest.raises(ValueError, match="per-layer data"):
        to_arrow_table(None)


def test_integer_raises_type_error():
    """A bare integer should raise TypeError mentioning Unsupported."""
    with pytest.raises(TypeError, match="Unsupported data type"):
        to_arrow_table(42)


def test_string_raises_type_error():
    """A bare string should raise TypeError mentioning Unsupported."""
    with pytest.raises(TypeError, match="Unsupported data type"):
        to_arrow_table("not a dataframe")
