"""Edge-case tests for selection-state-machine -- generated by bug-hunter agent."""

from __future__ import annotations

import json

import polars as pl
import pytest

import ferrum as fm
from ferrum._core import render_interactive
from ferrum._interactive import InteractiveChart, _render_scene
from ferrum.selection import (
    ConditionalSpec,
    Selection,
    SelectionMark,
    _LiteralValue,
    _resolve_channel,
    _resolve_encoding_value,
    selection_interval,
    selection_point,
    selection_single,
    selection_multi,
    value,
)


# ── helpers ──────────────────────────────────────────────────────────────────


def _render(chart: fm.Chart) -> tuple[str, bytes]:
    """Render a chart to (scene_json_str, packed_bytes)."""
    return _render_scene(chart)


def _small_df():
    return pl.DataFrame({"x": [1.0, 2.0, 3.0], "y": [4.0, 5.0, 6.0], "g": ["a", "b", "c"]})


# ── 1. toggle edge cases ────────────────────────────────────────────────────


def test_toggle_empty_indices_via_selection_single():
    """selection_single disables toggle (toggle='false'), so shift-clicking
    should replace the selection rather than toggling. Verify the toggle
    parameter is serialized as 'click' (the mapped value for 'false')."""
    sel = selection_single(name="ts_sel")
    d = sel.to_spec_dict()
    # toggle="false" maps to "click" in the event map
    assert d["toggle"] == "click", (
        f"toggle must be 'click' for selection_single; got {d['toggle']!r}"
    )


def test_toggle_selection_multi_has_shift_key():
    """selection_multi must serialize toggle as 'shift_key'."""
    sel = selection_multi(name="tm_sel")
    d = sel.to_spec_dict()
    assert d["toggle"] == "shift_key", f"toggle must be 'shift_key'; got {d['toggle']!r}"


# ── 2. Selection spec round-trip ──────────────────────────────────────────


def test_selection_point_spec_roundtrip():
    """selection_point spec dict must contain all expected keys and values survive
    JSON round-trip without silent drops."""
    sel = selection_point(
        fields=["category", "region"],
        encodings=["X", "Color"],
        nearest=True,
        toggle="event.shiftKey",
        on="mouseover",
        clear="mouseout",
        resolve="union",
        name="rt_sel",
    )
    d = sel.to_spec_dict()
    assert d["type"] == "point"
    assert d["name"] == "rt_sel"
    assert d["nearest"] is True
    assert d["resolve"] == "union"
    assert d["fields"] == ["category", "region"]
    assert d["encodings"] == ["x", "color"]  # lowered
    # JSON round-trip
    j = json.dumps(d)
    d2 = json.loads(j)
    assert d2["fields"] == ["category", "region"]
    assert d2["nearest"] is True


def test_selection_interval_spec_roundtrip():
    """selection_interval spec dict must contain all expected keys."""
    mark = SelectionMark(fill="#ff0000", stroke="#00ff00", fill_opacity=0.5, stroke_dash=[4, 2])
    sel = selection_interval(
        fields=["x_field"],
        encodings=["X"],
        translate=False,
        zoom=False,
        mark=mark,
        resolve="intersect",
        name="ri_sel",
    )
    d = sel.to_spec_dict()
    assert d["type"] == "interval"
    assert d["translate"] is False
    assert d["zoom"] is False
    assert d["resolve"] == "intersect"
    assert "mark" in d
    assert d["mark"]["fill_opacity"] == 0.5
    assert d["mark"]["stroke_dash"] == [4, 2]
    assert d["mark"]["fill"]["r"] == 255
    assert d["mark"]["stroke"]["g"] == 255


# ── 3. ConditionalSpec construction and validation ───────────────────────


def test_conditional_spec_when_otherwise_produces_conditional():
    """sel.when(Color('x')).otherwise(value('#ccc')) must produce a ConditionalSpec."""
    sel = selection_point(name="c_sel")
    cond = sel.when(fm.Color("x")).otherwise(value("#cccccc"))
    assert isinstance(cond, ConditionalSpec)
    assert cond.selection_name == "c_sel"


def test_conditional_spec_to_spec_dict_color_channel():
    """ConditionalSpec.to_spec_dict must produce channel='color' for Color encoding."""
    sel = selection_point(name="csd_sel")
    cond = sel.when(fm.Color("cat")).otherwise(value("#aabbcc"))
    d = cond.to_spec_dict()
    assert d["channel"] == "color"
    assert d["selection_name"] == "csd_sel"
    assert d["if_selected"]["kind"] == "field"
    assert d["if_not"]["kind"] == "color"


def test_conditional_spec_to_spec_dict_opacity_channel():
    """ConditionalSpec must resolve Opacity encoding to channel='opacity'."""
    sel = selection_point(name="op_sel")
    cond = sel.when(fm.Opacity("density")).otherwise(value(0.1))
    d = cond.to_spec_dict()
    assert d["channel"] == "opacity"
    assert d["if_not"]["kind"] == "opacity"
    assert abs(d["if_not"]["value"] - 0.1) < 1e-10


def test_conditional_spec_to_spec_dict_size_channel():
    """ConditionalSpec must resolve Size encoding to channel='size'."""
    sel = selection_point(name="sz_sel")
    cond = sel.when(fm.Size("weight")).otherwise(value(0.5))
    d = cond.to_spec_dict()
    assert d["channel"] == "size"


def test_resolve_encoding_value_invalid_type_raises():
    """_resolve_encoding_value must raise TypeError for unsupported types."""
    with pytest.raises(TypeError, match="conditional encoding value"):
        _resolve_encoding_value(42)


def test_resolve_encoding_value_literal_non_color_string():
    """_LiteralValue with a non-color string should fall back to opacity kind."""
    result = _resolve_encoding_value(_LiteralValue("not_a_color"))
    assert result["kind"] == "opacity"
    assert result["value"] == 1.0


# ── 4. Chart.conditional() with non-existent selection raises ────────────


def test_conditional_without_add_selection_raises():
    """Chart.conditional() must raise ValueError when the selection truly is
    not available — i.e. the spec carries no source Selection and none is
    registered. (When the spec carries its source Selection, as it does from
    ``sel.when(...).otherwise(...)``, conditional() auto-registers it.)"""
    df = _small_df()
    # Build a spec with no carried selection to exercise the unavailable path.
    cond = ConditionalSpec(
        selection_name="absent_sel",
        if_selected=fm.Color("g"),
        if_not=value("#ccc"),
    )
    chart = fm.Chart(df).mark_point().encode(x="x:Q", y="y:Q").properties(width=200, height=200)
    with pytest.raises(ValueError, match="no selection named"):
        chart.conditional(cond)


# ── 5. Auto-injection of selection fields into tooltips ──────────────────


def test_auto_injection_does_not_duplicate_existing_tooltip_field():
    """If the tooltip already contains the selection field, auto-injection
    must not add it again."""
    df = _small_df()
    sel = selection_point(fields=["g"], name="dup_sel")
    chart = (
        fm.Chart(df)
        .mark_point()
        .encode(x="x:Q", y="y:Q", tooltip="g:N")
        .add_selection(sel)
        .properties(width=200, height=200)
    )
    json_str, _ = _render(chart)
    scene = json.loads(json_str)
    panel = scene["panels"][0]
    for batch in panel["marks"]:
        tooltips = batch.get("tooltips")
        if tooltips is not None and len(tooltips) > 0:
            field_names = [f["name"] for f in tooltips[0].get("fields", [])]
            g_count = field_names.count("g")
            assert g_count == 1, (
                f"field 'g' must appear exactly once in tooltips; got {g_count} times: {field_names}"
            )
            return
    pytest.fail("no tooltips found in mark batches")


def test_auto_injection_with_multi_field_tooltip():
    """Selection fields auto-injected alongside explicit multi-field tooltip
    must produce union of all fields without duplicates."""
    df = pl.DataFrame({"x": [1.0, 2.0], "y": [3.0, 4.0], "g": ["a", "b"], "h": ["c", "d"]})
    sel = selection_point(fields=["g", "h"], name="mf_sel")
    chart = (
        fm.Chart(df)
        .mark_point()
        .encode(x="x:Q", y="y:Q", tooltip=fm.Tooltip("x"))
        .add_selection(sel)
        .properties(width=200, height=200)
    )
    json_str, _ = _render(chart)
    scene = json.loads(json_str)
    panel = scene["panels"][0]
    for batch in panel["marks"]:
        tooltips = batch.get("tooltips")
        if tooltips is not None and len(tooltips) > 0:
            field_names = {f["name"] for f in tooltips[0].get("fields", [])}
            assert "g" in field_names, "auto-injected field 'g' must be in tooltips"
            assert "h" in field_names, "auto-injected field 'h' must be in tooltips"
            assert "x" in field_names, "explicit tooltip field 'x' must be in tooltips"
            return
    pytest.fail("no tooltips found in mark batches")


# ── 6. Composition-level selection propagation ───────────────────────────


def test_layer_add_preserves_both_point_and_interval():
    """Chart.__add__ must preserve both a point selection from LHS and an
    interval selection from RHS."""
    df = _small_df()
    sel_pt = selection_point(fields=["g"], name="lhs_pt")
    sel_iv = selection_interval(name="rhs_iv")

    lhs = (
        fm.Chart(df)
        .mark_point()
        .encode(x="x:Q", y="y:Q")
        .add_selection(sel_pt)
        .properties(width=200, height=200)
    )
    rhs = (
        fm.Chart(df)
        .mark_line()
        .encode(x="x:Q", y="y:Q")
        .add_selection(sel_iv)
        .properties(width=200, height=200)
    )
    merged = lhs + rhs
    sel_names = {s.name for s in merged._selections}
    assert "lhs_pt" in sel_names, f"LHS point selection missing; got {sel_names}"
    assert "rhs_iv" in sel_names, f"RHS interval selection missing; got {sel_names}"


def test_layer_add_deduplicates_same_name_selection():
    """If LHS and RHS have a selection with the same name, the merged chart
    must contain it only once (no duplicates)."""
    df = _small_df()
    sel = selection_point(fields=["g"], name="shared_sel")
    lhs = (
        fm.Chart(df)
        .mark_point()
        .encode(x="x:Q", y="y:Q")
        .add_selection(sel)
        .properties(width=200, height=200)
    )
    rhs = (
        fm.Chart(df)
        .mark_line()
        .encode(x="x:Q", y="y:Q")
        .add_selection(sel)
        .properties(width=200, height=200)
    )
    merged = lhs + rhs
    names = [s.name for s in merged._selections]
    assert names.count("shared_sel") == 1, f"shared_sel must appear once; got {names}"


def test_hconcat_propagates_conditionals_from_both_children():
    """HConcat (|) with conditionals on both children must merge them all into
    the composed scene's interaction.conditionals."""
    df = _small_df()
    sel = selection_point(fields=["g"], name="hc_sel")
    cond = sel.when(fm.Color("g")).otherwise(value("#ccc"))
    left = (
        fm.Chart(df)
        .mark_point()
        .encode(x="x:Q", y="y:Q")
        .add_selection(sel)
        .conditional(cond)
        .properties(width=200, height=200)
    )
    right = (
        fm.Chart(df)
        .mark_bar()
        .encode(x="x:Q", y="y:Q")
        .add_selection(sel)
        .conditional(cond)
        .properties(width=200, height=200)
    )
    composed = left | right
    scene_json, _ = composed._render_interactive()
    scene = json.loads(scene_json)
    conditionals = scene["interaction"]["conditionals"]
    assert len(conditionals) == 2, f"expected 2 conditionals; got {len(conditionals)}"


# ── 7. Empty / single-row DataFrame edge cases ──────────────────────────


def test_single_row_df_with_selection_and_conditional():
    """A single-row DataFrame with selection + conditional must not crash
    and must produce valid scene JSON."""
    df = pl.DataFrame({"x": [42.0], "y": [7.0], "g": ["only"]})
    sel = selection_point(fields=["g"], name="sr_sel")
    cond = sel.when(fm.Color("g")).otherwise(value("#999"))
    chart = (
        fm.Chart(df)
        .mark_point()
        .encode(x="x:Q", y="y:Q")
        .add_selection(sel)
        .conditional(cond)
        .properties(width=200, height=200)
    )
    json_str, _ = _render(chart)
    scene = json.loads(json_str)
    assert "panels" in scene
    assert len(scene["panels"]) >= 1


def test_empty_df_with_conditional_no_crash():  # BUG: ValueError: empty record batch stream
    """An empty DataFrame with selection + conditional must not crash."""
    df = pl.DataFrame(
        {
            "x": pl.Series([], dtype=pl.Float64),
            "y": pl.Series([], dtype=pl.Float64),
            "g": pl.Series([], dtype=pl.Utf8),
        }
    )
    sel = selection_point(fields=["g"], name="em_sel")
    cond = sel.when(fm.Color("g")).otherwise(value("#aaa"))
    chart = (
        fm.Chart(df)
        .mark_point()
        .encode(x="x:Q", y="y:Q")
        .add_selection(sel)
        .conditional(cond)
        .properties(width=200, height=200)
    )
    json_str, _ = _render(chart)
    scene = json.loads(json_str)
    assert "panels" in scene


# ── 8. field_value_matches_tooltip via scene structure ───────────────────


def test_numeric_field_values_in_tooltips():
    """Selection fields with numeric values must be serialized correctly
    in tooltips (as strings that can round-trip through the field_value_matches_tooltip
    comparison on the Rust side)."""
    df = pl.DataFrame({"x": [1.0, 2.0], "y": [3.0, 4.0], "score": [99.5, 100.5]})
    sel = selection_point(fields=["score"], name="num_sel")
    chart = (
        fm.Chart(df)
        .mark_point()
        .encode(x="x:Q", y="y:Q")
        .add_selection(sel)
        .properties(width=200, height=200)
    )
    json_str, _ = _render(chart)
    scene = json.loads(json_str)
    panel = scene["panels"][0]
    found_score = False
    for batch in panel["marks"]:
        tooltips = batch.get("tooltips")
        if tooltips is not None:
            for tip in tooltips:
                for f in tip.get("fields", []):
                    if f["name"] == "score":
                        found_score = True
                        # Value must be parseable as float
                        float(f["value"])
    assert found_score, "numeric selection field 'score' must appear in tooltips"


# ── 9. SelectionMark edge cases ─────────────────────────────────────────


def test_selection_mark_default_values():
    """SelectionMark with no arguments must have sensible defaults."""
    m = SelectionMark()
    d = m.to_spec_dict()
    assert d["fill_opacity"] == 0.3
    assert d["stroke_opacity"] == 1.0
    assert d["stroke_width"] == 1.0
    assert "fill" not in d  # None fill not serialized
    assert "stroke" not in d
    assert "stroke_dash" not in d


def test_selection_mark_hex_parsing():
    """SelectionMark hex colours must parse correctly into r/g/b/a dicts."""
    m = SelectionMark(fill="#ff8800", stroke="#00ff0080")
    d = m.to_spec_dict()
    assert d["fill"]["r"] == 255
    assert d["fill"]["g"] == 136
    assert d["fill"]["b"] == 0
    assert d["fill"]["a"] == 255
    assert d["stroke"]["a"] == 128  # 8-char hex includes alpha


# ── 10. Selection with bar marks ────────────────────────────────────────


def test_bar_chart_with_selection_produces_valid_scene():
    """A bar chart with selection and conditional must produce valid scene JSON
    with rect marks that can have conditionals applied."""
    df = pl.DataFrame({"x": ["a", "b", "c"], "y": [10.0, 20.0, 30.0]})
    sel = selection_point(fields=["x"], name="bar_sel")
    cond = sel.when(fm.Color("x")).otherwise(value("#cccccc"))
    chart = (
        fm.Chart(df)
        .mark_bar()
        .encode(x="x:N", y="y:Q")
        .add_selection(sel)
        .conditional(cond)
        .properties(width=200, height=200)
    )
    json_str, _ = _render(chart)
    scene = json.loads(json_str)
    assert "panels" in scene
    # Must have mark batches
    marks = scene["panels"][0]["marks"]
    assert len(marks) >= 1


# ── 11. value() edge cases ──────────────────────────────────────────────


def test_value_with_integer_opacity():
    """value(1) must produce an opacity encoding with value 1.0."""
    v = value(1)
    d = _resolve_encoding_value(v)
    assert d["kind"] == "opacity"
    assert d["value"] == 1.0


def test_value_with_hex_color():
    """value('#ff0000') must produce a color encoding."""
    v = value("#ff0000")
    d = _resolve_encoding_value(v)
    assert d["kind"] == "color"
    assert d["value"]["r"] == 255
    assert d["value"]["g"] == 0


# ── 12. add_selection with no arguments ──────────────────────────────────


def test_add_selection_no_args():
    """add_selection() with no arguments must not crash and produce a chart
    with no selections."""
    df = _small_df()
    chart = (
        fm.Chart(df)
        .mark_point()
        .encode(x="x:Q", y="y:Q")
        .add_selection()
        .properties(width=200, height=200)
    )
    json_str, _ = _render(chart)
    scene = json.loads(json_str)
    selections = scene.get("selections", [])
    assert len(selections) == 0


def test_add_selection_multiple_at_once():
    """add_selection(sel1, sel2, sel3) must register all three selections."""
    df = _small_df()
    s1 = selection_point(name="s1")
    s2 = selection_interval(name="s2")
    s3 = selection_point(name="s3")
    chart = (
        fm.Chart(df)
        .mark_point()
        .encode(x="x:Q", y="y:Q")
        .add_selection(s1, s2, s3)
        .properties(width=200, height=200)
    )
    json_str, _ = _render(chart)
    scene = json.loads(json_str)
    sel_names = {s["name"] for s in scene.get("selections", [])}
    assert sel_names == {"s1", "s2", "s3"}


# ── 13. Selection immutability ──────────────────────────────────────────


def test_selection_is_frozen():
    """Selection dataclass is frozen -- attributes cannot be mutated."""
    sel = selection_point(name="frozen_sel")
    with pytest.raises(AttributeError):
        sel.name = "modified"


def test_conditional_spec_is_frozen():
    """ConditionalSpec dataclass is frozen."""
    sel = selection_point(name="f_sel")
    cond = sel.when(fm.Color("g")).otherwise(value("#ccc"))
    with pytest.raises(AttributeError):
        cond.selection_name = "modified"
