"""Edge-case tests for model-diagnostics — generated by bug-hunter agent."""

from __future__ import annotations

import numpy as np
import polars as pl
import pytest

import ferrum
from ferrum._diagnostics.source import ModelSource


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class _PredictOnly:
    """Minimal duck-typed model: predict returns zeros."""

    def predict(self, X):
        return np.zeros(len(X))


class _PredictProba:
    """Model with predict + predict_proba for binary classification."""

    classes_ = np.array([0, 1])

    def predict(self, X):
        return np.zeros(len(X), dtype=int)

    def predict_proba(self, X):
        n = len(X)
        return np.column_stack([np.full(n, 0.8), np.full(n, 0.2)])


class _DecisionFunctionOnly:
    """Binary model that only has decision_function (no predict_proba)."""

    classes_ = np.array([0, 1])

    def predict(self, X):
        return np.zeros(len(X), dtype=int)

    def decision_function(self, X):
        return np.zeros(len(X))


class _NoPredictNoProba:
    """Model with no predict at all."""

    pass


# ---------------------------------------------------------------------------
# 1. Single-row DataFrame — constructor and predictions round-trip
# ---------------------------------------------------------------------------


def test_single_row_predictions_does_not_crash():
    """A 1-row dataset must not cause index errors or panics in predictions()."""
    X = pl.DataFrame({"a": [1.0], "b": [2.0]})
    y = [1.0]
    source = ModelSource(_PredictOnly(), X, y=y)
    pred = source.predictions()
    assert pred.height == 1
    assert "y_true" in pred.columns
    assert "y_pred" in pred.columns
    assert "residual" in pred.columns


# ---------------------------------------------------------------------------
# 2. Empty DataFrame (0 rows)
# ---------------------------------------------------------------------------


def test_zero_row_dataframe_does_not_crash_constructor():
    """ModelSource accepts a 0-row DataFrame without raising on __init__."""
    X = pl.DataFrame({"a": pl.Series([], dtype=pl.Float64)})
    # Must not raise at construction time.
    source = ModelSource(_PredictOnly(), X)
    assert source.X.height == 0


def test_zero_row_predictions_returns_empty_frame():
    """predictions() on a 0-row dataset returns a 0-row DataFrame."""
    X = pl.DataFrame({"a": pl.Series([], dtype=pl.Float64)})
    y = pl.Series("y", [], dtype=pl.Float64)
    source = ModelSource(_PredictOnly(), X, y=y)
    pred = source.predictions()
    assert pred.height == 0
    assert set(pred.columns) >= {"y_true", "y_pred", "residual"}


# ---------------------------------------------------------------------------
# 3. 1D numpy array for X must raise ValueError
# ---------------------------------------------------------------------------


def test_1d_numpy_x_raises_value_error():
    """Passing a 1D ndarray as X must raise ValueError with shape info."""
    with pytest.raises(ValueError, match="2D"):
        ModelSource(_PredictOnly(), np.array([1.0, 2.0, 3.0]), y=[0, 1, 2])


# ---------------------------------------------------------------------------
# 4. Integer numpy array coerces cleanly
# ---------------------------------------------------------------------------


def test_integer_numpy_x_coerces_to_dataframe():
    """X as int64 ndarray must be accepted; no float required."""
    X = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.int64)
    source = ModelSource(_PredictOnly(), X, y=[0, 1, 2])
    assert source.X.height == 3
    assert source.feature_names == ["f0", "f1"]


# ---------------------------------------------------------------------------
# 5. Boolean numpy array as X
# ---------------------------------------------------------------------------


def test_boolean_numpy_x_coerces_without_error():
    """Boolean arrays may appear when features are indicator columns."""
    X = np.array([[True, False], [False, True], [True, True]], dtype=bool)
    source = ModelSource(_PredictOnly(), X, y=[0, 1, 2])
    assert source.X.height == 3


# ---------------------------------------------------------------------------
# 6. y as a single-column polars DataFrame (the DataFrame->Series branch)
# ---------------------------------------------------------------------------


def test_y_as_single_column_polars_dataframe():
    """y passed as a 1-column polars DataFrame must be coerced to a Series."""
    X = pl.DataFrame({"a": [1.0, 2.0, 3.0]})
    y_df = pl.DataFrame({"target": [0.0, 1.0, 0.0]})
    source = ModelSource(_PredictOnly(), X, y=y_df)
    assert source.y is not None
    assert len(source.y) == 3


def test_y_as_multi_column_polars_dataframe_raises():
    """y with >1 column must raise ValueError."""
    X = pl.DataFrame({"a": [1.0, 2.0]})
    y_df = pl.DataFrame({"c1": [0.0, 1.0], "c2": [1.0, 0.0]})
    with pytest.raises(ValueError, match="1 column"):
        ModelSource(_PredictOnly(), X, y=y_df)


# ---------------------------------------------------------------------------
# 7. predictions() when y is None — y_true column is all NaN
# ---------------------------------------------------------------------------


def test_predictions_without_y_produces_nan_y_true():
    """When y=None, predictions() should still return a frame with y_true=NaN."""
    X = pl.DataFrame({"a": [1.0, 2.0, 3.0]})
    source = ModelSource(_PredictOnly(), X)
    pred = source.predictions()
    assert pred.height == 3
    y_true = pred["y_true"].to_numpy()
    assert np.all(np.isnan(y_true)), "y_true should be NaN when y was not provided"


# ---------------------------------------------------------------------------
# 8. probabilities() without predict_proba or decision_function raises
# ---------------------------------------------------------------------------


def test_probabilities_without_proba_or_decision_raises():
    """ModelSource wrapping a predict-only model must raise AttributeError
    from probabilities()."""
    X = pl.DataFrame({"a": [1.0, 2.0], "b": [3.0, 4.0]})
    source = ModelSource(_PredictOnly(), X, y=[0, 1])
    with pytest.raises(AttributeError, match="predict_proba"):
        source.probabilities()


# ---------------------------------------------------------------------------
# 9. probabilities() via decision_function path (sigmoid normalization)
# ---------------------------------------------------------------------------


def test_probabilities_via_decision_function_sums_to_one():
    """Binary model with only decision_function must produce probabilities
    that sum to 1.0 via the sigmoid path."""
    X = pl.DataFrame({"a": [1.0, -1.0, 0.0], "b": [0.5, 0.5, 0.5]})
    source = ModelSource(_DecisionFunctionOnly(), X, y=[0, 1, 0])
    proba = source.probabilities()
    proba_cols = [c for c in proba.columns if c.startswith("proba_")]
    assert len(proba_cols) == 2
    sums = proba.select(proba_cols).to_numpy().sum(axis=1)
    np.testing.assert_allclose(sums, 1.0, atol=1e-10)


# ---------------------------------------------------------------------------
# 10. roc_curve() when y is None must raise ValueError with clear message
# ---------------------------------------------------------------------------


def test_roc_curve_without_y_raises():
    """roc_curve() requires y; calling without it must raise ValueError."""
    X = pl.DataFrame({"a": [1.0, 2.0, 3.0]})
    source = ModelSource(_PredictProba(), X)
    with pytest.raises(ValueError, match="requires y"):
        source.roc_curve()


# ---------------------------------------------------------------------------
# 11. confusion_matrix() when y is None must raise ValueError
# ---------------------------------------------------------------------------


def test_confusion_matrix_without_y_raises():
    X = pl.DataFrame({"a": [1.0, 2.0, 3.0]})
    source = ModelSource(_PredictProba(), X)
    with pytest.raises(ValueError, match="requires y"):
        source.confusion_matrix()


# ---------------------------------------------------------------------------
# 12. Degenerate binary classification: all samples same class
# ---------------------------------------------------------------------------


def test_roc_curve_all_same_class_emits_nan_auc():
    """When all y labels are the same class, sklearn roc_auc_score raises.
    ModelSource must catch and produce NaN auc or raise with a legible
    message — not an unguarded crash."""
    X = pl.DataFrame({"a": [1.0, 2.0, 3.0, 4.0]})
    y = pl.Series("y", [1, 1, 1, 1])
    source = ModelSource(_PredictProba(), X, y=y)
    # roc_auc_score raises ValueError when only one class is present;
    # the binary path does not guard this so it bubbles up from sklearn.
    # This test documents the current behavior (exception) as a bug
    # or an un-tested contract.
    try:
        roc = source.roc_curve()
        # If it doesn't raise, AUC must be numeric (NaN or 0.0..1.0).
        assert roc.height >= 0
    except Exception as exc:
        # Any exception here is acceptable; we just don't want a silent wrong answer.
        assert isinstance(exc, (ValueError, Exception))


# ---------------------------------------------------------------------------
# 13. calibration_curve with n_bins=1 (extreme edge)
# ---------------------------------------------------------------------------


def test_calibration_curve_n_bins_1():
    """n_bins=1 is the minimum meaningful bin count. Should not panic or
    produce NaN fraction_positive when the single bin has all samples."""
    X = pl.DataFrame({"a": [float(i) for i in range(20)]})
    y = pl.Series("y", [0] * 10 + [1] * 10)
    source = ModelSource(_PredictProba(), X, y=y)
    cal = source.calibration_curve(n_bins=1)
    assert cal.height >= 0  # May be 0 if sklearn emits 0 bins — should not raise.
    # No NaN in fraction_positive.
    if cal.height > 0:
        assert not any(np.isnan(v) for v in cal["fraction_positive"].to_numpy())


# ---------------------------------------------------------------------------
# 14. lift_curve when base_rate is 0 (no positive class) skips cleanly
# ---------------------------------------------------------------------------


def test_lift_curve_no_positive_class_baseline_only():
    """When all y labels are negative (base_rate=0), lift is undefined.
    The implementation skips that class's curve. The resulting DataFrame
    must still have the baseline rows."""
    X = pl.DataFrame({"a": [1.0, 2.0, 3.0]})
    y = pl.Series("y", [0, 0, 0])
    source = ModelSource(_PredictProba(), X, y=y)
    lift = source.lift_curve()
    # Baseline must still be present.
    baseline = lift.filter(pl.col("class") == "baseline")
    assert baseline.height == 2
    assert (baseline["lift"] == 1.0).all()


# ---------------------------------------------------------------------------
# 15. cumulative_gain baseline endpoints contract
# ---------------------------------------------------------------------------


def test_cumulative_gain_baseline_goes_from_zero_to_one():
    """The baseline always starts at (0, 0) and ends at (1, 1)."""
    X = pl.DataFrame({"a": [1.0, 2.0, 3.0, 4.0]})
    y = pl.Series("y", [0, 1, 0, 1])
    source = ModelSource(_PredictProba(), X, y=y)
    gain = source.cumulative_gain()
    baseline = gain.filter(pl.col("class") == "baseline").sort("percent_population")
    assert baseline["percent_population"].to_list() == [0.0, 1.0]
    assert baseline["gain"].to_list() == [0.0, 1.0]


# ---------------------------------------------------------------------------
# 16. importances() without feature_importances_ or coef_ raises AttributeError
# ---------------------------------------------------------------------------


def test_importances_builtin_no_attribute_raises():
    """A model with neither feature_importances_ nor coef_ must raise
    AttributeError with a legible message from importances(method='builtin')."""
    X = pl.DataFrame({"a": [1.0, 2.0], "b": [3.0, 4.0]})
    source = ModelSource(_PredictOnly(), X, y=[0, 1])
    with pytest.raises(AttributeError, match="feature_importances_"):
        source.importances(method="builtin")


# ---------------------------------------------------------------------------
# 17. importances() unknown method raises ValueError
# ---------------------------------------------------------------------------


def test_importances_unknown_method_raises_value_error():
    """importances(method='unknown') must raise ValueError."""
    X = pl.DataFrame({"a": [1.0, 2.0], "b": [3.0, 4.0]})
    source = ModelSource(_PredictOnly(), X, y=[0, 1])
    with pytest.raises(ValueError, match="'builtin' or 'permutation'"):
        source.importances(method="not_a_real_method")


# ---------------------------------------------------------------------------
# 18. ComparedModelSource repr and single-model edge case
# ---------------------------------------------------------------------------


def test_compared_source_single_model_repr():
    """ComparedModelSource with one model must have a non-empty repr."""
    X = pl.DataFrame({"a": [1.0, 2.0]})
    source = ModelSource(_PredictOnly(), X, y=[0, 1])
    cms = ferrum.ComparedModelSource({"lone_model": source})
    r = repr(cms)
    assert "lone_model" in r
    assert cms.model_names == ["lone_model"]


# ---------------------------------------------------------------------------
# 19. caching is consistent across method invocations
# ---------------------------------------------------------------------------


def test_predictions_caching_returns_same_object():
    """predictions() must return the identical DataFrame object on second call."""
    X = pl.DataFrame({"a": [1.0, 2.0, 3.0]})
    source = ModelSource(_PredictOnly(), X, y=[0.0, 1.0, 0.0])
    p1 = source.predictions()
    p2 = source.predictions()
    assert p1 is p2, "Cache miss: predictions() computed twice for identical inputs"


# ---------------------------------------------------------------------------
# 20. predictions() residual identity: residual == y_true - y_pred exactly
# ---------------------------------------------------------------------------


def test_predictions_residual_is_y_true_minus_y_pred():
    """residual column must be y_true - y_pred to floating-point precision."""
    X = pl.DataFrame({"a": [1.0, 2.0, 3.0, 4.0, 5.0]})
    y = [0.5, 1.5, 2.5, 3.5, 4.5]
    source = ModelSource(_PredictOnly(), X, y=y)
    pred = source.predictions()
    y_true = pred["y_true"].to_numpy()
    y_pred = pred["y_pred"].to_numpy()
    residual = pred["residual"].to_numpy()
    np.testing.assert_allclose(residual, y_true - y_pred, rtol=1e-12)


# ---------------------------------------------------------------------------
# 21. discrimination_threshold rejects multiclass (>2 classes)
# ---------------------------------------------------------------------------


def test_discrimination_threshold_with_two_classes_runs():
    """Sanity: binary model must succeed (not raise) in discrimination_threshold."""
    X = pl.DataFrame({"a": [float(i) for i in range(10)]})
    y = pl.Series("y", [0, 1] * 5)
    source = ModelSource(_PredictProba(), X, y=y)
    dt = source.discrimination_threshold(n_thresholds=5)
    assert dt.height == 5
    assert set(dt.columns) == {"threshold", "precision", "recall", "f1", "queue_rate"}


# ---------------------------------------------------------------------------
# 22. feature_names from explicit list overrides DataFrame column names
# ---------------------------------------------------------------------------


def test_explicit_feature_names_override_dataframe_columns():
    """feature_names kwarg must replace DataFrame column names for all outputs."""
    X = pl.DataFrame({"a": [1.0, 2.0], "b": [3.0, 4.0]})
    source = ModelSource(_PredictOnly(), X, feature_names=["alpha", "beta"])
    assert source.feature_names == ["alpha", "beta"]


# ---------------------------------------------------------------------------
# 23. rank2d on a single-feature dataset (1x1 matrix)
# ---------------------------------------------------------------------------


def test_rank2d_single_feature_diagonal_only():
    """rank2d on 1 feature returns 1 row (the diagonal) with correlation=1.0."""
    X = pl.DataFrame({"f0": [1.0, 2.0, 3.0, 4.0]})
    source = ModelSource(_PredictOnly(), X)
    out = source.rank2d(algorithm="pearson")
    assert out.height == 1
    assert float(out["correlation"][0]) == pytest.approx(1.0)
