"""Edge-case tests for the cohesion-campaign encoding/color/band validation surfaces.

Generated by the bug-hunter agent.  Targets the four validation paths the
campaign changed:

1. ``scheme=`` declaration-time validation on Color/Fill/Stroke
   (``ChannelBase._validate`` -> ``ferrum.color._validate_scheme``).
2. ``color.to_hex`` range-based default heuristic (``color.to_hex``).
3. ``deny_unknown_fields`` on transform/encoding/scale wire dicts
   (``ChartSpec.from_json`` round-trip).
4. ``min_band``/``max_band`` deprecated-alias resolution
   (``_configure_mixin._resolve_band_alias``).

Each test names the specific source path it exercises and asserts a concrete
outcome (exception type, warning category, resolved value, exact hex), not just
"no crash".  Tests that document a real defect carry a ``# BUG:`` marker on the
``def`` line.
"""

from __future__ import annotations

import json
import warnings

import polars as pl
import pytest

import ferrum as fm
from ferrum._core import ChartSpec
from ferrum.axis import Axis
from ferrum.configure import AxisConfig


# ===========================================================================
# 1. scheme= declaration-time validation (ChannelBase._validate)
# ===========================================================================

# All channels that honor scheme= and therefore validate it at construction.
_SCHEME_CHANNELS = [fm.Color, fm.Fill, fm.Stroke]
_SCHEME_IDS = ["Color", "Fill", "Stroke"]


@pytest.mark.parametrize("cls", _SCHEME_CHANNELS, ids=_SCHEME_IDS)
def test_valid_registry_scheme_constructs(cls) -> None:
    """A real registry name (``tableau10``) constructs without raising/warning.

    Path: ``ChannelBase._validate`` -> ``color._validate_scheme`` -> registry hit.
    """
    with warnings.catch_warnings():
        warnings.simplefilter("error")  # any warning would fail the test
        ch = cls("species", scheme="tableau10")
    assert ch.option("scheme") == "tableau10"


@pytest.mark.parametrize("cls", _SCHEME_CHANNELS, ids=_SCHEME_IDS)
def test_bogus_scheme_raises_at_construction(cls) -> None:
    """A bogus scheme name raises ValueError at DECLARATION, not at render.

    Path: ``color._validate_scheme`` -> ``_palette_kind(name) is None``.
    """
    with pytest.raises(ValueError, match="Unknown palette"):
        cls("f", scheme="definitely_not_a_palette")


@pytest.mark.parametrize("cls", _SCHEME_CHANNELS, ids=_SCHEME_IDS)
def test_bogus_scheme_message_is_helpful(cls) -> None:
    """The error names the channel context AND lists available palettes.

    Path: ``_validate_scheme`` prepends ``"<Cls>(scheme=...)"`` to the canonical
    ``_unknown_palette_error`` body (which embeds the sorted registry).
    """
    with pytest.raises(ValueError) as exc:
        cls("f", scheme="zzz")
    msg = str(exc.value)
    assert msg.startswith(f"{cls.__name__}(scheme=...)"), msg
    assert "Available:" in msg
    assert "tableau10" in msg  # a real palette appears in the suggestion list


def test_scheme_validation_is_identical_across_color_fill_stroke() -> None:
    """Color/Fill/Stroke produce byte-identical message BODIES (only prefix differs).

    Path: all three route through the single ``_validate_scheme`` helper, so the
    ``Unknown palette: 'x'. Available: ...`` body must be identical.
    """
    bodies = []
    for cls in _SCHEME_CHANNELS:
        with pytest.raises(ValueError) as exc:
            cls("f", scheme="xyzzy")
        # Strip the channel-context prefix "<Cls>(scheme=...): "
        bodies.append(str(exc.value).split(": ", 1)[1])
    assert bodies[0] == bodies[1] == bodies[2], bodies


@pytest.mark.parametrize("cls", _SCHEME_CHANNELS, ids=_SCHEME_IDS)
def test_scheme_none_does_not_validate(cls) -> None:
    """``scheme=None`` is the unset default and must construct silently.

    Path: ``_validate`` guard ``scheme is not None`` short-circuits.
    """
    ch = cls("f", scheme=None)
    assert ch.option("scheme") is None


@pytest.mark.parametrize("cls", _SCHEME_CHANNELS, ids=_SCHEME_IDS)
def test_scheme_empty_string_raises(cls) -> None:
    """``scheme=""`` is non-None and not a palette, so it must raise (not pass through).

    Path: ``_validate`` passes ``""`` to ``_validate_scheme`` (``"" is not None``),
    which rejects it as an unknown palette.  Pins that the empty string is treated
    as a real (bogus) value, not as "unset".
    """
    with pytest.raises(ValueError, match="Unknown palette: ''"):
        cls("f", scheme="")


def test_scheme_accepts_continuous_palette_for_categorical_channel() -> None:
    """A continuous palette name (``viridis``) is accepted as a Color scheme.

    Path: ``_validate_scheme`` checks membership only, not kind.  This pins that
    declaration-time validation is intentionally KIND-AGNOSTIC (a sequential
    palette on a categorical color channel is not rejected here).
    """
    ch = fm.Color("f", scheme="viridis")  # sequential palette, categorical channel
    assert ch.option("scheme") == "viridis"


def test_scheme_on_non_color_channel_is_not_validated() -> None:
    """``scheme=`` on a channel that does NOT honor it skips validation entirely.

    Path: ``_validate`` gates validation on ``"scheme" in self._honored_kwargs``.
    ``Opacity`` does not honor scheme, so a bogus name is warn-dropped, NOT raised.
    Pins the channel-dependence of scheme validation (an asymmetry by design).
    """
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        fm.Opacity("f", scheme="definitely_not_a_palette")  # must NOT raise
    # It is dropped with a "not honored" warning rather than validated.
    assert any("scheme" in str(w.message) for w in caught)


# ===========================================================================
# 2. color.to_hex range-based default heuristic
# ===========================================================================


def test_to_hex_int_one_is_unit_under_new_heuristic() -> None:
    """``(1, 0, 0)`` integer maps to pure red under the range-based default.

    Path: ``to_hex`` scale=None branch: ``max(r,g,b)=1`` is NOT > 1, so unit
    interpretation -> ``round(1*255)=255`` -> ``#ff0000``.  This is the campaign's
    behavior change (1 and 1.0 now agree).
    """
    assert fm.color.to_hex((1, 0, 0)) == "#ff0000"


def test_to_hex_byte_scale_recovers_old_behavior() -> None:
    """``scale="byte"`` on ``(1, 0, 0)`` recovers the OLD near-black mapping.

    Path: ``to_hex`` explicit byte branch: ``int(1)=1`` -> ``#010000``.  The
    campaign documents ``scale="byte"`` as the escape hatch for the old behavior.
    """
    assert fm.color.to_hex((1, 0, 0), scale="byte") == "#010000"


def test_to_hex_255_is_byte_under_new_heuristic() -> None:
    """``(255, 0, 0)`` maps to pure red (byte inferred from the >1 component)."""
    assert fm.color.to_hex((255, 0, 0)) == "#ff0000"


def test_to_hex_unit_overshoot_uses_byte_interpretation_current_behavior() -> None:
    """A near-white unit tuple ``(0.9, 0.9, 1.1)`` is interpreted as BYTE by the heuristic.

    Characterization of the T2.2#3 range-based default; the (0.9, 0.9, 1.1) ->
    near-black overshoot edge is flagged for user ratification, not a fixed contract.

    Path: ``to_hex`` scale=None branch.  ``max=1.1 > 1`` triggers BYTE mode for
    *all* three components: ``int(0.9)=0``, ``int(0.9)=0``, ``int(1.1)=1`` -> ``#000001``.
    This is the current behavior under ``color.py:190``'s heuristic
    (``scale = "byte" if max(r,g,b) > 1 else "unit"``).

    The explicit ``scale="unit"`` escape hatch recovers the near-white reading
    ``#e6e6ff``, proving the behavior is recoverable and the intended color is
    reachable — the heuristic just doesn't choose it for floating-point overshoots.
    """
    # Current heuristic: any component > 1 forces byte interpretation for all components.
    heuristic_result = fm.color.to_hex((0.9, 0.9, 1.1))
    assert heuristic_result == "#000001"

    # The explicit escape hatch recovers the near-white intended color.
    explicit_unit = fm.color.to_hex((0.9, 0.9, 1.1), scale="unit")
    assert explicit_unit == "#e6e6ff"


def test_to_hex_unit_scale_clamps_out_of_range() -> None:
    """Explicit ``scale="unit"`` clamps out-of-range components to [0, 255].

    Path: ``to_hex`` unit branch then ``max(0, min(255, ...))`` clamp.
    ``(-0.1, 1.5, 0.5)`` -> ``#0080... `` with the negative clamped to 0 and the
    over-1 clamped to ff.
    """
    assert fm.color.to_hex((-0.1, 1.5, 0.5), scale="unit") == "#00ff80"


def test_to_hex_byte_scale_clamps_out_of_range() -> None:
    """Explicit ``scale="byte"`` clamps ``256`` down to ``255`` and negatives to 0.

    Path: ``to_hex`` byte branch then clamp.  ``(256, -3, 128)`` -> ``#ff0080``.
    """
    assert fm.color.to_hex((256, -3, 128), scale="byte") == "#ff0080"


def test_to_hex_invalid_scale_keyword_raises() -> None:
    """A scale keyword other than unit/byte/None raises ValueError with the value.

    Path: ``to_hex`` guard ``scale not in (None, "unit", "byte")``.
    """
    with pytest.raises(ValueError, match="scale must be 'unit', 'byte', or None"):
        fm.color.to_hex((1, 0, 0), scale="UNIT")  # case-sensitive


def test_to_hex_short_tuple_raises() -> None:
    """A 2-tuple is rejected (len < 3) instead of indexing out of bounds.

    Path: ``to_hex`` guard ``len(color) < 3``.
    """
    with pytest.raises(ValueError, match="Expected an RGB tuple"):
        fm.color.to_hex((1, 0))


def test_to_hex_non_hex_string_raises() -> None:
    """A non-``#`` string is rejected with a legible message.

    Path: ``to_hex`` string branch ``not s.startswith("#")``.
    """
    with pytest.raises(ValueError, match="must be hex format"):
        fm.color.to_hex("rgb(1,0,0)")


def test_to_hex_bool_components_treated_as_ints() -> None:
    """``bool`` components (``True``/``False``) ride the int path; max=1 -> unit.

    Path: ``to_hex`` scale=None branch.  ``True==1`` (not > 1) -> unit ->
    ``round(1*255)=255`` -> ``#ff0000``.  Pins that boolean RGB does not crash and
    does not silently become near-black under the heuristic.
    """
    assert fm.color.to_hex((True, False, False)) == "#ff0000"


# ===========================================================================
# 3. deny_unknown_fields on the wire round-trip (ChartSpec.from_json)
# ===========================================================================


def _base_spec_json() -> dict:
    return json.loads(ChartSpec(mark="point", x="a", y="b").to_json())


def test_transform_typo_key_is_rejected() -> None:
    """A misspelled transform field raises ValueError (deny_unknown_fields ON).

    Path: ``crates/.../transform/*.rs`` structs carry ``#[serde(deny_unknown_fields)]``.
    A ``predicat`` typo on a filter transform must surface as an ``unknown field``
    error, NOT a silent drop.
    """
    df = pl.DataFrame({"a": [1.0, 2.0, 3.0], "b": [4.0, 5.0, 6.0]})
    base = fm.Chart(df).transform(fm.transform_filter("a > 1")).mark_point().encode(x="a", y="b")
    j = json.loads(base.to_spec().to_json())
    j["transforms"][0]["predicat"] = "a > 1"  # typo of "predicate"
    with pytest.raises(ValueError, match="unknown field"):
        ChartSpec.from_json(json.dumps(j))


def test_unknown_transform_variant_is_rejected() -> None:
    """An unknown transform ``type`` value raises (tagged-enum variant guard).

    Path: serde tagged-enum deserialise on the transform list.  ``"flilter"`` is
    not a known variant.
    """
    df = pl.DataFrame({"a": [1.0, 2.0, 3.0], "b": [4.0, 5.0, 6.0]})
    base = fm.Chart(df).transform(fm.transform_filter("a > 1")).mark_point().encode(x="a", y="b")
    j = json.loads(base.to_spec().to_json())
    j["transforms"][0]["type"] = "flilter"
    with pytest.raises(ValueError, match="unknown variant"):
        ChartSpec.from_json(json.dumps(j))


def test_per_channel_axis_style_typo_is_rejected() -> None:
    """A misspelled per-channel ``axis`` style key raises (AxisStyleSpec guards it).

    Path: ``EncodingSpec.axis`` is typed against ``AxisStyleSpec`` which has
    ``#[serde(deny_unknown_fields)]``.  ``labl_angle`` must fail loud.
    """
    df = pl.DataFrame({"a": [1.0, 2.0, 3.0], "b": [4.0, 5.0, 6.0]})
    base = fm.Chart(df).mark_point().encode(x=fm.X("a", axis=fm.Axis(label_angle=10)), y="b")
    j = json.loads(base.to_spec().to_json())
    j["encoding"]["x"]["axis"]["labl_angle"] = 20  # typo of label_angle
    with pytest.raises(ValueError, match="unknown field"):
        ChartSpec.from_json(json.dumps(j))


def test_encoding_channel_typo_key_is_rejected() -> None:
    """A misspelled encoding-channel key (``typ``) raises, not silently dropped.

    Path: ``EncodingSpec`` (spec/encoding.rs) carries struct-level
    ``#[serde(deny_unknown_fields)]`` (S4FIX2), so ``{"field": "a", "typ": "Q"}``
    (typo of ``type``) fails loud as an ``unknown field`` error rather than
    dropping the intended type.  Completes the no-silent-drop seam so the
    channel-key path matches the per-channel axis-style path above.
    """
    j = _base_spec_json()
    j["encoding"]["x"]["typ"] = "Q"  # typo of the "type" wire key
    with pytest.raises(ValueError, match="unknown field"):
        ChartSpec.from_json(json.dumps(j))


def test_scale_dict_typo_key_is_tolerated_documented_exception() -> None:
    """A misspelled scale key (``clammp``) is TOLERATED (documented exception).

    Path: ``ScaleSpec`` deserialise.  Unlike ``EncodingSpec``/``ChartSpec``,
    ``ScaleSpec`` is an internally-tagged enum whose every continuous variant
    embeds ``ContinuousScaleCommon`` via ``#[serde(flatten)]``.  serde cannot
    enforce ``deny_unknown_fields`` through a flattened / internally-tagged shape,
    so a ``clammp`` typo (of ``clamp``) inside a ``scale`` sub-dict is accepted
    and silently dropped.  This is a structural serde constraint, documented on
    the ``ScaleSpec`` doc comment — NOT a fail-loud surface.  This test pins that
    tolerated-drop so a future "fix" that breaks the round-trip is caught.
    """
    df = pl.DataFrame({"a": [1.0, 2.0, 3.0], "b": [4.0, 5.0, 6.0]})
    base = fm.Chart(df).mark_point().encode(x=fm.X("a", scale=fm.LinearScale()), y="b")
    j = json.loads(base.to_spec().to_json())
    j["encoding"]["x"]["scale"]["clammp"] = True  # typo of clamp
    # Tolerated: the flattened ScaleSpec cannot deny, so this round-trips and the
    # typo'd key is dropped (no error).
    spec = ChartSpec.from_json(json.dumps(j))
    round_tripped = json.loads(spec.to_json())
    assert "clammp" not in round_tripped["encoding"]["x"]["scale"]


def test_top_level_chartspec_typo_key_is_rejected() -> None:
    """A misspelled top-level ChartSpec key (``marrk``) raises, not dropped.

    Path: top-level ``ChartSpec`` carries ``#[serde(deny_unknown_fields)]``
    (S4FIX2), so a ``marrk`` typo (of ``mark``) fails loud as an ``unknown
    field`` error rather than being silently dropped.
    """
    j = _base_spec_json()
    j["marrk"] = "point"  # typo of "mark"; the real "mark" stays "point"
    with pytest.raises(ValueError, match="unknown field"):
        ChartSpec.from_json(json.dumps(j))


# ===========================================================================
# 4. min_band/max_band alias resolution — VALUE edges (type, negative, zero)
#    (The cross-surface warn/raise/None edges are covered by
#     tests/test_cohesion_band_alias_and_primitive_marks.py; here we probe the
#     numeric value-domain edges that file does not exercise.)
# ===========================================================================

_BAND_SURFACES = [
    ("Axis", lambda **kw: Axis(**kw)),
    ("AxisConfig", lambda **kw: AxisConfig(**kw)),
]
_BAND_IDS = ["Axis", "AxisConfig"]


@pytest.mark.parametrize("label,build", _BAND_SURFACES, ids=_BAND_IDS)
@pytest.mark.parametrize("bound", ["min", "max"])
def test_band_zero_is_preserved_not_treated_as_unset(label, build, bound) -> None:  # noqa: ARG001
    """``<bound>_band=0`` (falsy but supplied) must survive as ``0``, not vanish.

    Path: ``_resolve_band_alias`` returns ``canonical_value`` when no alias is
    given; ``0`` is a legitimate band bound.  A naive ``if value:`` truthiness
    check would drop it.  Also confirms ``to_dict`` keeps it (no default filtering
    for band fields).
    """
    obj = build(**{f"{bound}_band": 0})
    assert getattr(obj, f"{bound}_band") == 0
    assert obj.to_dict().get(f"{bound}_band") == 0


@pytest.mark.parametrize("label,build", _BAND_SURFACES, ids=_BAND_IDS)
@pytest.mark.parametrize("bound", ["min", "max"])
def test_band_negative_value_passes_through(label, build, bound) -> None:  # noqa: ARG001
    """A negative band value is accepted at the Python layer (no validation gate).

    Path: ``_resolve_band_alias`` does not range-check; pins that the Python
    surface forwards ``-5`` verbatim (the renderer, not the value class, owns any
    sign policy).  This documents the *absence* of a Python-side guard.
    """
    obj = build(**{f"{bound}_band": -5.0})
    assert getattr(obj, f"{bound}_band") == -5.0


@pytest.mark.parametrize("label,build", _BAND_SURFACES, ids=_BAND_IDS)
@pytest.mark.parametrize("bound", ["min", "max"])
def test_band_non_number_alias_passes_through_untyped(label, build, bound) -> None:
    """A non-number band ALIAS value rides through resolution unchecked + warns.

    Path: ``_resolve_band_alias`` only checks the ``_MISSING`` sentinel and the
    double-supply conflict — it does NOT type-check the value.  A string passed
    under the deprecated alias warns (deprecation) and lands on the canonical
    field verbatim.  Pins that the resolver is value-agnostic (defers typing to
    serialization/Rust), which is a latent footgun worth documenting.
    """
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        obj = build(**{f"{bound}_extent": "not_a_number"})
    dep = [w for w in caught if issubclass(w.category, DeprecationWarning)]
    assert dep, f"{label}: alias supply must warn even for a bad value"
    assert getattr(obj, f"{bound}_band") == "not_a_number"


def test_band_alias_double_supply_raises_typeerror_not_valueerror() -> None:
    """Double-supply raises ``TypeError`` (not ValueError) — pin the exact type.

    Path: ``_resolve_band_alias`` raises ``TypeError`` when both canonical and
    alias are present.  Callers that ``except ValueError`` must NOT swallow this.
    """
    with pytest.raises(TypeError):
        Axis(min_band=5, min_extent=7)
    with pytest.raises(TypeError):
        AxisConfig(max_band=5, max_extent=7)
