"""Edge-case tests for the reactive-parameter / selection / conditional system (D6).

Generated by the bug-hunter agent. Targets the STATIC resolution and
serialization layer that runs without a browser:

- fm.param(value=) static domain substitution (numeric / string / bool / list)
- fm.when(...).then(...).otherwise(...) static resolution to the default branch
- scale={"domain": param} (domainParam) static rescale + degenerate domains
- transform_filter(param) crossfilter static contract (all rows kept)
- add_params dedup, name collisions, orphan params, wrong-typed args
- param -> spec -> from_json round-trip stability

Each test names the source code path it exercises. Tests proving a bug carry a
``# BUG:`` marker on the def line.
"""

from __future__ import annotations

import json
import math
import re

import polars as pl
import pytest

import ferrum as fm
from ferrum._core import ChartSpec
from ferrum.selection import _resolve_encoding_value, value


def _df() -> pl.DataFrame:
    return pl.DataFrame({"t": [10, 20, 30], "a": [1, 2, 3], "c": ["x", "y", "x"]})


def _params_of(spec) -> list:
    d = json.loads(spec.to_json())
    raw = d.get("params")
    if raw is None:
        return []
    if isinstance(raw, str):
        return json.loads(raw)
    return raw


def _cx(svg: str) -> list[float]:
    return [float(m) for m in re.findall(r'cx="([0-9.eE+-]+)"', svg)]


# ─────────────────────────────────────────────────────────────────────────────
# Static domainParam substitution — numeric / type-boundary value kinds
#   source: crates/ferrum-core/src/spec/parameter.rs ParamStore.numeric_domain
#           crates/ferrum-core/src/render/scene_build.rs resolve_param_domains
#           src/ferrum/encoding/_scale.py _scale_to_dict
# ─────────────────────────────────────────────────────────────────────────────


class TestDomainParamValueKinds:
    def test_numeric_array_domain_constrains_axis(self):
        """[0,100] domain param: t=30 sits well left of the right edge."""
        df = _df()
        a = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=[0, 100])}), y=fm.Y("a"))
        )
        b = fm.Chart(df).mark_point().encode(x=fm.X("t"), y=fm.Y("a"))
        cx_a, cx_b = _cx(a.to_svg()), _cx(b.to_svg())
        assert cx_a and cx_b
        assert max(cx_a) < max(cx_b)

    def test_string_value_falls_back_to_auto_infer(self):
        """A non-array string value → numeric_domain None → auto-infer; no NaN."""
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value="hello")}), y=fm.Y("a"))
        )
        svg = c.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_bool_value_falls_back_to_auto_infer(self):
        """A bool scalar value → numeric_domain None → auto-infer; no NaN."""
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=True)}), y=fm.Y("a"))
        )
        svg = c.to_svg()
        assert "<svg" in svg and "NaN" not in svg

    def test_scalar_numeric_value_falls_back_to_auto_infer(self):
        """A scalar (non-array) numeric value is not a domain → auto-infer."""
        df = _df()
        forced = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=50)}), y=fm.Y("a"))
        )
        auto = fm.Chart(df).mark_point().encode(x=fm.X("t"), y=fm.Y("a"))
        # scalar value must NOT be treated as a domain; should match auto-infer.
        assert _cx(forced.to_svg()) == _cx(auto.to_svg())

    def test_single_element_array_falls_back(self):
        """A 1-element array (< 2) → numeric_domain None → auto-infer; no NaN."""
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=[42])}), y=fm.Y("a"))
        )
        svg = c.to_svg()
        assert "<svg" in svg and "NaN" not in svg

    def test_string_list_domain_no_nan(self):
        """A list of strings as a continuous domain must not produce NaN coords."""
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=["a", "b"])}), y=fm.Y("a"))
        )
        svg = c.to_svg()
        assert "<svg" in svg and "NaN" not in svg


class TestDomainParamDegenerate:
    def test_reversed_domain_renders_descending(self):
        """domain=[100,0] (hi<lo) must render without NaN (descending axis)."""
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=[100, 0])}), y=fm.Y("a"))
        )
        svg = c.to_svg()
        assert "NaN" not in svg
        assert _cx(svg)

    def test_collapsed_domain_no_nan(self):
        """domain=[5,5] (zero width) must not divide-by-zero into NaN coords."""
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=[5, 5])}), y=fm.Y("a"))
        )
        svg = c.to_svg()
        assert "NaN" not in svg
        assert "<svg" in svg

    def test_huge_float_domain_no_nan(self):
        """domain=[0,1e300] must not overflow to NaN/Infinity in coords."""
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=[0, 1e300])}), y=fm.Y("a"))
        )
        svg = c.to_svg()
        assert "NaN" not in svg
        assert "Infinity" not in svg

    def test_single_row_df_with_domain_param(self):
        """A 1-row DataFrame with a forced domain renders without NaN."""
        df = pl.DataFrame({"t": [10], "a": [1]})
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=[0, 100])}), y=fm.Y("a"))
        )
        svg = c.to_svg()
        assert "<svg" in svg and "NaN" not in svg

    def test_color_channel_domain_param_substituted(self):
        """domainParam on the color channel is in the resolve set; renders clean."""
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(
                x=fm.X("t"),
                y=fm.Y("a"),
                color=fm.Color("a", scale={"domain": fm.param("cd", value=[0, 1000])}),
            )
        )
        svg = c.to_svg()
        assert "<svg" in svg and "NaN" not in svg


class TestDomainParamInfNaN:
    # BUG: fm.param(value=[0, inf]) used as a scale domain raises a cryptic
    # low-level serde error ("params: expected value at line 1 column N")
    # because json.dumps emits the non-JSON token `Infinity`, which the Rust
    # serde_json deserializer rejects. The user gets no legible ferrum-level
    # diagnostic about an invalid domain bound.  Source: chart.py to_spec ->
    # json.dumps(params) ; crates/ferrum-core/src/spec/chart.rs new() params parse.
    def test_infinity_in_domain_param_gives_legible_error(self):
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=[0, math.inf])}), y=fm.Y("a"))
        )
        # We expect EITHER a clean render (inf clamped/ignored) OR a legible
        # ferrum error that names the parameter / domain. A raw serde
        # "expected value at line 1 column N" is neither.
        try:
            svg = c.to_svg()
        except Exception as exc:  # noqa: BLE001
            msg = str(exc)
            assert "expected value at line" not in msg, (
                f"Infinity domain bound surfaced as a raw serde parse error "
                f"instead of a legible ferrum diagnostic: {msg!r}"
            )
        else:
            assert "NaN" not in svg and "Infinity" not in svg

    # BUG: same root cause for NaN — json.dumps emits `NaN`, serde rejects it
    # with an opaque column-offset error rather than a domain-validation message.
    def test_nan_in_domain_param_gives_legible_error(self):
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(
                x=fm.X("t", scale={"domain": fm.param("d", value=[math.nan, 100])}), y=fm.Y("a")
            )
        )
        try:
            svg = c.to_svg()
        except Exception as exc:  # noqa: BLE001
            msg = str(exc)
            assert "expected value at line" not in msg, (
                f"NaN domain bound surfaced as a raw serde parse error instead "
                f"of a legible ferrum diagnostic: {msg!r}"
            )
        else:
            assert "NaN" not in svg


# ─────────────────────────────────────────────────────────────────────────────
# Param collection / dedup — collisions, orphans, wrong types
#   source: src/ferrum/chart.py Chart._collect_params, add_params
# ─────────────────────────────────────────────────────────────────────────────


class TestParamCollection:
    # BUG: a Selection and a VariableParameter sharing a name silently drop the
    # variable (first-seen = registered selection wins in _collect_params dedup).
    # When the variable was the source of a scale domainParam, the forced domain
    # value [0,100] is lost and the axis silently auto-infers a *different*
    # domain, corrupting the chart with no warning.
    # Source: chart.py _collect_params (selections iterated before _params /
    # domain refs; dedup by name keeps first-seen).
    # FIX: ferrum now raises ValueError on cross-kind name collision so the user
    # is told explicitly to rename one of the two objects.
    def test_selection_must_not_silently_shadow_domain_variable(self):
        df = _df()
        sel = fm.selection_interval(name="dup")
        chart = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("dup", value=[0, 100])}), y=fm.Y("a"))
            .add_selection(sel)
        )
        # A cross-kind collision (Selection + VariableParameter sharing "dup")
        # must raise ValueError at serialization time — never silently diverge.
        with pytest.raises(ValueError, match="collision"):
            chart.to_svg()

    # BUG: add_params with a non-Parameter argument (e.g. a typo'd string or a
    # raw dict) is silently dropped by _collect_params' isinstance(p, Parameter)
    # filter. A user passing the wrong thing gets a silent no-op instead of a
    # TypeError.  Source: chart.py _collect_params `_add` guard.
    # FIX: add_params() now raises TypeError immediately at call time when a
    # non-Parameter argument is passed.
    def test_add_params_non_parameter_is_not_silently_dropped(self):
        df = _df()
        # A wrong-typed argument must raise TypeError at add_params() call time.
        with pytest.raises(TypeError, match="Parameter"):
            fm.Chart(df).mark_point().encode(x="t", y="a").add_params("not_a_param")

    def test_duplicate_variable_names_dedup_first_wins(self):
        """Two variables named 'k' → exactly one entry, first value wins."""
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x="t", y="a")
            .add_params(fm.param("k", value=1), fm.param("k", value=2))
        )
        params = _params_of(c.to_spec())
        ks = [p for p in params if p["name"] == "k"]
        assert len(ks) == 1
        assert ks[0]["value"] == 1

    def test_orphan_param_serializes_and_renders(self):
        """A param referenced by no encoding still serializes and renders."""
        df = _df()
        c = fm.Chart(df).mark_point().encode(x="t", y="a").add_params(fm.param("orphan", value=5))
        params = _params_of(c.to_spec())
        assert any(p["name"] == "orphan" for p in params)
        assert "<svg" in c.to_svg()

    def test_multiple_distinct_params(self):
        """Multiple distinct params all appear, none dropped."""
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x="t", y="a")
            .add_params(fm.param("a1", value=1), fm.param("b2", value=2), fm.param("c3", value=3))
        )
        names = {p["name"] for p in _params_of(c.to_spec())}
        assert {"a1", "b2", "c3"} <= names

    def test_dedup_selection_and_domain_same_object(self):
        """A selection used as both a domain ref AND registered appears once."""
        df = _df()
        brush = fm.selection_interval(name="brush")
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": brush}), y=fm.Y("a"))
            .add_selection(brush)
        )
        names = [p["name"] for p in _params_of(c.to_spec())]
        assert names.count("brush") == 1


# ─────────────────────────────────────────────────────────────────────────────
# transform_filter(param) crossfilter — static contract = all rows kept
#   source: src/ferrum/transforms.py transform_filter
#           crates/ferrum-core/src/render/scene_build.rs collect_param_bindings
# ─────────────────────────────────────────────────────────────────────────────


class TestTransformFilterStatic:
    def test_param_filter_keeps_all_rows(self):
        """The documented static contract: a param filter keeps every row."""
        df = _df()
        brush = fm.selection_interval(name="b")
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t"), y=fm.Y("a"))
            .transform(fm.transform_filter(brush))
            .add_selection(brush)
        )
        svg = c.to_svg()
        assert svg.count("<circle") == 3, "param filter must keep all rows statically"

    def test_variable_param_filter_marker(self):
        """transform_filter(VariableParameter) emits a true-predicate + marker."""
        p = fm.param("k", value=3)
        t = fm.transform_filter(p)
        assert t == {"type": "filter", "predicate": "true", "param": "k"}

    def test_param_filter_renders_without_nan(self):
        df = _df()
        brush = fm.selection_interval(name="b")
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t"), y=fm.Y("a"))
            .transform(fm.transform_filter(brush))
            .add_selection(brush)
        )
        assert "NaN" not in c.to_svg()


# ─────────────────────────────────────────────────────────────────────────────
# Conditional encoding — static resolution to the otherwise/default branch
#   source: src/ferrum/selection.py ConditionalSpec / _resolve_encoding_value
#           src/ferrum/chart.py encode() conditional threading
# ─────────────────────────────────────────────────────────────────────────────


class TestConditionalStatic:
    def test_color_conditional_renders_otherwise_branch(self):
        """Static render of a color-conditional encoding (nothing selected).

        Post-FA-15 fix: a Color(field) conditional now builds a categorical legend.
        The data has 3 rows and 2 distinct values in 'c' ("x", "y"), so the SVG
        contains 3 data-mark circles plus 2 legend-symbol circles = 5 total.

        Static marks render in the default mark color; the conditional 'otherwise'
        hue is applied at interactive runtime, not baked into the static SVG.
        """
        df = _df()
        sel = fm.selection_point()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x="t", y="a", color=sel.when(fm.Color("c")).otherwise(value("#cccccc")))
        )
        svg = c.to_svg()
        assert "<svg" in svg
        # 3 data-mark circles + 2 legend-symbol circles (one per distinct "c" value).
        assert svg.count("<circle") == 5

    def test_opacity_conditional_channel_and_kinds(self):
        df = _df()
        sel = fm.selection_point()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x="t", y="a", opacity=fm.when(sel).then(1.0).otherwise(0.15))
        )
        cond = json.loads(c.to_json())["conditionals"][0]
        assert cond["channel"] == "opacity"
        assert cond["if_selected"] == {"kind": "opacity", "value": 1.0}
        assert cond["if_not"] == {"kind": "opacity", "value": 0.15}

    def test_size_conditional_numeric_kinds(self):
        df = _df()
        sel = fm.selection_point()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x="t", y="a", size=fm.when(sel).then(100).otherwise(20))
        )
        cond = json.loads(c.to_json())["conditionals"][0]
        assert cond["channel"] == "size"
        assert cond["if_selected"]["kind"] == "size"

    def test_multiple_conditionals_on_one_chart(self):
        """Two conditionals on distinct channels both serialize, both selections registered."""
        df = _df()
        s1 = fm.selection_point(name="s1")
        s2 = fm.selection_point(name="s2")
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(
                x="t",
                y="a",
                opacity=fm.when(s1).then(1.0).otherwise(0.2),
                size=fm.when(s2).then(80).otherwise(10),
            )
        )
        spec = json.loads(c.to_json())
        chans = {cd["channel"] for cd in spec["conditionals"]}
        assert chans == {"opacity", "size"}
        sel_names = {s["name"] for s in spec["selections"]}
        assert {"s1", "s2"} <= sel_names

    def test_conditional_only_selection_auto_registered(self):
        """A conditional via encode auto-registers its selection (no add_selection)."""
        df = _df()
        sel = fm.selection_point(name="auto")
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x="t", y="a", color=sel.when(fm.Color("c")).otherwise(value("#ccc")))
        )
        sel_names = {s["name"] for s in json.loads(c.to_json())["selections"]}
        assert "auto" in sel_names

    def test_resolve_encoding_value_rejects_raw_scalar(self):
        """A raw int (not value()-wrapped, not a channel) must raise TypeError."""
        with pytest.raises(TypeError, match="channel object"):
            _resolve_encoding_value(42)

    def test_when_rejects_variable_parameter(self):
        """fm.when(VariableParameter) must raise — a variable is not a predicate."""
        vp = fm.param("k", value=3)
        with pytest.raises(TypeError, match="fm.when"):
            fm.when(vp)

    def test_conditional_renders_without_nan(self):
        df = _df()
        sel = fm.selection_point()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x="t", y="a", color=sel.when(fm.Color("c")).otherwise(value("#cccccc")))
        )
        assert "NaN" not in c.to_svg()


# ─────────────────────────────────────────────────────────────────────────────
# Spec round-trips — params survive to_json -> from_json -> to_json
#   source: crates/ferrum-core/src/spec/chart.rs (params serde)
#           crates/ferrum-core/src/spec/encoding.rs (domainParam serde)
# ─────────────────────────────────────────────────────────────────────────────


class TestRoundTrip:
    def test_domain_param_chart_round_trip_stable(self):
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=[0, 100])}), y=fm.Y("a"))
        )
        js = c.to_spec().to_json()
        rt = ChartSpec.from_json(js)
        assert rt.to_json() == js

    def test_domain_param_preserved_in_round_trip(self):
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x=fm.X("t", scale={"domain": fm.param("d", value=[0, 100])}), y=fm.Y("a"))
        )
        js = ChartSpec.from_json(c.to_spec().to_json()).to_json()
        assert "domainParam" in js
        # the variable value survives
        d = json.loads(js)
        params = d["params"]
        if isinstance(params, str):
            params = json.loads(params)
        d_param = next(p for p in params if p["name"] == "d")
        assert d_param["value"] == [0, 100]

    def test_selection_param_round_trip(self):
        df = _df()
        brush = fm.selection_interval(name="brush", encodings=["x"])
        c = fm.Chart(df).mark_point().encode(x=fm.X("t"), y=fm.Y("a")).add_selection(brush)
        js = c.to_spec().to_json()
        assert ChartSpec.from_json(js).to_json() == js

    def test_conditional_round_trip(self):
        df = _df()
        sel = fm.selection_point(name="s")
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x="t", y="a", opacity=fm.when(sel).then(1.0).otherwise(0.2))
        )
        js = c.to_spec().to_json()
        rt = ChartSpec.from_json(js)
        assert rt.to_json() == js

    def test_legend_bind_round_trip(self):
        df = _df()
        c = (
            fm.Chart(df)
            .mark_point()
            .encode(x="t", y="a")
            .add_params(fm.param("lp", value=1, bind="legend"))
        )
        js = c.to_spec().to_json()
        rt_js = ChartSpec.from_json(js).to_json()
        assert rt_js == js
        params = json.loads(rt_js)["params"]
        if isinstance(params, str):
            params = json.loads(params)
        lp = next(p for p in params if p["name"] == "lp")
        assert lp.get("bind") == "legend"

    def test_param_free_chart_omits_params_key(self):
        """Byte-stability: a param-free chart never emits a params key."""
        df = _df()
        js = fm.Chart(df).mark_point().encode(x="t", y="a").to_spec().to_json()
        assert "params" not in js
