"""Edge-case tests for scene-composition -- generated by bug-hunter agent."""

from __future__ import annotations

import json

import polars as pl
import pytest

import ferrum as fm
from ferrum.composition import (
    ConcatChart,
    HConcatChart,
    VConcatChart,
    _empty_scene,
    _merge_child_scenes,
    _merge_child_scenes_grid,
    _merge_packed_data,
    _merge_scene_panels,
    _offset_node,
)
from ferrum._html import _background_css_from_dict
from ferrum._interactive import InteractiveChart, _render_scene
from ferrum.display import _extract_title_text


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _simple_chart(width=200, height=200):
    """Return a minimal chart for composition tests."""
    df = pl.DataFrame({"x": [1.0, 2.0, 3.0], "y": [4.0, 5.0, 6.0]})
    return fm.Chart(df).mark_point().encode(x="x:Q", y="y:Q").properties(width=width, height=height)


# ===========================================================================
# 1. _offset_node: image type (W4 -- node type not handled)
# ===========================================================================


def test_offset_node_image_type():  # BUG: _offset_node ignores image node type -- x/y not shifted
    """_offset_node must offset image node's x and y coordinates."""
    node = {
        "type": "image",
        "x": 10.0,
        "y": 20.0,
        "w": 100.0,
        "h": 80.0,
        "data": {"kind": "url", "url": "http://example.com/img.png"},
    }
    _offset_node(node, 50.0, 30.0)
    assert node["x"] == 60.0, f"image x not offset: expected 60, got {node['x']}"
    assert node["y"] == 50.0, f"image y not offset: expected 50, got {node['y']}"
    # Width and height must NOT change
    assert node["w"] == 100.0
    assert node["h"] == 80.0


# ===========================================================================
# 2. _offset_node: polygon type (W4 -- node type not handled)
# ===========================================================================


def test_offset_node_polygon_type():  # BUG: _offset_node ignores polygon node type -- ring coordinates not shifted
    """_offset_node must offset every coordinate in polygon rings."""
    node = {
        "type": "polygon",
        "rings": [
            [[0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 10.0]],
            [[2.0, 2.0], [8.0, 2.0], [8.0, 8.0], [2.0, 8.0]],  # hole
        ],
        "style": {},
    }
    _offset_node(node, 100.0, 50.0)
    # Exterior ring
    assert node["rings"][0][0] == [100.0, 50.0], (
        f"polygon ring[0][0] not offset: {node['rings'][0][0]}"
    )
    assert node["rings"][0][1] == [110.0, 50.0]
    assert node["rings"][0][2] == [110.0, 60.0]
    # Hole ring
    assert node["rings"][1][0] == [102.0, 52.0]


# ===========================================================================
# 3. _offset_node: polyline type (W4 -- node type not handled)
# ===========================================================================


def test_offset_node_polyline_type():  # BUG: _offset_node ignores polyline node type -- points not shifted
    """_offset_node must offset every point in a polyline."""
    node = {
        "type": "polyline",
        "points": [[0.0, 0.0], [10.0, 20.0], [30.0, 40.0]],
        "style": {},
    }
    _offset_node(node, 5.0, 15.0)
    assert node["points"][0] == [5.0, 15.0], f"polyline point[0] not offset: {node['points'][0]}"
    assert node["points"][1] == [15.0, 35.0]
    assert node["points"][2] == [35.0, 55.0]


# ===========================================================================
# 4. _offset_node: raw type (W4 -- rect-offset + clip-id uniquification)
# ===========================================================================


def test_offset_node_raw_rect_offset():
    """_offset_node on a raw node offsets <rect> x/y attributes by (dx, dy).

    The fix for W4 (COMP-07) makes _offset_node translate the baked absolute
    <rect> coords in opaque SVG chrome defs.  Non-rect geometry (circles etc.)
    is left untouched -- raw defs only carry clip-region rects.
    """
    node = {
        "type": "raw",
        "svg": '<rect x="10" y="20" width="100" height="40"/><circle cx="10" cy="20" r="5"/>',
        "anchor": "chrome",
    }
    _offset_node(node, 100.0, 50.0)
    # rect x/y shifted; circle coords are opaque (not <rect>) and unchanged
    assert (
        node["svg"]
        == '<rect x="110.0" y="70.0" width="100" height="40"/><circle cx="10" cy="20" r="5"/>'
    )


def test_offset_node_raw_clip_uniquify():
    """_offset_node on a raw node uniquifies ferrum clip/colorbar/legend-clip ids
    when clip_cell_idx is provided, mirroring uniquify_clip_ids in compositor.rs.
    """
    svg = (
        '<clipPath id="ferrum-clip-0"><rect x="0" y="0" width="100" height="80"/></clipPath>'
        '<g clip-path="url(#ferrum-clip-0)"/>'
        '<linearGradient id="ferrum-colorbar-0"/>'
        '<clipPath id="ferrum-legend-clip-0"/>'
        '<use href="url(#ferrum-legend-clip-0)"/>'
    )
    node = {"type": "raw", "svg": svg, "anchor": "chrome"}
    _offset_node(node, 0.0, 0.0, clip_cell_idx=2)
    result = node["svg"]
    assert 'id="cell2-ferrum-clip-0"' in result
    assert "url(#cell2-ferrum-clip-0)" in result
    assert 'id="cell2-ferrum-colorbar-0"' in result
    assert 'id="cell2-ferrum-legend-clip-0"' in result
    assert "url(#cell2-ferrum-legend-clip-0)" in result
    # Original ids should be gone
    assert 'id="ferrum-clip-0"' not in result
    assert 'id="ferrum-colorbar-0"' not in result
    assert 'id="ferrum-legend-clip-0"' not in result


def test_offset_node_raw_clip_none_leaves_ids_unchanged():
    """_offset_node with clip_cell_idx=None must NOT rewrite clip ids (back-compat)."""
    svg = (
        '<clipPath id="ferrum-clip-0"><rect x="10" y="20" width="100" height="80"/></clipPath>'
        '<g clip-path="url(#ferrum-clip-0)"/>'
    )
    node = {"type": "raw", "svg": svg, "anchor": "chrome"}
    _offset_node(node, 5.0, 3.0, clip_cell_idx=None)
    result = node["svg"]
    # rect coords shifted but clip ids unchanged
    assert 'id="ferrum-clip-0"' in result
    assert "url(#ferrum-clip-0)" in result
    assert "cell" not in result


# ===========================================================================
# 5. _offset_node: unknown node type is silent no-op
# ===========================================================================


def test_offset_node_unknown_type_no_crash():
    """_offset_node with an unknown type must not crash -- it silently
    does nothing (no coordinates to offset)."""
    node = {"type": "sparkline", "data": [1, 2, 3]}
    _offset_node(node, 10.0, 20.0)
    # No crash; node unchanged
    assert node == {"type": "sparkline", "data": [1, 2, 3]}


# ===========================================================================
# 6. _offset_node: zero offset triggers early return
# ===========================================================================


def test_offset_node_zero_offset_is_noop():
    """_offset_node with dx=0 and dy=0 must return immediately without
    modifying the node."""
    node = {"type": "circle", "cx": 10.0, "cy": 20.0, "r": 5.0, "style": {}}
    _offset_node(node, 0.0, 0.0)
    assert node["cx"] == 10.0
    assert node["cy"] == 20.0


# ===========================================================================
# 7. _offset_node: path with arc_to command
# ===========================================================================


def test_offset_node_path_arc_to():
    """_offset_node must offset arc_to endpoint (x, y) but NOT rx/ry
    (they are radii, not coordinates)."""
    node = {
        "type": "path",
        "commands": [
            {"op": "move_to", "x": 10.0, "y": 20.0},
            {
                "op": "arc_to",
                "rx": 25.0,
                "ry": 25.0,
                "rotation": 0.0,
                "large_arc": False,
                "sweep": True,
                "x": 50.0,
                "y": 60.0,
            },
        ],
    }
    _offset_node(node, 100.0, 200.0)
    arc_cmd = node["commands"][1]
    # Endpoint must be offset
    assert arc_cmd["x"] == 150.0, f"arc_to x not offset: {arc_cmd['x']}"
    assert arc_cmd["y"] == 260.0, f"arc_to y not offset: {arc_cmd['y']}"
    # Radii must NOT be offset
    assert arc_cmd["rx"] == 25.0, f"arc_to rx should not be offset: {arc_cmd['rx']}"
    assert arc_cmd["ry"] == 25.0, f"arc_to ry should not be offset: {arc_cmd['ry']}"


# ===========================================================================
# 8. _merge_child_scenes: 0 children
# ===========================================================================


def test_merge_child_scenes_zero_children():
    """_merge_child_scenes with an empty charts list must return a valid
    empty scene JSON with no panels."""
    scene_json, packed = _merge_child_scenes([], spacing=10.0, layout="horizontal")
    scene = json.loads(scene_json)
    assert scene["panels"] == []
    assert scene["width"] == 0
    assert scene["height"] == 0
    assert packed == b""


# ===========================================================================
# 9. _merge_child_scenes: 1 child
# ===========================================================================


def test_merge_child_scenes_single_child():
    """_merge_child_scenes with exactly 1 chart must produce 1 panel
    with panel ID 0 and no offset applied."""
    chart = _simple_chart()
    scene_json, packed = _merge_child_scenes([chart], spacing=10.0, layout="horizontal")
    scene = json.loads(scene_json)
    assert len(scene["panels"]) == 1
    assert scene["panels"][0]["id"] == 0
    assert isinstance(packed, bytes)


# ===========================================================================
# 10. _merge_child_scenes_grid: columns=1 (single column)
# ===========================================================================


def test_merge_child_scenes_grid_single_column():
    """_merge_child_scenes_grid with columns=1 must stack all charts vertically."""
    charts = [_simple_chart() for _ in range(3)]
    scene_json, packed = _merge_child_scenes_grid(charts, spacing=10.0, columns=1)
    scene = json.loads(scene_json)
    panels = scene["panels"]
    assert len(panels) == 3
    # Each panel should be in a different row (increasing y)
    y_coords = [p["plot_area"]["y"] for p in panels]
    assert y_coords[1] > y_coords[0], "second panel must be below first"
    assert y_coords[2] > y_coords[1], "third panel must be below second"
    # All in the same column (same x)
    x_coords = [p["plot_area"]["x"] for p in panels]
    assert x_coords[0] == x_coords[1] == x_coords[2], "all panels must have same x offset"


# ===========================================================================
# 11. _merge_child_scenes_grid: columns > len(charts)
# ===========================================================================


def test_merge_child_scenes_grid_columns_exceeds_count():
    """_merge_child_scenes_grid with columns > len(charts) must place all
    charts in a single row."""
    charts = [_simple_chart() for _ in range(2)]
    scene_json, packed = _merge_child_scenes_grid(charts, spacing=10.0, columns=10)
    scene = json.loads(scene_json)
    panels = scene["panels"]
    assert len(panels) == 2
    # Both panels should have the same y (single row)
    y0 = panels[0]["plot_area"]["y"]
    y1 = panels[1]["plot_area"]["y"]
    assert y0 == y1, f"panels should be in same row but y0={y0}, y1={y1}"
    # Panel 1 to the right of panel 0
    assert panels[1]["plot_area"]["x"] > panels[0]["plot_area"]["x"]


# ===========================================================================
# 12. _merge_child_scenes_grid: 0 charts
# ===========================================================================


def test_merge_child_scenes_grid_empty():
    """_merge_child_scenes_grid with no charts must return a valid empty scene."""
    scene_json, packed = _merge_child_scenes_grid([], spacing=10.0, columns=3)
    scene = json.loads(scene_json)
    assert scene["panels"] == []
    assert packed == b""


# ===========================================================================
# 13. _merge_packed_data: all empty
# ===========================================================================


def test_merge_packed_data_all_empty():
    """_merge_packed_data with all-empty packed data returns empty bytes."""
    result = _merge_packed_data([b"", b"", b""], [0, 1, 2], [(0.0, 0.0), (0.0, 0.0), (0.0, 0.0)])
    assert result == b""


# ===========================================================================
# 14. _merge_packed_data: some non-empty (falls back to empty)
# ===========================================================================


def test_merge_packed_data_mixed_returns_empty_for_invalid_data():
    """_merge_packed_data with a mix of empty and non-empty but invalid
    packed data (too short for a 20-byte header) returns empty bytes."""
    result = _merge_packed_data(
        [b"", b"\x01\x02\x03", b""], [0, 1, 2], [(0.0, 0.0), (0.0, 0.0), (0.0, 0.0)]
    )
    assert result == b"", "invalid packed data (too short for header) must produce empty bytes"


# ===========================================================================
# 15. _merge_packed_data: all non-empty (falls back to empty)
# ===========================================================================


def test_merge_packed_data_all_nonempty_invalid_returns_empty():
    """_merge_packed_data with all non-empty but invalid packed data (too
    short for a 20-byte header) returns empty bytes."""
    result = _merge_packed_data([b"\x01\x02", b"\x03\x04"], [0, 1], [(0.0, 0.0), (0.0, 0.0)])
    assert result == b"", "invalid packed data (too short for header) must produce empty bytes"


# ===========================================================================
# 16. _merge_packed_data: empty list
# ===========================================================================


def test_merge_packed_data_empty_list():
    """_merge_packed_data with an empty list must return empty bytes."""
    result = _merge_packed_data([], [], [])
    assert result == b""


# ===========================================================================
# 17. _background_css_from_dict: missing background
# ===========================================================================


def test_background_css_from_dict_no_background():
    """_background_css_from_dict with no 'background' key must return white."""
    result = _background_css_from_dict({})
    assert result == "#ffffff"


def test_background_css_from_dict_none_background():
    """_background_css_from_dict with background=None must return white."""
    result = _background_css_from_dict({"background": None})
    assert result == "#ffffff"


# ===========================================================================
# 18. _background_css_from_dict: malformed background dict (W7)
# ===========================================================================


def test_background_css_from_dict_malformed_raises():  # BUG: _background_css_from_dict crashes on malformed dict -- no try/except guard
    """_background_css_from_dict with a malformed background dict (missing keys)
    should not crash. It should either handle gracefully or the caller should
    guard with try/except."""
    # A background dict missing the 'r' key
    malformed = {"background": {"g": 128, "b": 255, "a": 255}}
    try:
        result = _background_css_from_dict(malformed)
        # If it doesn't crash, any fallback is acceptable
        assert isinstance(result, str)
    except KeyError:
        pytest.fail(
            "_background_css_from_dict crashed with KeyError on malformed background dict; "
            "expected graceful fallback or caller guard"
        )


# ===========================================================================
# 19. _empty_scene: all required keys present
# ===========================================================================


def test_empty_scene_has_all_required_keys():
    """_empty_scene must return a dict with all keys required by the WASM
    SceneGraph deserializer."""
    scene = _empty_scene()
    required_top = {
        "width",
        "height",
        "background",
        "title",
        "panels",
        "legend",
        "decorations",
        "selections",
        "interaction",
    }
    for key in required_top:
        assert key in scene, f"_empty_scene missing top-level key: {key!r}"

    interaction = scene["interaction"]
    required_interaction = {
        "zoom_enabled",
        "pan_enabled",
        "conditionals",
        "linked_panels",
        "tick_levels",
    }
    for key in required_interaction:
        assert key in interaction, f"_empty_scene.interaction missing key: {key!r}"

    # Verify types
    assert isinstance(scene["panels"], list)
    assert isinstance(scene["title"], list)
    assert isinstance(scene["legend"], list)
    assert isinstance(scene["decorations"], list)
    assert isinstance(scene["selections"], list)
    assert isinstance(interaction["conditionals"], list)
    assert isinstance(interaction["linked_panels"], list)
    assert isinstance(interaction["tick_levels"], list)


# ===========================================================================
# 20. _extract_title_text: Title dataclass with text=None
# ===========================================================================


def test_extract_title_text_title_with_none_text():
    """_extract_title_text on a Title(text=None) must return 'Ferrum chart',
    not 'None' or the repr."""
    from ferrum.title import Title

    t = Title(text=None)
    result = _extract_title_text(t)
    assert result == "Ferrum chart", f"expected 'Ferrum chart'; got {result!r}"


def test_extract_title_text_plain_string():
    """_extract_title_text on a plain string must return that string."""
    result = _extract_title_text("My Chart")
    assert result == "My Chart"


def test_extract_title_text_none():
    """_extract_title_text(None) must return 'Ferrum chart'."""
    result = _extract_title_text(None)
    assert result == "Ferrum chart"


def test_extract_title_text_title_dataclass():
    """_extract_title_text on a Title(text='Hello') must return 'Hello'."""
    from ferrum.title import Title

    t = Title(text="Hello")
    result = _extract_title_text(t)
    assert result == "Hello"


def test_extract_title_text_empty_string():
    """_extract_title_text('') must return 'Ferrum chart' (empty string
    is falsy)."""
    result = _extract_title_text("")
    assert result == "Ferrum chart"


# ===========================================================================
# 21. JointChart._render_interactive: center only
# ===========================================================================


def test_joint_chart_interactive_center_only():
    """JointChart with only a center chart (no marginals) must produce
    valid interactive scene JSON via _render_scene dispatch."""
    chart = _simple_chart()
    joint = fm.JointChart(chart)
    scene_json, packed = joint._render_interactive()
    scene = json.loads(scene_json)
    assert len(scene["panels"]) == 1
    assert isinstance(packed, bytes)


# ===========================================================================
# 22. ConcatChart._render_interactive with single chart
# ===========================================================================


def test_concat_chart_single_child():
    """ConcatChart with a single chart must render without error."""
    chart = _simple_chart()
    concat = ConcatChart(chart, columns=1)
    scene_json, packed = concat._render_interactive()
    scene = json.loads(scene_json)
    assert len(scene["panels"]) == 1
    assert isinstance(packed, bytes)


# ===========================================================================
# 23. ConcatChart._render_interactive: wrapping grid
# ===========================================================================


def test_concat_chart_wrapping_grid():
    """ConcatChart with 5 charts and columns=2 must produce 5 panels
    arranged in a grid (3 rows x 2 columns, last cell empty)."""
    charts = [_simple_chart() for _ in range(5)]
    concat = ConcatChart(*charts, columns=2)
    scene_json, packed = concat._render_interactive()
    scene = json.loads(scene_json)
    panels = scene["panels"]
    assert len(panels) == 5
    # Panel IDs must be sequential 0..4
    ids = [p["id"] for p in panels]
    assert ids == list(range(5)), f"panel IDs must be [0,1,2,3,4]; got {ids}"


# ===========================================================================
# 24. _merge_scene_panels: panel ID re-indexing with offset
# ===========================================================================


def test_merge_scene_panels_reindexing():
    """_merge_scene_panels must add panel_id_offset to each panel ID."""
    merged = _empty_scene()
    child_scene = {
        "panels": [
            {
                "id": 0,
                "plot_area": {"x": 0, "y": 0, "w": 100, "h": 80},
                "clip": {"x": 0, "y": 0, "w": 100, "h": 80},
                "marks": [],
                "axes": [],
                "grid": [],
                "annotations": [],
            },
            {
                "id": 1,
                "plot_area": {"x": 110, "y": 0, "w": 100, "h": 80},
                "clip": {"x": 110, "y": 0, "w": 100, "h": 80},
                "marks": [],
                "axes": [],
                "grid": [],
                "annotations": [],
            },
        ]
    }
    _merge_scene_panels(merged, child_scene, dx=200.0, dy=50.0, panel_id_offset=5)
    assert len(merged["panels"]) == 2
    assert merged["panels"][0]["id"] == 5
    assert merged["panels"][1]["id"] == 6
    # Plot areas must be offset by dx, dy
    assert merged["panels"][0]["plot_area"]["x"] == 200.0
    assert merged["panels"][0]["plot_area"]["y"] == 50.0
    assert merged["panels"][1]["plot_area"]["x"] == 310.0
    assert merged["panels"][1]["plot_area"]["y"] == 50.0


# ===========================================================================
# 25. _merge_scene_panels does not mutate original scene
# ===========================================================================


def test_merge_scene_panels_does_not_mutate_original():
    """_merge_scene_panels must deep-copy panels before mutation."""
    merged = _empty_scene()
    child_scene = {
        "panels": [
            {
                "id": 0,
                "plot_area": {"x": 10, "y": 20, "w": 100, "h": 80},
                "clip": {"x": 10, "y": 20, "w": 100, "h": 80},
                "marks": [],
                "axes": [],
                "grid": [],
                "annotations": [],
            }
        ]
    }
    original_x = child_scene["panels"][0]["plot_area"]["x"]
    _merge_scene_panels(merged, child_scene, dx=50.0, dy=30.0, panel_id_offset=0)
    # Original scene must not be mutated
    assert child_scene["panels"][0]["plot_area"]["x"] == original_x, (
        "original scene was mutated by _merge_scene_panels"
    )


# ===========================================================================
# 26. HConcatChart with 3+ charts: panel IDs sequential
# ===========================================================================


def test_hconcat_three_charts_panel_ids():
    """HConcatChart with 3 charts must produce panel IDs [0, 1, 2]."""
    charts = [_simple_chart() for _ in range(3)]
    composed = HConcatChart(charts)
    scene_json, _ = composed._render_interactive()
    scene = json.loads(scene_json)
    panel_ids = [p["id"] for p in scene["panels"]]
    assert panel_ids == [0, 1, 2], f"expected [0,1,2]; got {panel_ids}"


# ===========================================================================
# 27. VConcatChart interactive: width is max of children
# ===========================================================================


def test_vconcat_interactive_width_is_max_child():
    """VConcatChart scene width must be the max of children widths."""
    c1 = _simple_chart(width=200, height=200)
    c2 = _simple_chart(width=300, height=200)
    composed = VConcatChart([c1, c2])
    scene_json, _ = composed._render_interactive()
    scene = json.loads(scene_json)
    # The wider chart dominates the total width
    assert scene["width"] >= 300, f"scene width should be >= 300; got {scene['width']}"


# ===========================================================================
# 28. HConcatChart interactive: height is max of children
# ===========================================================================


def test_hconcat_interactive_height_is_max_child():
    """HConcatChart scene height must be the max of children heights."""
    c1 = _simple_chart(width=200, height=200)
    c2 = _simple_chart(width=200, height=300)
    composed = HConcatChart([c1, c2])
    scene_json, _ = composed._render_interactive()
    scene = json.loads(scene_json)
    assert scene["height"] >= 300, f"scene height should be >= 300; got {scene['height']}"


# ===========================================================================
# 29. _offset_node: group with nested mixed types
# ===========================================================================


def test_offset_node_group_recursive():
    """_offset_node on a group must recursively offset all children."""
    node = {
        "type": "group",
        "attrs": [],
        "children": [
            {"type": "circle", "cx": 10.0, "cy": 20.0, "r": 5.0, "style": {}},
            {"type": "rect", "x": 30.0, "y": 40.0, "w": 50.0, "h": 60.0, "style": {}},
            {
                "type": "group",
                "attrs": [],
                "children": [
                    {"type": "text", "x": 100.0, "y": 110.0, "content": "hi", "style": {}},
                ],
            },
        ],
    }
    _offset_node(node, 7.0, 13.0)
    assert node["children"][0]["cx"] == 17.0
    assert node["children"][0]["cy"] == 33.0
    assert node["children"][1]["x"] == 37.0
    assert node["children"][1]["y"] == 53.0
    # Nested group child
    assert node["children"][2]["children"][0]["x"] == 107.0
    assert node["children"][2]["children"][0]["y"] == 123.0


# ===========================================================================
# 30. Composition .save(format="svg") round-trip
# ===========================================================================


def test_composition_save_svg_roundtrip(tmp_path):
    """HConcatChart.save() with SVG format must write valid SVG to disk."""
    composed = HConcatChart([_simple_chart(), _simple_chart()])
    out = tmp_path / "comp.svg"
    composed.save(str(out))
    content = out.read_text()
    assert "<svg" in content
    assert "NaN" not in content


# ===========================================================================
# 31. Composition .save() with unsupported format raises
# ===========================================================================


def test_composition_save_unsupported_format_raises():
    """Saving composition with a genuinely unsupported format raises ValueError."""
    import tempfile
    import os

    composed = HConcatChart([_simple_chart(), _simple_chart()])
    with tempfile.NamedTemporaryFile(suffix=".xyz", delete=False) as f:
        tmp = f.name
    try:
        with pytest.raises(ValueError, match="xyz|not supported"):
            composed.save(tmp, format="xyz")
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


def test_composition_save_pdf_works():
    """Saving composition as PDF now succeeds (F14)."""
    import tempfile
    import os

    composed = HConcatChart([_simple_chart(), _simple_chart()])
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as f:
        tmp = f.name
    try:
        composed.save(tmp)
        with open(tmp, "rb") as fh:
            assert fh.read(5) == b"%PDF-"
    finally:
        os.unlink(tmp)


# ===========================================================================
# 32. _offset_node: path with Close command (no coordinates)
# ===========================================================================


def test_offset_node_path_close_no_crash():
    """_offset_node must handle a Close command (no coordinate keys) without
    error."""
    node = {
        "type": "path",
        "commands": [
            {"op": "move_to", "x": 0.0, "y": 0.0},
            {"op": "line_to", "x": 10.0, "y": 0.0},
            {"op": "close"},
        ],
    }
    _offset_node(node, 5.0, 5.0)
    assert node["commands"][0]["x"] == 5.0
    assert node["commands"][2] == {"op": "close"}


# ===========================================================================
# 33. _offset_node: line node -- all four endpoints offset
# ===========================================================================


def test_offset_node_line_all_endpoints():
    """_offset_node must offset x1, y1, x2, y2 of a line node."""
    node = {"type": "line", "x1": 0.0, "y1": 0.0, "x2": 100.0, "y2": 50.0, "style": {}}
    _offset_node(node, 10.0, 20.0)
    assert node["x1"] == 10.0
    assert node["y1"] == 20.0
    assert node["x2"] == 110.0
    assert node["y2"] == 70.0


# ===========================================================================
# 34. Tick-level panel_id re-indexing in merged scenes
# ===========================================================================


def test_tick_level_panel_id_reindexed():
    """tick_levels from child scenes must have panel_id adjusted by
    the panel_id_offset."""
    chart = _simple_chart()
    scene_json1, _ = _render_scene(chart)
    scene1 = json.loads(scene_json1)

    scene_json2, _ = _render_scene(chart)
    scene2 = json.loads(scene_json2)

    # If either scene has tick_levels, verify they would be reindexed
    tl1 = scene1.get("interaction", {}).get("tick_levels", [])
    tl2 = scene2.get("interaction", {}).get("tick_levels", [])

    if tl1 or tl2:
        # Build a composed scene manually to check panel_id offset
        composed = HConcatChart([chart, chart])
        merged_json, _ = composed._render_interactive()
        merged = json.loads(merged_json)
        tick_levels = merged["interaction"]["tick_levels"]
        if len(tick_levels) >= 2:
            # First child's tick_levels should have panel_id starting at 0
            # Second child's should be offset
            ids = [tl["panel_id"] for tl in tick_levels]
            assert len(set(ids)) > 1 or len(tick_levels) == 0, (
                "tick_level panel_ids must be distinct across composed children"
            )
    # If no tick_levels at all, that's fine -- test passes trivially


# ===========================================================================
# 35. LayerChart no-op when 0 charts raises ValueError
# ===========================================================================


def test_layer_chart_zero_charts_raises():
    """LayerChart with no charts must raise ValueError."""
    with pytest.raises(ValueError, match="at least one"):
        fm.LayerChart()


# ===========================================================================
# 36. ConcatChart with columns=None defaults to single row
# ===========================================================================


def test_concat_chart_no_columns_single_row():
    """ConcatChart with columns=None places all charts in a single row."""
    charts = [_simple_chart() for _ in range(3)]
    concat = ConcatChart(*charts)
    scene_json, _ = concat._render_interactive()
    scene = json.loads(scene_json)
    panels = scene["panels"]
    assert len(panels) == 3
    # All panels in same row means same y offset
    y_coords = [p["plot_area"]["y"] for p in panels]
    assert y_coords[0] == y_coords[1] == y_coords[2], (
        f"all panels should have same y for single-row layout; got {y_coords}"
    )


# ===========================================================================
# 37. _offset_node raw branch: rect-offset + clip-id uniquification (COMP-07 / W4)
# ===========================================================================


def test_offset_node_raw_rect_offset_and_clip_uniquify():
    """_offset_node on a raw node offsets <rect> x/y and uniquifies clip ids.

    Regression for COMP-07 (W4): the raw branch was absent, leaving baked
    SVG coords un-offset and clip ids colliding across composed children.
    """
    svg = (
        '<rect x="10" y="20" width="80" height="40"/>'
        '<clipPath id="ferrum-clip-0"><rect x="0" y="0" width="80" height="40"/></clipPath>'
        '<g clip-path="url(#ferrum-clip-0)"/>'
        '<linearGradient id="ferrum-colorbar-0"/>'
        '<clipPath id="ferrum-legend-clip-0"/>'
        '<use href="url(#ferrum-legend-clip-0)"/>'
    )
    node = {"type": "raw", "svg": svg, "anchor": "chrome"}

    _offset_node(node, 100.0, 50.0, clip_cell_idx=2)
    result = node["svg"]

    # --- rect coords offset ---
    assert 'x="110.0"' in result, f"outer rect x not shifted; got: {result}"
    assert 'y="70.0"' in result, f"outer rect y not shifted; got: {result}"

    # --- clip ids uniquified ---
    assert 'id="cell2-ferrum-clip-0"' in result
    assert "url(#cell2-ferrum-clip-0)" in result
    assert 'id="cell2-ferrum-colorbar-0"' in result
    assert 'id="cell2-ferrum-legend-clip-0"' in result
    assert "url(#cell2-ferrum-legend-clip-0)" in result

    # --- original ids gone ---
    assert 'id="ferrum-clip-0"' not in result
    assert 'id="ferrum-colorbar-0"' not in result
    assert 'id="ferrum-legend-clip-0"' not in result


def test_offset_node_raw_clip_none_preserves_ids_but_offsets_rect():
    """With clip_cell_idx=None, rect x/y is still offset but clip ids are unchanged."""
    svg = (
        '<rect x="10" y="20" width="80" height="40"/>'
        '<clipPath id="ferrum-clip-0"><rect x="5" y="5" width="10" height="10"/></clipPath>'
        '<g clip-path="url(#ferrum-clip-0)"/>'
    )
    node = {"type": "raw", "svg": svg, "anchor": "chrome"}
    _offset_node(node, 100.0, 50.0, clip_cell_idx=None)
    result = node["svg"]

    # rect shifted
    assert 'x="110.0"' in result
    assert 'y="70.0"' in result
    # ids preserved (no uniquification)
    assert 'id="ferrum-clip-0"' in result
    assert "url(#ferrum-clip-0)" in result
    assert "cell" not in result


def test_offset_node_raw_group_nested_forward():
    """A raw node nested inside a group gets offset+uniquified via recursive forward."""
    inner_svg = (
        '<rect x="5" y="10" width="50" height="30"/>'
        '<clipPath id="ferrum-clip-0"/>'
        '<g clip-path="url(#ferrum-clip-0)"/>'
    )
    node = {
        "type": "group",
        "attrs": [],
        "children": [
            {"type": "raw", "svg": inner_svg, "anchor": "chrome"},
            {"type": "circle", "cx": 1.0, "cy": 2.0, "r": 3.0, "style": {}},
        ],
    }
    _offset_node(node, 20.0, 30.0, clip_cell_idx=1)

    raw_result = node["children"][0]["svg"]
    # rect offset
    assert 'x="25.0"' in raw_result
    assert 'y="40.0"' in raw_result
    # clip id uniquified with cell_idx=1
    assert 'id="cell1-ferrum-clip-0"' in raw_result
    assert "url(#cell1-ferrum-clip-0)" in raw_result

    # sibling circle also offset
    assert node["children"][1]["cx"] == 21.0
    assert node["children"][1]["cy"] == 32.0
