"""Edge-case tests for figure-api (Round 2) — generated by bug-hunter agent.

Round 1 found 4 bugs (catplot/box integer column crash x3, CSS shorthand hex
rejection x1). Those are covered by the existing tests. This round targets:

- configure() with format presets, domain clamping, tick_values
- relplot with style/size parameters
- catplot with order/hue_order, orient="h" for non-box kinds
- displot multiple="fill"/"dodge"
- lmplot with various methods and hue
- regplot, residplot edge cases
- configure_grid band_colors, configure_padding auto=False
- Multiple configure calls of same domain (last-wins)
- configure_axis x=False (y-only config)
- configure with axis_y2
- labs() unknown key error
- Annotations rendered in SVG output
- catplot seed parameter
- NaN in hue columns across figure functions
- configure on HConcat/VConcat composed charts
- mark_line(point=True) composition
- All-null column in figure functions
- configure_axis domain_min/domain_max on rendered SVG
- Extreme tick_values
- configure_color domain+range interaction
- override + configure interaction on rendered SVG
"""

from __future__ import annotations

import json
import math

import polars as pl
import pytest

import ferrum as fm
from ferrum.configure import (
    AxisConfig,
    ColorConfig,
    Configure,
    GridConfig,
    LegendConfig,
    PaddingConfig,
    TitleConfig,
)
from ferrum.structural import BreakAxis, Inset, SecondaryY
import ferrum.annotation as ann
from ferrum.annotation import Annotate


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def simple_df():
    return pl.DataFrame({"x": [1.0, 2.0, 3.0, 4.0, 5.0], "y": [2.0, 4.0, 1.0, 5.0, 3.0]})


@pytest.fixture
def cat_df():
    return pl.DataFrame(
        {
            "group": ["a"] * 10 + ["b"] * 10,
            "value": list(range(10)) + list(range(5, 15)),
        }
    )


@pytest.fixture
def cat_float_df():
    """Same as cat_df but with Float64 value column to avoid the integer-cast bug."""
    return pl.DataFrame(
        {
            "group": ["a"] * 10 + ["b"] * 10,
            "value": [float(v) for v in list(range(10)) + list(range(5, 15))],
        }
    )


@pytest.fixture
def iris_df():
    import numpy as np

    rng = np.random.default_rng(42)
    return pl.DataFrame(
        {
            "sepal_length": rng.normal(5.0, 0.5, 40).tolist(),
            "sepal_width": rng.normal(3.0, 0.3, 40).tolist(),
            "species": ["a"] * 20 + ["b"] * 20,
        }
    )


@pytest.fixture
def hue_df():
    """DataFrame suitable for multi-group figure functions."""
    import numpy as np

    rng = np.random.default_rng(99)
    return pl.DataFrame(
        {
            "x": rng.uniform(0, 10, 60).tolist(),
            "y": rng.uniform(0, 10, 60).tolist(),
            "group": (["A"] * 20 + ["B"] * 20 + ["C"] * 20),
        }
    )


# ===================================================================
# Category: configure_axis with format presets
# ===================================================================


class TestConfigureAxisFormatPresets:
    """Tests for AxisConfig.label_format preset resolution and rendering.
    Targets configure.py lines 109-131 and format_presets.py resolve_format.
    """

    def test_axis_config_percent_preset_resolves(self):
        """AxisConfig.to_dict should resolve 'percent' to '.1%'."""
        cfg = AxisConfig(label_format="percent")
        d = cfg.to_dict()
        assert d["label_format"] == ".1%"

    def test_axis_config_currency_preset_resolves(self):
        """AxisConfig.to_dict should resolve 'currency' to '$,.0f'."""
        cfg = AxisConfig(label_format="currency")
        d = cfg.to_dict()
        assert d["label_format"] == "$,.0f"

    def test_axis_config_ordinal_preset_resolves(self):
        """AxisConfig.to_dict should resolve 'ordinal' to '__ordinal__' sentinel."""
        cfg = AxisConfig(label_format="ordinal")
        d = cfg.to_dict()
        assert d["label_format"] == "__ordinal__"

    def test_configure_axis_format_preset_renders_svg(self, simple_df):
        """Chart with configure_axis(label_format='percent') should render valid SVG.
        Exercises the full pipeline: AxisConfig -> _resolve_chart_config -> Rust renderer.
        """
        chart = (
            fm.Chart(simple_df)
            .mark_bar()
            .encode(x="x", y="y")
            .configure_axis(label_format="percent")
        )
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_configure_axis_format_raw_renders_svg(self, simple_df):
        """Chart with configure_axis(label_format_raw='.3f') should render valid SVG."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_axis(label_format_raw=".3f")
        )
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: configure_axis domain clamping and tick_values
# ===================================================================


class TestConfigureAxisDomainAndTicks:
    """Tests targeting AxisConfig domain_min/domain_max/tick_values/zero/nice.
    These flow through _resolve_chart_config and into Rust scale resolution.
    """

    def test_domain_min_max_in_config_dict(self, simple_df):
        """AxisConfig domain_min/domain_max should appear in to_dict output."""
        cfg = AxisConfig(domain_min=0, domain_max=100)
        d = cfg.to_dict()
        assert d["domain_min"] == 0
        assert d["domain_max"] == 100

    def test_configure_axis_domain_clamp_renders(self, simple_df):
        """configure_axis with domain_min/domain_max should produce valid SVG."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_axis(domain_min=-10, domain_max=20)
        )
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_explicit_tick_values_in_config(self, simple_df):
        """AxisConfig tick_values should appear in to_dict."""
        cfg = AxisConfig(tick_values=[0, 25, 50, 75, 100])
        d = cfg.to_dict()
        assert d["tick_values"] == [0, 25, 50, 75, 100]

    def test_configure_axis_tick_values_renders(self, simple_df):
        """configure_axis with explicit tick_values should render valid SVG."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_axis(tick_values=[1.0, 3.0, 5.0])
        )
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_configure_axis_nice_and_zero(self, simple_df):
        """AxisConfig with nice=True and zero=True should render."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_axis(nice=True, zero=True)
        )
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_empty_tick_values_list(self, simple_df):
        """AxisConfig with tick_values=[] — degenerate empty list."""
        cfg = AxisConfig(tick_values=[])
        d = cfg.to_dict()
        assert d["tick_values"] == []


# ===================================================================
# Category: relplot with style and size parameters
# ===================================================================


class TestRelplotStyleSize:
    """Tests for relplot's style and size encoding wiring.
    Targets distribution.py relplot lines 719-723 (style -> shape/stroke_dash).
    """

    def test_relplot_scatter_with_style_maps_shape(self, hue_df):
        """relplot(kind='scatter', style=...) should map style to Shape encoding.
        distribution.py line 720: enc['shape'] = style."""
        chart = fm.relplot(hue_df, x="x", y="y", style="group")
        # Verify shape encoding was set
        assert "shape" in chart._encoding

    def test_relplot_line_with_style_maps_stroke_dash(self, hue_df):
        """relplot(kind='line', style=...) should map style to stroke_dash encoding.
        distribution.py line 722: enc['stroke_dash'] = style."""
        chart = fm.relplot(hue_df, x="x", y="y", style="group", kind="line")
        assert "stroke_dash" in chart._encoding

    def test_relplot_with_size_maps_size_encoding(self, hue_df):
        """relplot(size=...) should map to Size encoding.
        distribution.py line 718: enc['size'] = size."""
        chart = fm.relplot(hue_df, x="x", y="y", size="group")
        assert "size" in chart._encoding

    def test_relplot_scatter_style_renders_svg(self, hue_df):
        """relplot scatter with style should render valid SVG."""
        chart = fm.relplot(hue_df, x="x", y="y", hue="group", style="group")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_relplot_line_style_renders_svg(self, hue_df):
        """relplot line with style should render valid SVG."""
        chart = fm.relplot(hue_df, x="x", y="y", hue="group", style="group", kind="line")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: catplot order and hue_order
# ===================================================================


class TestCatplotOrderHueOrder:
    """Tests for catplot order/hue_order wiring.
    Targets distribution.py catplot lines 529-534.
    """

    def test_catplot_order_sets_sort_on_x(self, cat_float_df):
        """catplot(order=[...]) should set sort on the x encoding.
        distribution.py line 530: enc['x'] = _X(cat_field, sort=list(order))."""
        chart = fm.catplot(cat_float_df, x="group", y="value", kind="strip", order=["b", "a"])
        x_enc = chart._encoding.get("x")
        assert x_enc is not None
        assert hasattr(x_enc, "_kwargs")
        assert x_enc._kwargs.get("sort") == ["b", "a"]

    def test_catplot_hue_order_sets_sort_on_color(self):
        """catplot(hue_order=[...]) should set sort on the color encoding.
        distribution.py line 533: enc['color'] = _Color(hue, sort=list(hue_order))."""
        df = pl.DataFrame(
            {
                "cat": ["a"] * 10 + ["b"] * 10,
                "val": [float(x) for x in range(20)],
                "grp": (["X", "Y"] * 10),
            }
        )
        chart = fm.catplot(df, x="cat", y="val", hue="grp", kind="strip", hue_order=["Y", "X"])
        color_enc = chart._encoding.get("color")
        assert color_enc is not None
        assert hasattr(color_enc, "_kwargs")
        assert color_enc._kwargs.get("sort") == ["Y", "X"]

    def test_catplot_order_renders_svg(self, cat_float_df):
        """catplot with explicit order should produce valid SVG."""
        chart = fm.catplot(cat_float_df, x="group", y="value", kind="strip", order=["b", "a"])
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: catplot orient="h" for non-box kinds
# ===================================================================


class TestCatplotOrientH:
    """Tests for catplot orient='h' axis swap and CoordFlip wiring.
    Targets distribution.py catplot lines 494-523, 592-593.
    """

    def test_catplot_strip_orient_h(self, cat_float_df):
        """catplot(kind='strip', orient='h') should set CoordFlip.
        distribution.py line 592-593: horizontal → CoordFlip."""
        chart = fm.catplot(cat_float_df, x="value", y="group", kind="strip", orient="h")
        # CoordFlip should be set
        from ferrum.coord import CoordFlip

        assert isinstance(chart._coord, CoordFlip) or chart._coord == "flip"
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_catplot_violin_orient_h(self, cat_float_df):
        """catplot(kind='violin', orient='h') should render valid SVG."""
        chart = fm.catplot(cat_float_df, x="value", y="group", kind="violin", orient="h")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_catplot_swarm_orient_h(self, cat_float_df):
        """catplot(kind='swarm', orient='h') should render valid SVG."""
        chart = fm.catplot(cat_float_df, x="value", y="group", kind="swarm", orient="h")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: displot multiple="fill" and "dodge"
# ===================================================================


class TestDisplotMultiple:
    """Tests for displot multiple parameter variations.
    Targets distribution.py _multiple_to_position lines 47-56.
    """

    def test_displot_fill_multiple(self, iris_df):
        """displot(multiple='fill') should produce a stacked normalized histogram.
        distribution.py line 54: Stack(by=hue, offset='normalize')."""
        chart = fm.displot(iris_df, x="sepal_length", hue="species", multiple="fill")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_displot_dodge_multiple(self, iris_df):
        """displot(multiple='dodge') should produce side-by-side bars.
        distribution.py line 52: Dodge(by=hue)."""
        chart = fm.displot(iris_df, x="sepal_length", hue="species", multiple="dodge")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_displot_stack_multiple(self, iris_df):
        """displot(multiple='stack') should produce stacked histogram."""
        chart = fm.displot(iris_df, x="sepal_length", hue="species", multiple="stack")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: lmplot methods and hue
# ===================================================================


class TestLmplotMethods:
    """Tests for lmplot with different method= values.
    Targets regression.py lmplot lines 493-632.
    """

    def test_lmplot_loess_method(self, simple_df):
        """lmplot(method='loess') should render valid SVG.
        regression.py lines 600-609: mark_smooth(method='loess')."""
        chart = fm.lmplot(simple_df, x="x", y="y", method="loess", ci=None, show_metrics=False)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_lmplot_lm_with_ci(self, simple_df):
        """lmplot(method='lm', ci=95) should produce a chart with confidence band."""
        chart = fm.lmplot(simple_df, x="x", y="y", method="lm", ci=95, show_metrics=False)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_lmplot_lm_ci_none(self, simple_df):
        """lmplot(method='lm', ci=None) should produce chart without band."""
        chart = fm.lmplot(simple_df, x="x", y="y", method="lm", ci=None, show_metrics=False)
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_lmplot_with_hue(self, hue_df):
        """lmplot with hue should produce per-group fit lines.
        regression.py lines 559-585: hue routing for lm/loess methods."""
        chart = fm.lmplot(hue_df, x="x", y="y", hue="group", ci=None, show_metrics=False)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_lmplot_scatter_false(self, simple_df):
        """lmplot(scatter=False) should render only the fit line.
        regression.py line 647: scatter_layer is None."""
        chart = fm.lmplot(simple_df, x="x", y="y", scatter=False, ci=None, show_metrics=False)
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_lmplot_invalid_method_raises(self, simple_df):
        """lmplot with invalid method should raise ValueError.
        regression.py line 493-494."""
        with pytest.raises(ValueError, match="method"):
            fm.lmplot(simple_df, x="x", y="y", method="INVALID")

    def test_lmplot_quadratic(self, simple_df):
        """lmplot(method='lm', order=2) should produce a polynomial fit."""
        chart = fm.lmplot(
            simple_df, x="x", y="y", method="lm", order=2, ci=None, show_metrics=False
        )
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: regplot (thin wrapper)
# ===================================================================


class TestRegplot:
    """Tests for regplot which delegates to lmplot.
    Targets regression.py regplot lines 869-982."""

    def test_regplot_basic(self, simple_df):
        """regplot should produce same result as lmplot without faceting."""
        chart = fm.regplot(simple_df, x="x", y="y", ci=None)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_regplot_with_scatter_kws(self, simple_df):
        """regplot with scatter_kws should forward them to mark_point."""
        chart = fm.regplot(simple_df, x="x", y="y", ci=None, scatter_kws={"opacity": 0.3})
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_regplot_with_line_kws(self, simple_df):
        """regplot with line_kws should forward them to the fit line."""
        chart = fm.regplot(simple_df, x="x", y="y", ci=None, line_kws={"stroke_width": 3})
        svg = chart.to_svg()
        assert "<svg" in svg


# ===================================================================
# Category: residplot edge cases
# ===================================================================


class TestResidplot:
    """Tests for residplot, targeting regression.py residplot lines 679-866."""

    def test_residplot_basic(self, simple_df):
        """residplot should produce a scatter of residuals."""
        chart = fm.residplot(simple_df, x="x", y="y", show_metrics=False, zero_line=False)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_residplot_with_zero_line(self, simple_df):
        """residplot(zero_line=True) should produce a layered chart with rule overlay."""
        chart = fm.residplot(simple_df, x="x", y="y", show_metrics=False, zero_line=True)
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_residplot_with_lowess(self, simple_df):
        """residplot(lowess=True) should overlay a LOESS smoother."""
        chart = fm.residplot(simple_df, x="x", y="y", show_metrics=False, lowess=True)
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_residplot_with_label(
        self, simple_df
    ):  # BUG: ValueError: unknown column '_label' — Smooth transform discards injected columns
        """residplot(label='series') should inject a _label column."""
        chart = fm.residplot(
            simple_df, x="x", y="y", label="series A", show_metrics=False, zero_line=False
        )
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_residplot_dropna_true(self):
        """residplot(dropna=True) should drop null rows before fitting."""
        df = pl.DataFrame({"x": [1.0, None, 3.0, 4.0], "y": [2.0, 4.0, None, 8.0]})
        chart = fm.residplot(df, x="x", y="y", dropna=True, show_metrics=False, zero_line=False)
        svg = chart.to_svg()
        assert "<svg" in svg


# ===================================================================
# Category: configure_grid band_colors and configure_padding auto
# ===================================================================


class TestConfigureGridAndPadding:
    """Tests for GridConfig.band_colors and PaddingConfig.auto=False."""

    def test_grid_config_band_colors_in_dict(self):
        """GridConfig with band_colors should include them in to_dict."""
        cfg = GridConfig(band_colors=["#f0f0f0", "#ffffff"])
        d = cfg.to_dict()
        assert d["band_colors"] == ["#f0f0f0", "#ffffff"]

    def test_configure_grid_band_colors_renders(self, simple_df):
        """Chart with configure_grid(band_colors=[...]) should render valid SVG."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_grid(band_colors=["#f0f0f0", "#ffffff"])
        )
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_padding_config_auto_false(self):
        """PaddingConfig(auto=False) should include auto=False in to_dict."""
        cfg = PaddingConfig(auto=False, top=10, bottom=10)
        d = cfg.to_dict()
        assert d["auto"] is False
        assert d["top"] == 10

    def test_configure_padding_auto_false_renders(self, simple_df):
        """Chart with configure_padding(auto=False) should render valid SVG."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_padding(auto=False, top=5, right=5, bottom=5, left=5)
        )
        svg = chart.to_svg()
        assert "<svg" in svg


# ===================================================================
# Category: Multiple configure calls of same domain (last-wins)
# ===================================================================


class TestConfigureSameDomainLastWins:
    """Tests that multiple configure calls for the same domain merge correctly,
    with later values overriding earlier ones.
    Targets _resolve_chart_config merge logic in _render.py.
    """

    def test_two_configure_axis_last_wins(self, simple_df):
        """Two configure_axis calls: later label_angle should override earlier."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_axis(label_angle=-45, tick_count=5)
            .configure_axis(label_angle=-90)
        )
        config = chart._resolve_chart_config()
        # Second call set label_angle=-90, should override -45
        assert config.get("axis", {}).get("label_angle") == -90

    def test_two_configure_legend_last_wins(self, simple_df):
        """Two configure_legend calls: later orient should override earlier."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_legend(orient="bottom")
            .configure_legend(orient="top")
        )
        config = chart._resolve_chart_config()
        assert config.get("legend", {}).get("orient") == "top"

    def test_two_configure_title_last_wins(self, simple_df):
        """Two configure_title calls: later font_size should override earlier."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_title(font_size=14)
            .configure_title(font_size=24)
        )
        config = chart._resolve_chart_config()
        assert config.get("title", {}).get("font_size") == 24

    def test_configure_grid_override_color(self, simple_df):
        """Two configure_grid calls: later color should override earlier."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_grid(color="#ccc")
            .configure_grid(color="#eee")
        )
        config = chart._resolve_chart_config()
        assert config.get("grid", {}).get("color") == "#eee"


# ===================================================================
# Category: configure_axis with x=False (y-only)
# ===================================================================


class TestConfigureAxisSingleAxis:
    """Tests for AxisConfig x=False (apply only to y) or y=False.
    Targets configure.py AxisConfig.x/y fields.
    """

    def test_axis_config_x_false_in_dict(self):
        """AxisConfig(x=False) should include x=False in to_dict."""
        cfg = AxisConfig(x=False, label_angle=-45)
        d = cfg.to_dict()
        assert d["x"] is False
        assert d["label_angle"] == -45

    def test_axis_config_y_false_in_dict(self):
        """AxisConfig(y=False) should include y=False in to_dict."""
        cfg = AxisConfig(y=False, label_font_size=14)
        d = cfg.to_dict()
        assert d["y"] is False
        assert d["label_font_size"] == 14

    def test_configure_axis_x_false_renders(self, simple_df):
        """configure_axis(x=False, label_angle=-45) should only affect y axis."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure_axis(x=False, label_angle=-45)
        )
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: configure with axis_y2
# ===================================================================


class TestConfigureAxisY2:
    """Tests for Configure(axis_y2=...) wiring.
    Targets chart.py configure() line 4710 and configure.py Configure dataclass.
    """

    def test_configure_axis_y2_in_config_dict(self, simple_df):
        """Configure(axis_y2=AxisConfig(...)) should appear in resolved config."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure(axis_y2=AxisConfig(label_angle=45, label_color="red"))
        )
        config = chart._resolve_chart_config()
        assert "axis_y2" in config
        assert config["axis_y2"]["label_angle"] == 45
        assert config["axis_y2"]["label_color"] == "red"

    def test_axis_y2_coexists_with_axis_y(self, simple_df):
        """axis_y2 and axis_y should both appear in the config."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .configure(
                axis_y=AxisConfig(label_angle=0),
                axis_y2=AxisConfig(label_angle=90),
            )
        )
        config = chart._resolve_chart_config()
        assert config["axis_y"]["label_angle"] == 0
        assert config["axis_y2"]["label_angle"] == 90


# ===================================================================
# Category: labs() unknown key error
# ===================================================================


class TestLabsErrorContract:
    """Tests for labs() error handling.
    Targets chart.py labs() line 5231-5232.
    """

    def test_labs_unknown_key_raises(self, simple_df):
        """labs() with unknown key should raise ValueError.
        chart.py labs() line 5231: remaining keys raise ValueError."""
        with pytest.raises(ValueError, match="unknown label keys"):
            fm.Chart(simple_df).mark_point().encode(x="x", y="y").labs(z_axis="Z")

    def test_labs_multiple_unknown_keys_reports_all(self, simple_df):
        """labs() with multiple unknown keys should mention them in the error."""
        with pytest.raises(ValueError, match="unknown label keys"):
            fm.Chart(simple_df).mark_point().encode(x="x", y="y").labs(foo="Foo", bar="Bar")


# ===================================================================
# Category: Annotations rendered in SVG output
# ===================================================================


class TestAnnotationsRenderedInSvg:
    """Tests that annotations actually appear in the rendered SVG output.
    Annotations flow through _resolve_chart_config -> Rust scene_build.
    """

    def test_text_annotation_appears_in_svg(self, simple_df):
        """A text annotation at a data coordinate should produce text elements in SVG."""
        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y")
        chart = chart + ann.text(3.0, 3.0, "Annotation Text")
        svg = chart.to_svg()
        assert "<svg" in svg
        # The annotation text should appear somewhere in the SVG output
        assert "Annotation Text" in svg

    def test_line_annotation_appears_in_svg(self, simple_df):
        """A line annotation should add a line/path element to the SVG."""
        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y")
        chart = chart + ann.line(1.0, 1.0, 5.0, 5.0, stroke="red")
        svg = chart.to_svg()
        assert "<svg" in svg
        # No NaN should leak from annotation coordinates
        assert "NaN" not in svg

    def test_rect_annotation_appears_in_svg(self, simple_df):
        """A rect annotation should add a rect element to the SVG."""
        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y")
        chart = chart + ann.rect(1.0, 1.0, 4.0, 4.0, fill="lightblue", opacity=0.3)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: catplot seed for jitter reproducibility
# ===================================================================


class TestCatplotSeed:
    """Tests for catplot seed= parameter wiring to Jitter.
    Targets distribution.py catplot line 549: Jitter(axis='x', width=0.4, seed=seed).
    """

    def test_catplot_strip_with_seed_renders(self, cat_float_df):
        """catplot(kind='strip', seed=42) should produce valid SVG."""
        chart = fm.catplot(cat_float_df, x="group", y="value", kind="strip", seed=42)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_catplot_strip_two_seeds_produce_same_svg(self, cat_float_df):
        """Same seed should produce identical SVGs (deterministic jitter)."""
        svg1 = fm.catplot(cat_float_df, x="group", y="value", kind="strip", seed=123).to_svg()
        svg2 = fm.catplot(cat_float_df, x="group", y="value", kind="strip", seed=123).to_svg()
        assert svg1 == svg2

    def test_catplot_strip_different_seeds_differ(self, cat_float_df):
        """Different seeds should produce different SVGs (non-trivial jitter)."""
        svg1 = fm.catplot(cat_float_df, x="group", y="value", kind="strip", seed=1).to_svg()
        svg2 = fm.catplot(cat_float_df, x="group", y="value", kind="strip", seed=999).to_svg()
        # They might differ in point positions if jitter is non-trivial
        # If both are identical, jitter is either disabled or seed is ignored
        # We just assert both are valid
        assert "<svg" in svg1
        assert "<svg" in svg2


# ===================================================================
# Category: NaN in hue columns across figure functions
# ===================================================================


class TestNanInHueColumn:
    """Tests with NaN or null in the hue (color) column for figure functions."""

    def test_displot_hist_nan_in_hue(self):
        """displot hist with null values in the hue column should not crash."""
        df = pl.DataFrame(
            {
                "val": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
                "grp": ["A", None, "B", "A", None, "B"],
            }
        )
        chart = fm.displot(df, x="val", hue="grp")
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_relplot_nan_in_hue(self, hue_df):
        """relplot with null values in the hue column should not crash."""
        df = hue_df.with_columns(
            pl.when(pl.col("group") == "A").then(None).otherwise(pl.col("group")).alias("group")
        )
        chart = fm.relplot(df, x="x", y="y", hue="group")
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_lmplot_nan_in_hue(self):
        """lmplot with null values in the hue column should not crash."""
        df = pl.DataFrame(
            {
                "x": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0],
                "y": [2.0, 4.0, 3.0, 5.0, 6.0, 8.0, 7.0, 9.0],
                "grp": ["A", None, "B", "A", None, "B", "A", "B"],
            }
        )
        chart = fm.lmplot(df, x="x", y="y", hue="grp", ci=None, show_metrics=False)
        svg = chart.to_svg()
        assert "<svg" in svg


# ===================================================================
# Category: configure on HConcat/VConcat composed charts
# ===================================================================


class TestConfigureOnComposedCharts:
    """Tests that configure_* works on HConcatChart/VConcatChart.
    Chart.__or__ (line 4189) and __and__ (line 4219) produce composed charts.
    """

    def test_hconcat_then_properties(self, simple_df):
        """HConcatChart should support .properties() for sizing."""
        left = fm.Chart(simple_df).mark_point().encode(x="x", y="y")
        right = fm.Chart(simple_df).mark_bar().encode(x="x", y="y")
        composed = left | right
        sized = composed.properties(width=400, height=300)
        svg = sized.to_svg()
        assert "<svg" in svg

    def test_vconcat_shows_valid_svg(self, simple_df):
        """VConcatChart should render valid SVG."""
        top = fm.Chart(simple_df).mark_point().encode(x="x", y="y")
        bottom = fm.Chart(simple_df).mark_bar().encode(x="x", y="y")
        composed = top & bottom
        svg = composed.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: mark_line(point=True) composition
# ===================================================================


class TestMarkLinePointOverlay:
    """Tests for mark_line(point=True) which creates a layered chart.
    Targets chart.py mark_line lines 648-653.
    """

    def test_mark_line_point_true_creates_layers(self, simple_df):
        """mark_line(point=True) should produce a layered chart (line + point).
        chart.py mark_line line 651-652: line_chart + point_chart."""
        chart = fm.Chart(simple_df).mark_line(point=True).encode(x="x", y="y")
        # Should be layered
        resolved = chart._resolve_pending()
        assert resolved._layers is not None
        assert len(resolved._layers) >= 2

    def test_mark_line_point_true_renders_svg(self, simple_df):
        """mark_line(point=True) should render valid SVG with both line and circle elements."""
        chart = fm.Chart(simple_df).mark_line(point=True).encode(x="x", y="y")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg
        # Should contain both line/path elements and circle elements
        assert "<circle" in svg or "<path" in svg

    def test_mark_line_point_true_then_configure(self, simple_df):
        """mark_line(point=True) + configure should not crash."""
        chart = (
            fm.Chart(simple_df)
            .mark_line(point=True)
            .encode(x="x", y="y")
            .configure_axis(label_angle=-30)
        )
        svg = chart.to_svg()
        assert "<svg" in svg


# ===================================================================
# Category: All-null column in figure functions
# ===================================================================


class TestAllNullColumn:
    """Tests with all-null columns in figure functions."""

    def test_displot_all_null_x_column(self):
        """displot with an all-null x column should produce valid SVG, not crash."""
        df = pl.DataFrame({"x": pl.Series([None, None, None], dtype=pl.Float64)})
        chart = fm.displot(df, x="x")
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_catplot_all_null_value_column(self):
        """catplot with all-null value column should not panic."""
        df = pl.DataFrame(
            {
                "group": ["a", "b", "c"],
                "value": pl.Series([None, None, None], dtype=pl.Float64),
            }
        )
        chart = fm.catplot(df, x="group", y="value", kind="strip")
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_relplot_all_null_y_column(self):
        """relplot with all-null y column should produce valid SVG."""
        df = pl.DataFrame(
            {
                "x": [1.0, 2.0, 3.0],
                "y": pl.Series([None, None, None], dtype=pl.Float64),
            }
        )
        chart = fm.relplot(df, x="x", y="y")
        svg = chart.to_svg()
        assert "<svg" in svg


# ===================================================================
# Category: configure_color domain+range interaction
# ===================================================================


class TestConfigureColorDomainRange:
    """Tests for ColorConfig with domain and range simultaneously.
    Targets configure.py ColorConfig lines 292-318.
    """

    def test_color_config_domain_and_range_in_dict(self):
        """ColorConfig with both domain and range should include both in to_dict."""
        cfg = ColorConfig(domain=["A", "B", "C"], range=["#ff0000", "#00ff00", "#0000ff"])
        d = cfg.to_dict()
        assert d["domain"] == ["A", "B", "C"]
        assert d["range"] == ["#ff0000", "#00ff00", "#0000ff"]

    def test_configure_color_domain_range_renders(
        self, hue_df
    ):  # BUG: ValueError: chart_config invalid type string expected f64 — string domain values crash Rust renderer
        """Chart with configure_color(domain=..., range=...) should render valid SVG."""
        chart = (
            fm.Chart(hue_df)
            .mark_point()
            .encode(x="x", y="y", color="group")
            .configure_color(domain=["A", "B", "C"], range=["#ff0000", "#00ff00", "#0000ff"])
        )
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_configure_color_scheme_and_range_coexist(self):
        """ColorConfig with scheme and range simultaneously should serialize both.
        Whether the renderer prioritizes one is implementation-defined, but serialization
        should not crash."""
        cfg = ColorConfig(scheme="tableau10", range=["#f00", "#0f0"])
        d = cfg.to_dict()
        assert "scheme" in d
        assert "range" in d


# ===================================================================
# Category: override + configure interaction on rendered SVG
# ===================================================================


class TestOverrideConfigureRenderedSvg:
    """Tests that both override() and configure() reach the renderer."""

    def test_override_and_configure_render_together(self, simple_df):
        """A chart with both override() and configure_axis() should render valid SVG.
        Exercises chart.py override() line 4775-4798 and configure pipeline.
        """
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .override(width=500)
            .configure_axis(label_angle=-45)
        )
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_override_and_multiple_configures(self, simple_df):
        """override + multiple configure_* calls should all be preserved."""
        chart = (
            fm.Chart(simple_df)
            .mark_point()
            .encode(x="x", y="y")
            .override(height=350)
            .configure_axis(label_angle=-30)
            .configure_legend(orient="bottom")
            .configure_grid(x=True, color="#eee")
        )
        svg = chart.to_svg()
        assert "<svg" in svg
        config = chart._resolve_chart_config()
        assert "axis" in config
        assert "legend" in config
        assert "grid" in config


# ===================================================================
# Category: catplot kind='count'
# ===================================================================


class TestCatplotCount:
    """Tests for catplot kind='count' which uses Aggregate transform.
    Targets distribution.py catplot lines 579-587.
    """

    def test_catplot_count_renders(self):
        """catplot(kind='count') should produce a bar chart with counts."""
        df = pl.DataFrame({"cat": ["a", "b", "a", "c", "b", "b", "a"]})
        chart = fm.catplot(df, x="cat", kind="count")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg
        # Should have bar/rect elements
        assert "<rect" in svg

    def test_catplot_count_orient_h(self):
        """catplot(kind='count', orient='h') should flip axes."""
        df = pl.DataFrame({"cat": ["a", "b", "a", "c", "b", "b", "a"]})
        chart = fm.catplot(df, y="cat", kind="count", orient="h")
        svg = chart.to_svg()
        assert "<svg" in svg


# ===================================================================
# Category: displot with kde and rug overlays
# ===================================================================


class TestDisplotOverlays:
    """Tests for displot kde=True and rug=True overlay flags.
    Targets distribution.py displot lines 270-279.
    """

    def test_displot_hist_with_kde_overlay(
        self, iris_df
    ):  # BUG: stat_kde column not found — histogram transform renames column, KDE overlay cannot find original
        """displot(kind='hist', kde=True) should layer a density curve on the histogram.
        distribution.py line 271-276: kde=True and kind != 'kde'."""
        chart = fm.displot(iris_df, x="sepal_length", kde=True)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_displot_hist_with_rug_overlay(self, iris_df):
        """displot(kind='hist', rug=True) should layer tick marks on the histogram.
        distribution.py line 277-279: rug=True and kind != 'rug'."""
        chart = fm.displot(iris_df, x="sepal_length", rug=True)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_displot_hist_with_both_kde_and_rug(
        self, iris_df
    ):  # BUG: stat_kde column not found — same root cause as kde=True overlay
        """displot(kde=True, rug=True) should layer both KDE and rug on histogram."""
        chart = fm.displot(iris_df, x="sepal_length", kde=True, rug=True)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: catplot with dodge=True and hue
# ===================================================================


class TestCatplotDodge:
    """Tests for catplot dodge=True with hue parameter.
    Targets distribution.py catplot lines 499-501.
    """

    def test_catplot_strip_dodge_with_hue(self):
        """catplot(kind='strip', dodge=True, hue=...) should use Dodge position.
        distribution.py line 500: Dodge(by=hue)."""
        df = pl.DataFrame(
            {
                "cat": (["a"] * 10 + ["b"] * 10),
                "val": [float(x) for x in range(20)],
                "grp": (["X", "Y"] * 10),
            }
        )
        chart = fm.catplot(df, x="cat", y="val", hue="grp", kind="strip", dodge=True)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_catplot_bar_dodge_with_hue(self):
        """catplot(kind='bar', dodge=True, hue=...) should produce side-by-side bars."""
        df = pl.DataFrame(
            {
                "cat": (["a"] * 4 + ["b"] * 4),
                "val": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0],
                "grp": (["X", "Y"] * 4),
            }
        )
        chart = fm.catplot(df, x="cat", y="val", hue="grp", kind="bar", dodge=True)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: displot faceting
# ===================================================================


class TestDisplotFaceting:
    """Tests for displot with col and row faceting.
    Targets distribution.py displot lines 312-318.
    """

    def test_displot_facet_col(self, iris_df):
        """displot with col= should produce a faceted chart."""
        chart = fm.displot(iris_df, x="sepal_length", col="species")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_displot_facet_row_and_col(self):
        """displot with both row= and col= should produce a grid facet."""
        df = pl.DataFrame(
            {
                "val": [float(x) for x in range(24)],
                "col_var": (["A", "B"] * 12),
                "row_var": (["X"] * 12 + ["Y"] * 12),
            }
        )
        chart = fm.displot(df, x="val", col="col_var", row="row_var")
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_catplot_facet_col(self, cat_float_df):
        """catplot with col= should produce a faceted chart."""
        df = cat_float_df.with_columns(
            pl.when(pl.col("value") > 7).then(pl.lit("hi")).otherwise(pl.lit("lo")).alias("split")
        )
        chart = fm.catplot(df, x="group", y="value", kind="strip", col="split")
        svg = chart.to_svg()
        assert "<svg" in svg


# ===================================================================
# Category: mark_circle and mark_square shortcuts
# ===================================================================


class TestMarkShortcuts:
    """Tests for mark_circle/mark_square which are aliases for mark_point.
    Targets chart.py mark_circle line 680, mark_square line 708.
    """

    def test_mark_circle_sets_shape(self, simple_df):
        """mark_circle() should produce a chart with mark='point' and shape='circle'.
        chart.py mark_circle line 681: mark_point(shape='circle')."""
        chart = fm.Chart(simple_df).mark_circle().encode(x="x", y="y")
        assert chart._mark == "point"
        assert chart._mark_kwargs.get("shape") == "circle"

    def test_mark_square_sets_shape(self, simple_df):
        """mark_square() should produce a chart with mark='point' and shape='square'.
        chart.py mark_square line 709: mark_point(shape='square')."""
        chart = fm.Chart(simple_df).mark_square().encode(x="x", y="y")
        assert chart._mark == "point"
        assert chart._mark_kwargs.get("shape") == "square"

    def test_mark_circle_renders(self, simple_df):
        """mark_circle should render valid SVG."""
        chart = fm.Chart(simple_df).mark_circle(size=80).encode(x="x", y="y")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: xlim / ylim convenience methods
# ===================================================================


class TestXlimYlim:
    """Tests for Chart.xlim/ylim convenience methods.
    Targets chart.py xlim line 4841-4876 and ylim line 4878-4913.
    """

    def test_xlim_sets_coord_cartesian(self, simple_df):
        """xlim() should set a CoordCartesian with the specified xlim.
        chart.py xlim line 4874: CoordCartesian(xlim=(lo, hi))."""
        from ferrum.coord import CoordCartesian

        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y").xlim(0, 10)
        assert isinstance(chart._coord, CoordCartesian)
        assert chart._coord.xlim == (0, 10)

    def test_ylim_sets_coord_cartesian(self, simple_df):
        """ylim() should set a CoordCartesian with the specified ylim."""
        from ferrum.coord import CoordCartesian

        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y").ylim(-5, 15)
        assert isinstance(chart._coord, CoordCartesian)
        assert chart._coord.ylim == (-5, 15)

    def test_xlim_then_ylim_preserves_both(self, simple_df):
        """xlim then ylim should preserve both limits.
        chart.py ylim line 4909: replaces existing CoordCartesian preserving xlim."""
        from ferrum.coord import CoordCartesian

        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y").xlim(0, 10).ylim(-5, 15)
        assert isinstance(chart._coord, CoordCartesian)
        assert chart._coord.xlim == (0, 10)
        assert chart._coord.ylim == (-5, 15)

    def test_xlim_ylim_renders(self, simple_df):
        """Chart with both xlim and ylim should render valid SVG."""
        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y").xlim(0, 10).ylim(0, 10)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: displot with log_scale
# ===================================================================


class TestDisplotLogScale:
    """Tests for displot log_scale parameter.
    Targets distribution.py displot lines 306-309.
    """

    def test_displot_log_scale_renders(self):
        """displot(log_scale=True) should set x encoding to log scale.
        distribution.py line 308: X(x, scale={'type': 'log'})."""
        df = pl.DataFrame({"x": [0.1, 1.0, 10.0, 100.0, 1000.0]})
        chart = fm.displot(df, x="x", log_scale=True)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: catplot with boxen and violin + configure
# ===================================================================


class TestCatplotCompositeWithConfigure:
    """Tests for catplot boxen/violin + configure interactions.
    Composite marks produce layered charts; configure must survive layering.
    """

    def test_catplot_boxen_with_configure(self, cat_float_df):
        """catplot(kind='boxen') + configure_axis should produce valid SVG."""
        chart = fm.catplot(cat_float_df, x="group", y="value", kind="boxen")
        chart = chart.configure_axis(label_angle=-45)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_catplot_violin_with_configure_legend(self, cat_float_df):
        """catplot(kind='violin') + configure_legend should produce valid SVG."""
        chart = fm.catplot(cat_float_df, x="group", y="value", kind="violin")
        chart = chart.configure_legend(orient="bottom")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: displot with cumulative=True
# ===================================================================


class TestDisplotCumulative:
    """Tests for displot cumulative parameter.
    Targets distribution.py displot lines 225-229 (hist) and 240 (kde).
    """

    def test_displot_hist_cumulative(self, iris_df):
        """displot(kind='hist', cumulative=True) should produce cumulative histogram."""
        chart = fm.displot(iris_df, x="sepal_length", cumulative=True)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_displot_kde_cumulative(self, iris_df):
        """displot(kind='kde', cumulative=True) should produce CDF.
        Note: cumulative is passed to mark_density kwargs but may not be
        explicitly wired; test that it does not crash."""
        chart = fm.displot(iris_df, x="sepal_length", kind="kde", cumulative=True)
        svg = chart.to_svg()
        assert "<svg" in svg


# ===================================================================
# Category: lmplot with x_jitter
# ===================================================================


class TestLmplotXJitter:
    """Tests for lmplot x_jitter parameter.
    Targets regression.py lmplot line 548: Jitter(axis='x', width=x_jitter).
    """

    def test_lmplot_with_x_jitter(self, simple_df):
        """lmplot(x_jitter=0.3) should apply Jitter to the scatter layer."""
        chart = fm.lmplot(simple_df, x="x", y="y", x_jitter=0.3, ci=None, show_metrics=False)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: Single-value data columns
# ===================================================================


class TestSingleValueColumns:
    """Tests with columns that have only a single distinct value (degenerate domain)."""

    def test_displot_single_unique_value_kde(self):
        """KDE with a single unique value (degenerate bandwidth estimation)."""
        df = pl.DataFrame({"x": [5.0] * 30})
        chart = fm.displot(df, x="x", kind="kde")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_relplot_constant_x(self):
        """relplot with constant x column (degenerate x domain)."""
        df = pl.DataFrame({"x": [3.0] * 10, "y": [float(i) for i in range(10)]})
        chart = fm.relplot(df, x="x", y="y")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_relplot_constant_y(self):
        """relplot with constant y column (degenerate y domain)."""
        df = pl.DataFrame({"x": [float(i) for i in range(10)], "y": [7.0] * 10})
        chart = fm.relplot(df, x="x", y="y")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: lmplot logx parameter
# ===================================================================


class TestLmplotLogx:
    """Tests for lmplot logx parameter.
    Targets regression.py lmplot lines 640-643.
    """

    def test_lmplot_logx_true(self):
        """lmplot(logx=True) should set x encoding to log scale."""
        df = pl.DataFrame({"x": [0.1, 1.0, 10.0, 100.0, 1000.0], "y": [1.0, 2.0, 3.0, 4.0, 5.0]})
        chart = fm.lmplot(df, x="x", y="y", logx=True, ci=None, show_metrics=False)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: catplot jitter=False
# ===================================================================


class TestCatplotJitterFalse:
    """Tests for catplot strip with jitter=False.
    Targets distribution.py catplot lines 551-552.
    """

    def test_catplot_strip_jitter_false(self, cat_float_df):
        """catplot(kind='strip', jitter=False) should use Identity position.
        distribution.py line 552: mark_point(position=Identity())."""
        chart = fm.catplot(cat_float_df, x="group", y="value", kind="strip", jitter=False)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: axis() method edge cases
# ===================================================================


class TestAxisMethod:
    """Tests for Chart.axis() method.
    Targets chart.py axis() lines 4370-4430.
    """

    def test_axis_show_false_hides_both(self, simple_df):
        """axis(show=False) should hide both axes.
        chart.py axis line 4422-4423."""
        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y").axis(show=False)
        assert chart._axis_x is False
        assert chart._axis_y is False

    def test_axis_show_and_x_raises(self, simple_df):
        """axis(show=..., x=...) should raise ValueError.
        chart.py axis line 4419-4420."""
        with pytest.raises(ValueError, match="show"):
            fm.Chart(simple_df).mark_point().encode(x="x", y="y").axis(show=False, x=True)

    def test_axis_x_false_y_true(self, simple_df):
        """axis(x=False, y=True) should hide x and show y."""
        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y").axis(x=False, y=True)
        assert chart._axis_x is False
        assert chart._axis_y is True

    def test_axis_false_renders_svg(self, simple_df):
        """Chart with axis(show=False) should still render valid SVG."""
        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y").axis(show=False)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: to_dict / to_json structural completeness
# ===================================================================


class TestToDictCompleteness:
    """Tests that to_dict/to_json capture all spec components."""

    def test_to_dict_includes_facet(self, iris_df):
        """to_dict should include facet when facet() was called."""
        chart = (
            fm.Chart(iris_df)
            .mark_point()
            .encode(x="sepal_length", y="sepal_width")
            .facet("species")
        )
        d = chart.to_dict()
        assert "facet" in d

    def test_to_json_pretty_print(self, simple_df):
        """to_json(indent=2) should produce indented JSON."""
        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y")
        j = chart.to_json(indent=2)
        assert "\n" in j
        # Should be valid JSON
        parsed = json.loads(j)
        assert parsed["mark"] == "point"

    def test_to_dict_captures_layers(self, simple_df):
        """to_dict for a layered chart should include layers array."""
        chart = fm.Chart(simple_df).mark_point().encode(x="x", y="y") + fm.Chart(
            simple_df
        ).mark_line().encode(x="x", y="y")
        d = chart.to_dict()
        assert "layers" in d
        assert len(d["layers"]) >= 2


# ===================================================================
# Category: displot stat='density'
# ===================================================================


class TestDisplotStatDensity:
    """Tests for displot stat='density' normalization.
    Targets distribution.py displot line 226: density=(stat == 'density').
    """

    def test_displot_stat_density(self, iris_df):
        """displot(stat='density') should normalize the histogram to a probability density."""
        chart = fm.displot(iris_df, x="sepal_length", stat="density")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: catplot point and bar kinds
# ===================================================================


class TestCatplotPointBar:
    """Tests for catplot kind='point' and kind='bar' (non-composite).
    Targets distribution.py catplot lines 573-576.
    """

    def test_catplot_point_kind(self, cat_float_df):
        """catplot(kind='point') should render mark_point."""
        chart = fm.catplot(cat_float_df, x="group", y="value", kind="point")
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_catplot_bar_kind(self, cat_float_df):
        """catplot(kind='bar') should render mark_bar."""
        chart = fm.catplot(cat_float_df, x="group", y="value", kind="bar")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "<rect" in svg


# ===================================================================
# Category: Infinity and extreme floats in figure functions
# ===================================================================


class TestInfinityInFigureFunctions:
    """Tests with infinity and extreme float values in figure-level functions."""

    def test_displot_with_inf_in_data(self):
        """displot with inf in the data should not produce Infinity in SVG."""
        df = pl.DataFrame({"x": [1.0, 2.0, float("inf"), 4.0, 5.0]})
        chart = fm.displot(df, x="x")
        svg = chart.to_svg()
        assert "<svg" in svg

    def test_relplot_with_neg_inf(self):
        """relplot with -inf in y should not crash."""
        df = pl.DataFrame({"x": [1.0, 2.0, 3.0], "y": [1.0, float("-inf"), 3.0]})
        chart = fm.relplot(df, x="x", y="y")
        svg = chart.to_svg()
        assert "<svg" in svg


# ===================================================================
# Category: Mixed integer/float columns in figure functions
# ===================================================================


class TestMixedIntFloatColumns:
    """Tests with integer columns where float is normally expected."""

    def test_displot_integer_column(self):
        """displot with pure integer column should work via CDI coercion."""
        df = pl.DataFrame({"x": [1, 2, 3, 4, 5, 3, 2, 4, 3, 2]})
        chart = fm.displot(df, x="x")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_relplot_integer_columns(self):
        """relplot with integer x and y columns should work."""
        df = pl.DataFrame({"x": [1, 2, 3, 4, 5], "y": [5, 4, 3, 2, 1]})
        chart = fm.relplot(df, x="x", y="y")
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_lmplot_integer_columns(
        self,
    ):  # BUG: stat_smooth 'x' must be Float64 — lmplot does not auto-cast integer columns to Float64
        """lmplot with integer columns should not crash the Smooth transform."""
        df = pl.DataFrame({"x": [1, 2, 3, 4, 5], "y": [2, 4, 5, 4, 5]})
        chart = fm.lmplot(df, x="x", y="y", ci=None, show_metrics=False)
        svg = chart.to_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===================================================================
# Category: __repr__ correctness
# ===================================================================


class TestRepr:
    """Tests for Chart.__repr__ (chart.py line 5718-5734)."""

    def test_repr_after_configure(self, simple_df):
        """__repr__ should still work after configure calls."""
        chart = (
            fm.Chart(simple_df).mark_point().encode(x="x", y="y").configure_axis(label_angle=-45)
        )
        r = repr(chart)
        assert "Chart" in r
        assert "point" in r

    def test_repr_with_no_mark(self, simple_df):
        """__repr__ for a chart with no mark should not crash."""
        chart = fm.Chart(simple_df)
        r = repr(chart)
        assert "Chart" in r

    def test_repr_with_no_encoding(self, simple_df):
        """__repr__ for a chart with mark but no encoding should show empty list."""
        chart = fm.Chart(simple_df).mark_point()
        r = repr(chart)
        assert "[]" in r


# ===================================================================
# Category: facet validation
# ===================================================================


class TestFacetValidation:
    """Tests for facet() method validation.
    Targets chart.py facet() lines 4305-4336.
    """

    def test_facet_no_args_raises(self, simple_df):
        """facet() with no arguments should raise ValueError.
        chart.py facet line 4335-4336."""
        with pytest.raises(ValueError, match="facet"):
            fm.Chart(simple_df).mark_point().encode(x="x", y="y").facet()

    def test_facet_field_string(self, iris_df):
        """facet(field='species') should set wrap mode."""
        chart = (
            fm.Chart(iris_df)
            .mark_point()
            .encode(x="sepal_length", y="sepal_width")
            .facet("species")
        )
        assert chart._facet is not None
        assert chart._facet.mode_kind == "wrap"
        assert chart._facet.field == "species"

    def test_facet_grid_mode(self):
        """facet(row=..., col=...) should set grid mode."""
        df = pl.DataFrame(
            {
                "x": [1.0, 2.0, 3.0, 4.0],
                "y": [1.0, 2.0, 3.0, 4.0],
                "r": ["R1", "R1", "R2", "R2"],
                "c": ["C1", "C2", "C1", "C2"],
            }
        )
        chart = fm.Chart(df).mark_point().encode(x="x", y="y").facet(row="r", col="c")
        assert chart._facet is not None
        assert chart._facet.mode_kind == "grid"
        assert chart._facet.row == "r"
        assert chart._facet.col == "c"
