"""Edge-case tests for figure-api — generated by bug-hunter agent."""

from __future__ import annotations

import json
import math
import warnings

import polars as pl
import pytest

import ferrum as fr


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def small_df():
    return pl.DataFrame({"x": [1.0, 2.0, 3.0, 4.0, 5.0], "y": [2.0, 4.0, 3.0, 5.0, 1.0]})


@pytest.fixture
def cat_df():
    return pl.DataFrame(
        {
            "group": ["a", "a", "a", "b", "b", "b"],
            "val": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0],
        }
    )


@pytest.fixture
def wide_df():
    return pl.DataFrame(
        {
            "row": ["r1", "r2", "r3"],
            "A": [1.0, 2.0, 3.0],
            "B": [4.0, 5.0, 6.0],
        }
    )


# ===========================================================================
# Section 1: Histogram / displot with color encoding + unusual data
# ===========================================================================


class TestDisplotColorEdgeCases:
    """Focus: histogram auto-groupby from color + edge-case group shapes."""

    def test_displot_hist_single_group_with_hue(self):
        """displot(hist) with hue column containing a single unique group."""
        df = pl.DataFrame({"x": [1.0, 2.0, 3.0, 4.0, 5.0], "cat": ["only"] * 5})
        svg = fr.displot(df, x="x", hue="cat", kind="hist").show_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_displot_hist_empty_group_after_filter(self):
        """displot(hist) with hue where one group has values, another is empty (all null x).

        After binning, one group will have zero rows in some bins.
        """
        df = pl.DataFrame(
            {
                "x": [1.0, 2.0, 3.0, None, None, None],
                "cat": ["a", "a", "a", "b", "b", "b"],
            }
        )
        svg = fr.displot(df, x="x", hue="cat", kind="hist").show_svg()
        assert "<svg" in svg

    def test_displot_hist_many_groups_dodge(self):
        """displot(hist, multiple='dodge') with 10 groups — bin/group combos explode."""
        groups = [f"g{i}" for i in range(10)]
        x_vals = [float(v % 5) for v in range(50)]
        cats = [groups[i % 10] for i in range(50)]
        df = pl.DataFrame({"x": x_vals, "cat": cats})
        svg = fr.displot(df, x="x", hue="cat", multiple="dodge").show_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_displot_hist_stacked_two_groups_one_has_single_value(self):
        """Stacked histogram where one hue group has a single value — one bin only."""
        df = pl.DataFrame(
            {
                "x": [1.0, 2.0, 3.0, 4.0, 5.0, 3.0],
                "cat": ["a", "a", "a", "a", "a", "b"],
            }
        )
        svg = fr.displot(df, x="x", hue="cat", multiple="stack").show_svg()
        assert "<svg" in svg

    def test_displot_kde_single_group_with_hue(self):
        """KDE with hue containing a single group — should still render."""
        df = pl.DataFrame({"x": [1.0, 2.0, 3.0, 4.0], "cat": ["only"] * 4})
        svg = fr.displot(df, x="x", hue="cat", kind="kde").show_svg()
        assert "<svg" in svg

    def test_displot_kde_group_with_single_observation(self):
        """KDE hue where one group has only 1 observation — bandwidth is degenerate."""
        df = pl.DataFrame(
            {
                "x": [1.0, 2.0, 3.0, 4.0, 5.0, 10.0],
                "cat": ["a", "a", "a", "a", "a", "b"],
            }
        )
        svg = fr.displot(df, x="x", hue="cat", kind="kde").show_svg()
        assert "<svg" in svg

    def test_displot_hist_fill_position_with_hue(self):
        """displot(multiple='fill') — normalize stack should sum to 1.0 per bin."""
        df = pl.DataFrame(
            {
                "x": [1.0, 1.5, 2.0, 2.5, 3.0, 3.5] * 2,
                "cat": ["a"] * 6 + ["b"] * 6,
            }
        )
        chart = fr.displot(df, x="x", hue="cat", multiple="fill")
        d = json.loads(chart.to_spec().to_json())
        pos = d.get("position", {})
        assert pos.get("type") == "stack"
        assert pos.get("offset") == "normalize"
        svg = chart.show_svg()
        assert "<svg" in svg


# ===========================================================================
# Section 2: Layered charts with overlapping column names
# ===========================================================================


class TestLayeredColumnOverlap:
    """Focus: mark_rule layering bug with overlapping column names."""

    def test_mark_rule_plus_mark_point_same_y_field(self):
        """mark_rule(y=...) + mark_point(x=..., y=...) — both reference 'y' column."""
        df_points = pl.DataFrame({"x": [1.0, 2.0, 3.0], "y": [4.0, 5.0, 6.0]})
        df_rule = pl.DataFrame({"y": [5.0]})
        scatter = fr.Chart(df_points).mark_point().encode(x="x", y="y")
        rule = fr.Chart(df_rule).mark_rule().encode(y="y")
        svg = (scatter + rule).show_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_mark_rule_plus_mark_line_same_x_field(self):
        """mark_rule(x=...) + mark_line(x=..., y=...) — both use 'x' column."""
        df_line = pl.DataFrame({"x": [1.0, 2.0, 3.0, 4.0], "y": [1.0, 4.0, 9.0, 16.0]})
        df_rule = pl.DataFrame({"x": [2.5]})
        line = fr.Chart(df_line).mark_line().encode(x="x", y="y")
        rule = fr.Chart(df_rule).mark_rule().encode(x="x")
        svg = (line + rule).show_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_two_scatter_layers_different_data_same_columns(
        self,
    ):  # BUG: only 2 circles rendered instead of 4 — RHS layer data lost after column-rename merge
        """Two mark_point layers, different data, identical column names — rename path."""
        df1 = pl.DataFrame({"x": [1.0, 2.0], "y": [3.0, 4.0]})
        df2 = pl.DataFrame({"x": [5.0, 6.0], "y": [7.0, 8.0]})
        c1 = fr.Chart(df1).mark_point().encode(x="x", y="y")
        c2 = fr.Chart(df2).mark_point().encode(x="x", y="y")
        svg = (c1 + c2).show_svg()
        assert "<svg" in svg
        # Should render points from both DataFrames
        assert svg.count("<circle") >= 4

    def test_three_layers_accumulation_same_data(self):
        """point + line + rule from the same DataFrame — no rename needed."""
        df = pl.DataFrame({"x": [1.0, 2.0, 3.0], "y": [2.0, 4.0, 6.0]})
        c1 = fr.Chart(df).mark_point().encode(x="x", y="y")
        c2 = fr.Chart(df).mark_line().encode(x="x", y="y")
        c3 = fr.Chart(df).mark_rule().encode(y="y")
        svg = (c1 + c2 + c3).show_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_layer_with_smooth_and_rule_same_y(self):
        """mark_smooth layer + mark_rule layer referencing same 'y' — Identity transform path."""
        df = pl.DataFrame({"x": [1.0, 2.0, 3.0, 4.0, 5.0], "y": [2.1, 3.9, 6.1, 8.0, 9.8]})
        smooth = fr.Chart(df).mark_smooth(method="lm", ci=None).encode(x="x", y="y")
        rule_df = pl.DataFrame({"y": [5.0]})
        rule = fr.Chart(rule_df).mark_rule(stroke="red").encode(y="y")
        svg = (smooth + rule).show_svg()
        assert "<svg" in svg
        assert "NaN" not in svg


# ===========================================================================
# Section 3: lmplot / residplot with edge-case data shapes
# ===========================================================================


class TestLmplotResidplotEdgeCases:
    """Focus: figure functions with single row, all-same values, NaN-heavy columns."""

    def test_lmplot_single_row(self):
        """lmplot with a single data point — regression is degenerate."""
        df = pl.DataFrame({"x": [1.0], "y": [2.0]})
        chart = fr.lmplot(df, x="x", y="y", show_metrics=False, ci=None)
        svg = chart.show_svg()
        assert "<svg" in svg

    def test_lmplot_two_points_perfect_fit(self):
        """lmplot with exactly 2 points — perfect fit, zero residual."""
        df = pl.DataFrame({"x": [0.0, 1.0], "y": [0.0, 1.0]})
        chart = fr.lmplot(df, x="x", y="y", ci=None, show_metrics=False)
        svg = chart.show_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_lmplot_all_same_x_values(self):
        """lmplot where all x values are identical — undefined slope."""
        df = pl.DataFrame({"x": [5.0] * 10, "y": [i * 1.0 for i in range(10)]})
        chart = fr.lmplot(df, x="x", y="y", show_metrics=False, ci=None)
        svg = chart.show_svg()
        assert "<svg" in svg

    def test_lmplot_all_same_y_values(self):
        """lmplot where all y values are identical — horizontal line, R^2=0."""
        df = pl.DataFrame({"x": [1.0, 2.0, 3.0, 4.0, 5.0], "y": [3.0] * 5})
        chart = fr.lmplot(df, x="x", y="y", show_metrics=False, ci=None)
        svg = chart.show_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_lmplot_with_nan_in_y(self):
        """lmplot where y has NaN values — smooth transform should handle or skip."""
        df = pl.DataFrame(
            {"x": [1.0, 2.0, 3.0, 4.0, 5.0], "y": [1.0, float("nan"), 3.0, float("nan"), 5.0]}
        )
        chart = fr.lmplot(df, x="x", y="y", show_metrics=False, ci=None)
        svg = chart.show_svg()
        assert "<svg" in svg

    def test_residplot_all_null_y_produces_empty_svg(self):
        """residplot with all-null y and dropna=True leaves 0 rows — produces empty SVG."""
        df = pl.DataFrame({"x": [1.0, 2.0, 3.0, 4.0], "y": [None, None, None, None]})
        svg = fr.residplot(df, x="x", y="y").show_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_residplot_all_same_values(self):
        """residplot with constant x and y — residuals are all zero."""
        df = pl.DataFrame({"x": [5.0] * 10, "y": [3.0] * 10})
        chart = fr.residplot(df, x="x", y="y", show_metrics=False, zero_line=False)
        svg = chart.show_svg()
        assert "<svg" in svg

    def test_residplot_two_points(self):
        """residplot with exactly 2 points — residuals are all zero with OLS."""
        df = pl.DataFrame({"x": [0.0, 1.0], "y": [0.0, 1.0]})
        chart = fr.residplot(df, x="x", y="y", show_metrics=False, zero_line=False)
        svg = chart.show_svg()
        assert "<svg" in svg


# ===========================================================================
# Section 4: catplot with edge-case data shapes
# ===========================================================================


class TestCatplotEdgeCases:
    """Focus: catplot with single category, single observation per group, etc."""

    def test_catplot_box_single_category(self):
        """Box plot with one category — whisker/IQR from that single group."""
        df = pl.DataFrame({"cat": ["a"] * 5, "val": [1.0, 2.0, 3.0, 4.0, 5.0]})
        svg = fr.catplot(df, x="cat", y="val", kind="box").show_svg()
        assert "<svg" in svg

    def test_catplot_box_single_observation_per_group(self):
        """Box plot where each group has exactly 1 observation — IQR is zero."""
        df = pl.DataFrame({"cat": ["a", "b", "c"], "val": [1.0, 2.0, 3.0]})
        svg = fr.catplot(df, x="cat", y="val", kind="box").show_svg()
        assert "<svg" in svg

    def test_catplot_violin_single_observation(self):
        """Violin with 1 obs per group — KDE bandwidth estimation is degenerate."""
        df = pl.DataFrame({"cat": ["a", "b"], "val": [1.0, 5.0]})
        svg = fr.catplot(df, x="cat", y="val", kind="violin").show_svg()
        assert "<svg" in svg

    def test_catplot_strip_with_dodge_and_single_hue_level(self):
        """Strip with dodge=True but hue has a single level — dodge is a no-op."""
        df = pl.DataFrame(
            {"cat": ["a", "a", "b", "b"], "val": [1.0, 2.0, 3.0, 4.0], "h": ["x"] * 4}
        )
        svg = fr.catplot(df, x="cat", y="val", hue="h", kind="strip", dodge=True).show_svg()
        assert "<svg" in svg

    def test_catplot_count_no_y_column(self):
        """catplot(kind='count') should work without y= specified (counts x categories)."""
        df = pl.DataFrame({"cat": ["a", "a", "b", "b", "b", "c"]})
        chart = fr.catplot(df, x="cat", kind="count")
        svg = chart.show_svg()
        assert "<svg" in svg
        assert "<rect" in svg


# ===========================================================================
# Section 5: RepeatChart with various encoding combinations
# ===========================================================================


class TestRepeatChartEdgeCases:
    """Focus: RepeatPlaceholder guard and various encoding combos."""

    def test_repeat_with_mark_histogram(self):
        """RepeatChart + mark_histogram — placeholder defers desugar until expand."""
        df = pl.DataFrame({"a": [1.0, 2.0, 3.0, 4.0, 5.0], "b": [10.0, 20.0, 30.0, 40.0, 50.0]})
        base = fr.Chart(df).mark_histogram().encode(x=fr.Repeat.column)
        rc = fr.RepeatChart(base, column=["a", "b"])
        svg = rc.show_svg()
        assert "<svg" in svg

    def test_repeat_with_mark_density(self):
        """RepeatChart + mark_density — placeholder defers desugar until expand."""
        df = pl.DataFrame({"a": [1.0, 1.5, 2.0, 2.5, 3.0], "b": [2.0, 2.5, 3.0, 3.5, 4.0]})
        base = fr.Chart(df).mark_density().encode(x=fr.Repeat.column)
        rc = fr.RepeatChart(base, column=["a", "b"])
        svg = rc.show_svg()
        assert "<svg" in svg

    def test_repeat_with_mark_smooth(self):
        """RepeatChart + mark_smooth — placeholder defers desugar."""
        df = pl.DataFrame(
            {
                "x": [1.0, 2.0, 3.0, 4.0, 5.0],
                "a": [2.0, 4.0, 5.0, 8.0, 10.0],
                "b": [1.0, 1.5, 2.0, 2.5, 3.0],
            }
        )
        base = fr.Chart(df).mark_smooth(method="lm", ci=None).encode(x="x", y=fr.Repeat.row)
        rc = fr.RepeatChart(base, row=["a", "b"])
        svg = rc.show_svg()
        assert "<svg" in svg

    def test_repeat_single_field_row_and_column(self):
        """RepeatChart with 1 field in both row and column — 1x1 grid."""
        df = pl.DataFrame({"a": [1.0, 2.0, 3.0]})
        base = fr.Chart(df).mark_point().encode(x=fr.Repeat.column, y=fr.Repeat.row)
        rc = fr.RepeatChart(base, row=["a"], column=["a"])
        svg = rc.show_svg()
        assert "<svg" in svg

    def test_pairplot_auto_detects_all_numeric(self):
        """pairplot with no vars= should auto-detect all numeric columns."""
        df = pl.DataFrame(
            {
                "a": [1.0, 2.0, 3.0],
                "b": [4.0, 5.0, 6.0],
                "label": ["x", "y", "z"],
            }
        )
        rc = fr.pairplot(df)
        assert "label" not in rc.row
        assert set(rc.row) == {"a", "b"}

    def test_pairplot_corner_true_excludes_upper_triangle(self):
        """pairplot(corner=True) should set corner flag."""
        df = pl.DataFrame({"a": [1.0, 2.0], "b": [3.0, 4.0], "c": [5.0, 6.0]})
        rc = fr.pairplot(df, vars=["a", "b", "c"], corner=True)
        assert rc.corner is True


# ===========================================================================
# Section 6: Null / NaN in various positions
# ===========================================================================


class TestNullNaN:
    def test_chart_null_x_renders(self):
        """Chart with null values in x-encoded column should skip those rows."""
        df = pl.DataFrame({"x": [1.0, None, 3.0], "y": [1.0, 2.0, 3.0]})
        svg = fr.Chart(df).mark_point().encode(x="x", y="y").show_svg()
        assert "<svg" in svg
        assert "NaN" not in svg

    def test_chart_null_color_renders(self):
        """Chart with null values in a color encoding should render remaining rows."""
        df = pl.DataFrame({"x": [1.0, 2.0, 3.0], "y": [1.0, 2.0, 3.0], "c": ["a", None, "b"]})
        svg = fr.Chart(df).mark_point().encode(x="x", y="y", color="c").show_svg()
        assert "<svg" in svg

    def test_displot_all_null_x_does_not_crash(self):
        """displot on a column that is entirely null — degenerate but should not panic."""
        df = pl.DataFrame({"x": pl.Series([None, None, None], dtype=pl.Float64)})
        # May raise or produce empty svg, but must not panic/segfault
        try:
            svg = fr.displot(df, x="x").show_svg()
            assert "<svg" in svg
        except (ValueError, Exception):
            pass  # graceful error is acceptable


# ===========================================================================
# Section 7: Empty input (zero rows)
# ===========================================================================


class TestEmptyInput:
    def test_chart_zero_row_renders(self):
        """Zero-row DataFrame with mark_point should produce valid SVG."""
        df = pl.DataFrame(
            {"x": pl.Series([], dtype=pl.Float64), "y": pl.Series([], dtype=pl.Float64)}
        )
        svg = fr.Chart(df).mark_point().encode(x="x", y="y").show_svg()
        assert "<svg" in svg

    def test_displot_zero_row_renders(self):
        """displot on zero-row DataFrame should produce valid SVG."""
        df = pl.DataFrame({"x": pl.Series([], dtype=pl.Float64)})
        svg = fr.displot(df, x="x").show_svg()
        assert "<svg" in svg

    def test_catplot_zero_row_renders(self):
        """catplot on zero-row DataFrame should produce valid SVG."""
        df = pl.DataFrame(
            {
                "group": pl.Series([], dtype=pl.Utf8),
                "val": pl.Series([], dtype=pl.Float64),
            }
        )
        svg = fr.catplot(df, x="group", y="val", kind="strip").show_svg()
        assert "<svg" in svg


# ===========================================================================
# Section 8: Error contracts
# ===========================================================================


class TestErrorContracts:
    def test_displot_invalid_kind_raises(self):
        """displot with unknown kind should raise ValueError with legible message."""
        df = pl.DataFrame({"x": [1.0, 2.0]})
        with pytest.raises(ValueError, match="kind"):
            fr.displot(df, x="x", kind="bogus")

    def test_catplot_invalid_kind_raises(self):
        """catplot with unknown kind should raise ValueError."""
        df = pl.DataFrame({"cat": ["a", "b"], "val": [1.0, 2.0]})
        with pytest.raises(ValueError, match="kind"):
            fr.catplot(df, x="cat", y="val", kind="bogus")

    def test_lmplot_invalid_method_raises(self):
        """lmplot with unknown method should raise ValueError."""
        df = pl.DataFrame({"x": [1.0, 2.0], "y": [3.0, 4.0]})
        with pytest.raises(ValueError, match="method"):
            fr.lmplot(df, x="x", y="y", method="bogus")

    def test_repeat_chart_no_axis_raises(self):
        """RepeatChart with no row/column/layer raises ValueError."""
        df = pl.DataFrame({"a": [1.0]})
        base = fr.Chart(df).mark_point().encode(x="a")
        with pytest.raises(ValueError):
            fr.RepeatChart(base)

    def test_heatmap_no_numeric_columns_raises(self):
        """heatmap on a DataFrame with no numeric columns raises ValueError."""
        df = pl.DataFrame({"a": ["x", "y", "z"], "b": ["p", "q", "r"]})
        with pytest.raises(ValueError, match="numeric"):
            fr.heatmap(df)


# ===========================================================================
# Section 9: Spec round-trip and contract pins
# ===========================================================================


class TestSpecContracts:
    def test_to_spec_json_round_trip_preserves_mark(self, small_df):
        """to_spec → to_json → from_json should preserve mark field."""
        spec = fr.Chart(small_df).mark_point().encode(x="x", y="y").to_spec()
        j = spec.to_json()
        from ferrum import ChartSpec

        spec2 = ChartSpec.from_json(j)
        d = json.loads(spec2.to_json())
        assert d["mark"] == "point"

    def test_svg_viewbox_is_not_empty(self, small_df):
        """SVG output should contain a non-empty viewBox attribute."""
        svg = fr.Chart(small_df).mark_point().encode(x="x", y="y").show_svg()
        assert 'viewBox="' in svg

    def test_chart_immutable_fluent_chain(self, small_df):
        """Each fluent method returns a new Chart; original is unchanged."""
        base = fr.Chart(small_df).mark_point()
        encoded = base.encode(x="x", y="y")
        assert "x" not in base._encoding
        assert "x" in encoded._encoding

    def test_layered_chart_spec_has_layers_key(self, small_df):
        """Layered chart to_spec should have 'layers' in JSON."""
        c1 = fr.Chart(small_df).mark_point().encode(x="x", y="y")
        c2 = fr.Chart(small_df).mark_line().encode(x="x", y="y")
        layered = c1 + c2
        d = json.loads(layered.to_spec().to_json())
        assert "layers" in d
        assert len(d["layers"]) >= 2


# ===========================================================================
# Section 10: Type boundaries
# ===========================================================================


class TestTypeBoundaries:
    def test_integer_columns_for_xy(self):
        """Integer columns in x/y should render as quantitative."""
        df = pl.DataFrame({"x": [1, 2, 3], "y": [4, 5, 6]})
        svg = fr.Chart(df).mark_bar().encode(x="x", y="y").show_svg()
        assert "<svg" in svg

    def test_boolean_color_column(self):
        """Boolean column as color encoding should not crash."""
        df = pl.DataFrame({"x": [1.0, 2.0, 3.0], "y": [1.0, 2.0, 3.0], "flag": [True, False, True]})
        svg = fr.Chart(df).mark_point().encode(x="x", y="y", color="flag").show_svg()
        assert "<svg" in svg

    def test_string_column_in_x_axis_renders(self):
        """String column on x axis renders as ordinal."""
        df = pl.DataFrame({"cat": ["apple", "banana", "cherry"], "val": [10.0, 20.0, 15.0]})
        svg = fr.Chart(df).mark_bar().encode(x="cat", y="val").show_svg()
        assert "<svg" in svg
