"""Encoding channels — declarative mappings from data fields to visual variables."""

from ferrum.encoding.positional import (
    X,
    Y,
    X2,
    Y2,
    XError,
    YError,
    XError2,
    YError2,
    Theta,
    Radius,
)
from ferrum.encoding.appearance import (
    Color,
    Fill,
    Stroke,
    Opacity,
    FillOpacity,
    StrokeOpacity,
    StrokeWidth,
    StrokeDash,
    Size,
    Shape,
    Angle,
)
from ferrum.encoding.text import (
    Text,
    Detail,
    Tooltip,
    TooltipField,
    Href,
    Description,
    Key,
)
from ferrum.encoding.facet import Facet, FacetRow, FacetCol

__all__ = [
    "X",
    "Y",
    "X2",
    "Y2",
    "XError",
    "YError",
    "XError2",
    "YError2",
    "Theta",
    "Radius",
    "Color",
    "Fill",
    "Stroke",
    "Opacity",
    "FillOpacity",
    "StrokeOpacity",
    "StrokeWidth",
    "StrokeDash",
    "Size",
    "Shape",
    "Angle",
    "Text",
    "Detail",
    "Tooltip",
    "TooltipField",
    "Href",
    "Description",
    "Key",
    "Facet",
    "FacetRow",
    "FacetCol",
]
